<div class="seotoaster container refreshOnClose">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Add / Edit deeplink', 'helpSection' => $this->helpSection)); ?>
	<div class="content-footer">
			<form id="frm-deeplinks" action="<?php echo $this->url(); ?>" method="post" class="_fajax grid_12 mb15px form-inline" data-callback="loadDeeplinksList">
				<div class="grid_5 alpha">
					<?php echo $this->form->getElement('anchorText'); ?>
				</div>
				<div class="grid_5 alpha omega mt0px type-url">
					<label for="urlType"><?php echo $this->form->getElement('urlType') . $this->translate(' Local url');?></label>
					<?php echo $this->form->getElement('url'); ?>
					<label for="nofollow" class="nofollow">
						<?php echo $this->translate('No follow?'); ?>
						<?php echo $this->form->getElement('nofollow')->renderViewHelper(); ?>
					</label>
				</div>
				<?php echo $this->form->getElement('addDeeplink'); ?>
                <input type="hidden" name="secureToken" value="<?php echo $this->secureToken;?>" />
			</form>
		<div id="deeplinks-title" class="grid_12 list-title">
			<div class="grid_1 mr0 ml0 text-center"> <input type="checkbox" id="chk-all" name="deleteAll" /></div>
			<div class="grid_3 alpha omega ml-grid mr-grid">Anchor text</div>
			<div class="grid_6 alpha omega ml-grid">Url</div>
			<div class="grid_1 alpha omega text-center">Rel</div>
		</div>
		<div id="deeplinks-list" class="grid_12 items-list"></div>
	</div>
	<div class="grid_12 footer">
		<a href="javascript:;" id="deeplink-massdel-run" class="delete-selected btn link error">[ <?php echo $this->translate('Delete selected'); ?> ]</a>
		<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_saveandclose.phtml'); ?>
	</dv>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/deeplinks.min.js'); ?>