<?php if(!empty($this->deeplinks)): ?>
	<?php foreach($this->deeplinks as $deeplink): ?>
		<div class="deeplink-row list-row">
			<div class="grid_1 mr0 ml0 text-center">
				<input type="checkbox" id="<?php echo $deeplink->getId(); ?>" name="massdell[<?php echo $deeplink->getId(); ?>]" class="deeplink-massdel" />
			</div>
			<div class="list-row-item grid_3 alpha omega ml-grid mr-grid"><?php echo $deeplink->getName(); ?></div>
			<div class="list-row-item grid_6 alpha omega ml-grid"><?php echo ($deeplink->getType() == Application_Model_Models_Deeplink::TYPE_INTERNAL) ? $this->websiteUrl . $deeplink->getUrl() : $deeplink->getUrl(); ?></div>
			<div class="grid_1 alpha omega text-center"><?php echo ($deeplink->getNofollow()) ? $this->translate('No follow') : $this->translate('Follow'); ?></div>
			<div class="grid_1 omega ml0 text-center">
				<a class="remove-deeplink _tdelete ticon-remove error icon16" data-callback="loadDeeplinksList" data-url="<?php echo $this->toasterLink('seo', 'removedeeplink', '', '', true)?>" data-eid="<?php echo $deeplink->getId(); ?>" href="javascript:;"></a>
			</div>
		</div>
	<?php endforeach; ?>
<?php endif; ?>
