<div class="seotoaster container_12 h570 rounded3px refreshOnClose">
    <?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array('headerText' => 'Add / Edit deeplink', 'helpSection' => $this->helpSection)); ?>
    <div class="grid_12">
        <h1 class="ui-helper-reset mb10px" style="text-align:center;">
            <?php echo $this->translate('Deep Linking'); ?>
        </h1>
        <iframe width="845" height="460" style="display: block; margin-left: auto; margin-right: auto;"
                src="http://player.vimeo.com/video/37348256?title=0&amp;byline=0&amp;portrait=0" frameborder="0"
                webkitallowfullscreen="" mozallowfullscreen$></iframe>
    </div>
</div>
