<div class="seotoaster container_12 h640 rounded8px">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Manage silos')); ?>
	<form id="frm-sculpting" method="post" action="<?php echo $this->websiteUrl;?>backend/backend_seo/sculpting/" class="_fajax" data-callback="siloslist">
		<div class="grid_9">
			<?php echo $this->siloForm->getElement('name'); ?>
		</div>
		<div class="grid_3">
			<?php echo $this->siloForm->getElement('addSilo'); ?>
		</div>
	</form>
	<div class="grid_12">
	     <div class="silo-row grid_12" style="font-size:10pt;font-weight: bold;padding: 9px 0 5px;">
			<div class="grid_1"><input type="checkbox" name="chckAllSilos" class="check-all-silos" /></div>
			<div class="grid_9"><?php echo $this->translate('Name'); ?></div>
			<div class="grid_2" style="text-align:right;"><?php echo $this->translate('Action'); ?></div>
		</div>
	</div>
	<div id="silos-list" class="grid_12 h450"></div>

	<div class="grid_12" style="text-align: right;">
<!--		<button id="mass-del">Delete selected</button>-->
		<a href="javascript:;" class="delete-selected" id="mass-del">[ <?php echo $this->translate('Delete selected');?> ]</a>
	</div>
</div>

<script type="text/javascript" charset="utf-8">
	$(function() {
		$('#addSilo-label').hide();
		siloslist();

		$('#mass-del').click(function() {
			var silosIds= [];
			$('.rem-silos:checked').each(function() {
				silosIds.push($(this).attr('id'));
			});
			if(!silosIds.length) {
				showMessage('Select at least one item, please', true);
				return false;
			}
			showConfirm('You are about to remove one or many silos. Are you sure?', function() {
				$.ajax({
					url: $('#website_url').val() + 'backend/backend_seo/managesilos/',
					type: 'post',
					data: {
						act : 'remove',
						id  : silosIds
					},
					dataType: 'json',
					beforeSend: function() {showSpinner();},
					success: function(response) {
						hideSpinner();
						showMessage(response.responseText);
						$(silosIds).each(function() {
							$('#' + this).parent().parent().remove();
						});
					}
				});
			});
		});
	});

	function siloslist() {
		$('#silo-name').val('').focus();
		showSpinner();
		$.post($('#website_url').val() + 'backend/backend_seo/managesilos', {
			act: 'loadlist'
		}, function(response) {
			hideSpinner();
			$('#silos-list').html(response.responseText);
		})
	}
</script>