<div class="seotoaster container">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Manage silos')); ?>
	<div class="content-footer">
		<form id="frm-sculpting" method="post" action="<?php echo $this->websiteUrl;?>backend/backend_seo/sculpting/" class="_fajax grid_12 mb15px form-inline" data-callback="siloslist">
            <?php echo $this->siloForm->getElement('name'); ?>
			<?php echo $this->siloForm->getElement('addSilo'); ?>
		</form>
		<div class="grid_12 list-title">
			<div class="grid_1"><input type="checkbox" name="chckAllSilos" class="check-all-silos" /></div>
			<div class="grid_9"><?php echo $this->translate('Name'); ?></div>
			<div class="grid_2 text-center"><?php echo $this->translate('Action'); ?></div>
		</div>
		<div id="silos-list" class="grid_12 items-list scroll"></div>
	</div>
	<div class="grid_12 footer">
		<a href="javascript:;" id="mass-del" class="delete-selected btn block error"><?php echo $this->translate('Delete selected');?></a>
	</dv>
</div>

<script type="text/javascript" charset="utf-8">
	$(function() {
		$('#addSilo-label').hide();
		siloslist();

		$('.check-all-silos').click(function() {
			$('.rem-silos').prop('checked', ($(this).prop('checked')) ? true : false);
		});

		$('#mass-del').click(function() {
			var silosIds= [];
			$('.rem-silos:checked').each(function() {
				silosIds.push($(this).attr('id'));
			});
			if(!silosIds.length) {
				showMessage('Select at least one item, please', true);
				return false;
			}
			showConfirm('You are about to remove one or many silos. Are you sure?', function() {
				$.ajax({
					url: $('#website_url').val() + 'backend/backend_seo/managesilos/',
					type: 'post',
					data: {
						act : 'remove',
						id  : silosIds
					},
					dataType: 'json',
					beforeSend: function() {showSpinner();},
					success: function(response) {
						hideSpinner();
						showMessage(response.responseText);
						$(silosIds).each(function() {
							$('#' + this).parent().parent().remove();
						});
					}
				});
			});
		});
	});

	function siloslist() {
		$('#silo-name').val('').focus();
		showSpinner();
		$.post($('#website_url').val() + 'backend/backend_seo/managesilos', {
			act: 'loadlist'
		}, function(response) {
			hideSpinner();
			$('#silos-list').html(response.responseText);
			checkboxRadioStyle();
		})
	}
</script>