<?php if ($this->pageCount && $this->pageCount > 1): ?>
    <div class="paginator seo-paginator grid_12 omega">
        <?php if ($this->first != $this->current): ?>
            <a class="paginations" data-page="<?php echo $this->first.$this->filterUrl;?>"> <?php echo $this->translate('First');?></a>
        <?php else: ?>
            <span class="disabled"><?php echo $this->translate('First'); ?></span>
        <?php endif; ?>

        <?php if (isset($this->previous)): ?>
            <a class="paginations" data-page="<?php echo $this->previous.$this->filterUrl;?>"><?php echo $this->translate('Previous'); ?></a>
        <?php else: ?>
            <span class="disabled"><?php echo $this->translate('Previous'); ?></span>
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a class="paginations" data-page="<?php echo $page;?>"><?php echo $page; ?></a>
            <?php else: ?>
                <span class='current'><?php echo $page; ?></span>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)): ?>
            <a class="paginations" data-page="<?php echo $this->next.$this->filterUrl;?>"><?php echo $this->translate('Next'); ?></a>
        <?php else: ?>
            <span class="disabled"><?php echo $this->translate('Next'); ?></span>
        <?php endif; ?>

        <?php if ($this->last != $this->current): ?>
            <a class="paginations" data-page="<?php echo $this->last.$this->filterUrl;?>"> <?php echo $this->translate('Last');?></a>
        <?php else: ?>
            <span class="disabled"><?php echo $this->translate('Last'); ?></span>
        <?php endif; ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
    $(document).ready(function() {
        var seoPaginator = $('.seo-paginator').detach();
        $('#redirects-box').append(seoPaginator.get(0));
    });

    $('.paginations').click(function(e) {
        showSpinner();
        e.preventDefault();
        var pageNum = $(event.target).data('page');
        var name = $('#redirect-search').val();
            $.ajax({
                url: $('#website_url').val() + 'backend/backend_seo/loadredirectslist/paginationPnum/'+pageNum+'/searchName/'+name,
                type: 'post',
                dataType: 'json',
                success: function(response) {
                    hideSpinner();
                    $('#redirects-box').find('#redirects-list').html(response.redirectsList);
                }
            })
        })

</script>
