<div class="seotoaster container">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Add / Edit 301 redirect', 'helpSection' => $this->helpSection)); ?>
	<div class="content-footer">
		<form id="frm-redirects" class="_fajax grid_12 mb15px form-inline" action="<?php echo $this->url(); ?>" method="post" data-callback="reloadRedirectsList">
			<div class="grid_5 alpha">
				<?php echo $this->form->getElement('fromUrl'); ?>
			</div>
			<div class="grid_5 alpha omega type-url">
				<label><?php echo $this->form->getElement('urlType') . $this->translate('Local url');?></label>
				<?php echo $this->form->getElement('toUrl'); ?>
			</div>
			<?php echo $this->form->getElement('addRedirect')->renderViewHelper(); ?>
		</form>

		<div id="redirect-title" class="grid_12 list-title">
			<div class="grid_1 mr0 ml0 text-center"><input type="checkbox" id="massdell-main" /></div>
			<div class="grid_5 alpha omega ml-grid mr-grid"><?php echo $this->translate('Former url'); ?></div>
			<div class="grid_5 alpha omega ml-grid"><?php echo $this->translate('New url'); ?></div>
			<div class="grid_1 omega ml0 text-center"><?php echo $this->translate('Action'); ?></div>
		</div>
		<div id="redirects-list" class="grid_12 items-list"></div>
	</div>
	<div class="grid_12 footer">
<!--	<button class="mdel-button" id="massdel-run">--><?php //echo $this->translate('Delete selected'); ?><!--</button>-->
		<a href="javascript:;" class="delete-selected btn btn-link btn-error" id="massdel-run">[ Delete selected ]</a>
		<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_saveandclose.phtml'); ?>
	</dv>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/redirect.js'); ?>