<div class="seotoaster f-container">
    <?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array('headerText' => 'Edit robots.txt', 'helpSection' => $this->helpSection)); ?>
    <div class="grid_12">
        <h1 class="ui-helper-reset mb10px" style="text-align:center;">
            <?php echo $this->translate('Edit robots.txt'); ?>
        </h1>
        <iframe width="290" height="240" style="display: block; margin-left: auto; margin-right: auto;"
                src="//player.vimeo.com/video/47663772" frameborder="0" webkitallowfullscreen="" mozallowfullscreen=""
                allowfullscreen="">
        </iframe>
    </div>
</div>