<?php if(is_array($this->pages) && !empty ($this->pages)): ?>

	<?php foreach ($this->pages as $key => $pageData): ?>
		<div class="sculpting-row" style="overflow: hidden;">
			<div class="sculpting-subrow" style="overflow: hidden;">
				<div class="grid_6"><?php echo $pageData['label']; ?></div>
				<div class="grid_6"><?php echo $this->translate('Silo this category'); ?><input type="checkbox" value="<?php echo $key; ?>" name="siloCat[<?php echo $key; ?>]" class="silo-this-cat" <?php echo (isset($pageData['isSilo']) && $pageData['isSilo']) ? 'checked="checked"' : ''; ?>/></div>
			</div>
			<?php if(isset($pageData['subpages']) && is_array($pageData['subpages']) && !empty($pageData['subpages'])): ?>
				<?php foreach($pageData['subpages'] as $subPage): ?>
					<div class="sculpting-subrow" style="overflow: hidden;">
						<div class="grid_6"><?php echo $subPage->getNavName(); ?></div>
						<div class="grid_6"><?php echo $this->formSelect('siloSelect', (($subPage->getSiloId()) ? $subPage->getSiloId() : 0), array('id' => $subPage->getId(), 'class' => 'silo-select'), $this->silosOptions); ?></div>
					</div>
				<?php endforeach; ?>
			<?php endif; ?>
		</div>
	<?php endforeach; ?>

<?php endif; ?>
