<div class="seotoaster container">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Manage Page Rank Sculpting', 'helpSection' => $this->helpSection)); ?>
	<div class="content-footer grid_12">
		<form id="frm-sculpting" method="post" action="<?php echo $this->url(); ?>" class="_fajax grid_12 mb15px form-inline" data-callback="sculptingCallback">
			<div class="grid_9 alpha">
				<?php echo $this->siloForm->getElement('name'); ?>
			</div>
			<?php echo $this->siloForm->getElement('addSilo'); ?>
		</form>
		<div id="sculpting-list" class="grid_12"></div>
	</div>
	<div class="grid_12 footer" id="button-wrapper">
		<a class="tpopup btn link info" data-pwidth="480" data-pheight="560" href="javascript:;" data-url="<?php echo $this->websiteUrl;?>backend/backend_seo/managesilos/" id="manage-silos">[ <?php echo $this->translate('Manage silos'); ?> ]</a>
		<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_saveandclose.phtml'); ?>
	</div>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/sculpting.js'); ?>
