<?php if(is_array($this->silos) && !empty ($this->silos)): ?>
	<?php foreach ($this->silos as $key => $silo): ?>
		<div class="silo-row list-row">
			<label class="grid_1"><input id="<?php echo $silo->getId(); ?>" type="checkbox" name="remSilo[]" class="rem-silos" /></label>
			<div class="grid_10 list-row-item"><?php echo $silo->getName(); ?></div>
			<div class="grid_1">
				<a href="javascript:;" class="_tdelete ticon-remove error icon16" data-callback="siloslist" data-eid="<?php echo $silo->getId(); ?>" data-url="<?php echo $this->toasterLink('seo', 'managesilos', '', array('act' => 'remove'), true)?>"></a>
			</div>
		</div>
	<?php endforeach; ?>
<?php else: ?>
	<?php echo $this->translate('You have no silos yet'); ?>
<?php endif; ?>
