<?php echo '<?xml version="1.0" encoding="UTF-8"?>';?>
<?php if(is_array($this->pages) && !empty($this->pages)): ?>
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
            xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
            xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
        <?php foreach($this->pages as $page): ?>
            <?php if($page->getParentId() != Application_Model_Models_Page::IDCATEGORY_DRAFT): ?>
                <?php
                $url = $page->getUrl();
                // Path news page
                if (!empty($this->newsPageUrlPath)) {
                    if (in_array(Newslog::OPTION_PAGE_INDEX, $page->getExtraOptions())) {
                        $url = $this->newsPageUrlPath.'/';
                    }
                    elseif (in_array(Newslog::OPTION_PAGE_DEFAULT, $page->getExtraOptions())
                        || $page->getNews() === '1'
                    ) {
                        $url = $this->newsPageUrlPath.'/'.$url;
                    }
                }
                ?>
                <url>
                    <loc><?php echo $this->websiteUrl.(($page->getUrl() == 'index.html') ? '' : $url); ?></loc>
                    <lastmod><?php echo date('c', time()); ?></lastmod>
                    <changefreq><?php echo Tools_Content_Feed::SMFEED_CHANGEFREEQ; ?></changefreq>
                    <priority><?php echo ($page->getUrl() == Tools_Content_Feed::SMFEED_HIGHPRIORITY_PAGE_URL) ? '1' : '0.8'; ?></priority>
                </url>
            <?php endif; ?>
        <?php endforeach; ?>
        <url>
            <loc><?php echo $this->websiteUrl ."website.kml"; ?></loc>
            <lastmod><?php echo date('c', time()); ?></lastmod>
            <changefreq><?php echo Tools_Content_Feed::SMFEED_CHANGEFREEQ; ?></changefreq>
            <priority>0.8</priority>
        </url>
    </urlset>
<?php endif; ?>