<div id="seotoaster" class="editor">
	<div class="admineditwhat">
		<input type="checkbox" id="published" <?php echo ($this->published) ? 'checked="checked"' : ''; ?> />&nbsp;Published? OR publish on&nbsp;
		<?php echo $this->datePicker('datepicker', $this->publishingDate , array('defaultDate' => date('Y-m-d', time()), 'dateFormat' => 'yy-mm-dd')) ?>
	</div>
	<div id="ajax_msg" class="success" style="display: none;"><?php echo $this->translate('Working') . '...'; ?></div>
	<div id="ajax_msg_fail" class="errors" style="display: none;"><?php echo $this->translate('Oops. Error occured.'); ?></div>
	<div class="close_window" onclick="parent.tb_remove();"></div>
	<div id="admintextcontent">
		<?php
			$this->contentForm->setAction($this->url());
			echo $this->contentForm;
		?>
	</div>
	<?php echo $this->render('backend/content/righttoolbar.phtml'); ?>
	<a id="toogletinymce" href="javascript:;"><?php echo $this->translate('No Editor'); ?></a>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/tinymce/tiny_mce_gzip.js'); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/tinymce/jquery.tinymce.js'); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/tinymceInit.js'); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/content.js'); ?>
<?php //$this->jQuery()->addStylesheet($this->websiteUrl . 'system/css/datepicker.css'); ?>
