<button class="a2hs-button"><?= $this->buttonText; ?></button>
<script type="text/javascript">
  $(document).ready(function () {
    let deferredPrompt;
    const btnAdd = document.querySelector('.a2hs-button');
    if (!('serviceWorker' in navigator) || window.onbeforeinstallprompt === undefined) {
      btnAdd.classList.add('hidden');
    }
    window.addEventListener('beforeinstallprompt', (e) => {
      // Prevent Chrome 67 and earlier from automatically showing the prompt
      e.preventDefault();
      // Stash the event so it can be triggered later.
      deferredPrompt = e;
    });

    btnAdd.addEventListener('click', (e) => {
      // hide our user interface that shows our A2HS button
      btnAdd.classList.add('hidden');
      // Show the prompt
      deferredPrompt.prompt();
      // Wait for the user to respond to the prompt
      deferredPrompt.userChoice.then(() => { deferredPrompt = null });
    });
  });
</script>
