{notadmin}
<script>
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
      <?php if(empty($this->scope)):?>
        navigator.serviceWorker.register('<?= $this->websiteUrl ?>sw.js');
      <?php else:?>
        navigator.serviceWorker.register('<?= $this->websiteUrl ?>sw.js', {scope: '<?php echo $this->scope;?>'});
      <?php endif;?>
    });
  }
</script>
{/notadmin}