<?php $this->headScript()->appendFile($this->websiteUrl.'system/js/external/underscore/underscore.min.js');?>
<div class="advancedPrepopSearch">
    <?php if(isset($this->prepopNameValues) && !empty($this->prepopNameValues)):?>
        <?php foreach($this->prepopNameValues as $prepopName => $prepopNameValue):?>
                <select class="searchAdvancedPrepop searchParams" name="<?php echo $prepopName?>">
                    <option value="select">select</option>
                    <?php asort($prepopNameValue);?>
                    <?php foreach($prepopNameValue as $value):?>
                        <?php if(in_array($prepopName,$this->prepopWithQuantity)):?>
                            <option value="<?php echo $value['content']?>"><?php echo $value['content']?><?php echo ' ('.$value['quantity'].')'?></option>
                        <?php else:?>
                            <option value="<?php echo $value['content']?>"><?php echo $value['content']?></option>
                        <?php endif;?>                
                   <?php endforeach;?>
                </select>
        <?php endforeach;?>
    <?php endif;?>
</div>
 
<?php $this->jQuery()->onLoadCaptureStart() ?>
     $(function() {
        var searchArray = <?php echo $this->searchArray;?>;
        var prepopNamePageIds = <?php echo $this->prepopNamePageIds;?>;
        $(document).on('change', '.searchAdvancedPrepop', function(e) {
            var prepopName = $(this).attr('name');
            var prepopSelectedValue = $("option:selected", this).val();
            var prepopSelectedIds = '';
            var prepopSelectNames = $(this).closest('.advancedPrepopSearch').find('select');
            var resultSelectedId = [];
            var selectsQuantity = 0;
            var selectsInSearch = 0;
            var diffPrepop = '';
                                    
            $.each(prepopSelectNames, function () {
                if($(this).attr('name') != prepopName){
                    $("option", this).attr("disabled","disabled");
                    $("option[value='select']", this).attr("disabled",false);
                }
                selectsInSearch = selectsInSearch + 1;
                if($("option:selected", this).val() != 'select'){
                    diffPrepop = $(this).attr('name');
                    var diffPrepopSelectedValue = $("option:selected", this).val();
                    $.each(prepopNamePageIds, function (name, ids) {
                        if(name == diffPrepop){
                            prepopSelectedIds = ids[diffPrepopSelectedValue];
                            if(_.isEmpty(resultSelectedId)){
                                resultSelectedId = prepopSelectedIds;
                            }else{
                                resultSelectedId = _.filter(prepopSelectedIds, function(num, key){ 
                                    return _.include(resultSelectedId, key);
                                });
                            }

                         }
                    });
                }
                if($("option:selected", this).val() == 'select'){
                   selectsQuantity = selectsQuantity +1;
                }
                    
            });
            if(selectsQuantity == selectsInSearch){
                resultSelectedId = _.keys(searchArray);
            }
                      
            var filtredValues = _.filter(searchArray, function(num, key){ 
                return _.include(resultSelectedId, key);
            });
            
            _.each(filtredValues, function(id, value){ 
                _.each(id, function(pValue, pName){
                    $('select[name="'+pName+'"] [value="'+pValue+'"]').attr("disabled",false);
                });
            });
            
            if(selectsQuantity == selectsInSearch - 1){
                $('select[name="'+diffPrepop+'"] option').attr("disabled",false);
            }
        });
    });
<?php $this->jQuery()->onLoadCaptureEnd() ?>



