<div itemscope itemtype="http://schema.org/WebSite" class="wrap-search-form">
    <meta itemprop="url" content="<?php echo $this->websiteUrl; ?>"/>
    <form itemprop="potentialAction" itemscope itemtype="http://schema.org/SearchAction"
         class="<?php echo $this->searchForm->getAttrib('class'); ?>">
        <meta itemprop="target"
              content="<?php echo $this->websiteUrl; ?><?php echo $this->searhResultPageUrl ?>?search={dropdownSearch}"/>
        <input itemprop="query-input" type="search" name="dropdownSearch" required/>
        <button class="hidden" type="submit"><?php echo $this->translate('Search'); ?></button>
    </form>
</div>
<script>
    $(function () {
        $(".<?php echo $this->searchForm->getAttrib('class'); ?>").on('submit', function (e) {
            e.preventDefault();
        });
        $('.<?php echo $this->searchForm->getAttrib('class'); ?> input').on('focus', function(){
            $(this).val('');
            $(this).autocomplete( "option", "appendTo", $(this).closest('div'));
            $(this).data("ui-autocomplete")._renderMenu = function (ul, items) {
                $.each(items, function (index, item) {
                    var $li = $('<li>'),
                        $img = $('<img>');
                    $img.attr({
                        src: item.src,
                        alt: item.value,
                        class: 'autocomplete-result-img'
                    });
                    $li.attr('data-value', item.value)
                        .append('<a href="' + item.url + '">')
                        .find('a').append($img).append(item.value);
                    $li.data("ui-autocomplete-item", item);
                    $li.appendTo(ul);
                });
                $('.autocomplete-result-img').wrap('<span></span>');
            };
        });
        $('.<?php echo $this->searchForm->getAttrib('class'); ?> input').autocomplete({
            minLength: 3,
            source: function (request, response) {
                $.ajax({
                    url: "<?php echo $this->websiteUrl;?>backend/search/dropdown/",
                    data: {
                        filterPageType: '<?php echo implode(',', $this->filterPageType);?>',
                        limit: <?php echo $this->limit;?>,
                        search: request.term
                    },
                    type: 'post',
                    dataType: 'json',
                    success: function (data) {
                        response($.map(data, function (item) {
                            return {
                                value: item.value,
                                src: item.src,
                                label: item.label,
                                url: item.url,
                            };
                        }))
                    },
                    error: function (e) {
                        console.log(e);
                    }
                });
            },
            select: function (event, ui) {
                if (ui) {
                    window.location.href = "<?php echo $this->websiteUrl;?>" + ui.item.url;
                }
                return false;
            },
            messages: {
                noResults: '',
                results: function () {
                }
            }
        });

    });
</script>