<form id="<?php echo $this->searchForm->getAttrib('id'); ?>"
      class="<?php echo $this->searchForm->getAttrib('class'); ?>">
    <?php echo $this->searchForm->getElement('search'); ?>
    <!--    <p><input type="submit" value="--><?php //echo $this->translate('Search'); ?><!--"/></p>-->
</form>

<script>
    $(function () {
        $("#<?php echo $this->searchForm->getAttrib('id'); ?>").on('submit', function (e) {
            e.preventDefault();
        });
        var dropdownData = {
            'useImage':
            <?php if ($this->useImage) {
            echo 'true';
        } else {
            echo 'false';
        }?>,
            'filterPageType': '<?php echo implode(',', $this->filterPageType);?>',
            'limit':
            <?php echo $this->limit;?>,
        };

        var urlAction = "<?php echo $this->websiteUrl;?>backend/search/dropdown/";
        $("#search").on('keyup', function () {
            if ($(this).val().length >= 3) {
                dropdownData.search = $(this).val();
                $.ajax({
                    url: urlAction,
                    data: dropdownData,
                    type: 'post',
                    dataType: 'json',
                    success: function (res) {
                        if (!jQuery.isEmptyObject(res)) {
                            var searchData = res;
                            console.log(searchData);
                            $('#search').autocomplete({
                                minLength: 3,
                                source: searchData,
                                select: function (event, ui) {
                                    if (ui) {
                                        window.location.href = "<?php echo $this->websiteUrl;?>" + ui.item.url;
                                    }
                                    return false;
                                },
                                position: { my : "right top", at: "right bottom" },
                                messages: {
                                    noResults: '',
                                    results: function () {
                                    }
                                }
                            });

                            $('#search').data("ui-autocomplete")._renderMenu = function (ul, items) {
                                $.each(items, function (index, item) {

                                    var $li = $('<li>'),
                                        $img = $('<img>');
                                    $img.attr({
                                        src: item.src,
                                        alt: item.value,
                                        class: 'autocomplete-result-img'
                                    });

                                    $li.attr('data-value', item.value)
                                        .append('<a href="' + item.url + '">')
                                        .find('a').append($img).append(item.value);
                                    $li.data("ui-autocomplete-item", item);
                                    $li.appendTo(ul);
                                });
                            };

                        }
                    },
                    error: function (e) {
                        console.log(e);
                    }
                });
            }
        });
    });
</script>