<form id="<?php echo $this->searchForm->getAttrib('id'); ?>" class="<?php echo $this->searchForm->getAttrib('class'); ?>" action="<?php echo $this->searchForm->getAction(); ?>"
      method="<?php echo $this->searchForm->getMethod(); ?>">
    <?php echo $this->searchForm->getElement('search'); ?>
    <?php if(!empty($this->subfolders)) :?>
        <input type="hidden" name="subfolders" id="subfolders" value="<?php echo $this->subfolders;?>">
    <?php endif;?>
    <button type="submit"><?php echo $this->translate('Search'); ?></button>
</form>
