<?php echo $this->searchForm; ?>
<?php //if($this->renewIndex): ?>
<!--    <script type="text/javascript">-->
<!--        $('#logoutul li a').one('click', function(e) {-->
<!--            e.preventDefault();-->
<!--            $.post('--><?php //echo $this->_websiteUrl;?><!--backend/search/managesearchindex/', {doaction: 'renew'}, function() {-->
<!--                window.location.href = --><?php //echo $this->_websiteUrl;?><!--'backend/login/logout/';-->
<!--            });-->
<!--        });-->
<!--    </script>-->
<?php //endif; ?>
