<div class="widget-control-img" id="search-img"></div>
<form class="wmc-block" action="javascript:;" id="search-widget-form" style="display: none;" method="post">

	<label class="nopad grid_12" for="search-results"><?php echo $this->translate('Select a search results page'); ?></label>
	<select class="nopad grid_12" id="search-results"></select>

	<label class="nopad grid_6" for="search-item-img"><?php echo $this->translate('Use image'); ?></label>
	<div class="grid_6 nopad">
		<input type="checkbox" id="search-item-img" />
		<input class="cropped" type="checkbox" id="search-item-img-crop" /><span class="nopad label cropped" style="display: inline;"><?php echo $this->translate('Cropped'); ?>?</span>
	</div>
	<div class="grid_12"><input class="formsubmit" type="submit" id="search-done" name="done" value="Done" /></div>
</form>

<script type="text/javascript">
	$(function() {
		$('.widget-control-img#search-img').click(function() {
			$('#widgets-header').text('<?php echo $this->translate('Search engine'); ?>').fadeIn();
			$('#widget-controls').html($('#search-widget-form').html());
			//$('#search-widget-form').slideDown();
		});

		if($('#search-results').length) {
			load();
		}
		$('#search-item-img').live('click', function() {
			$('#search-item-img-crop').attr('checked', false);
			if($(this).attr('checked')) {
				$('.cropped').show();
			}
			else {
				$('.cropped').hide();
			}
		});

		$('#search-done').live('click', function() {
			var imgType = '';
			if( $('#search-item-img').attr('checked') && $('#search-item-img-crop').attr('checked')) {
				imgType = ':imgc';
			}
			else if($('#search-item-img').attr('checked') && !$('#search-item-img-crop').attr('checked')) {
				imgType = ':img';
			}
			var searchWidget = '{$search:form:' + $('#search-results').val() + '}<br /><br />======== <strong>CODE TO INSERT IN "'
				+ $('#search-results option:selected').text() + '" page ONLY(remove from here)</strong>  ========  <br/>'
				+ '{$search:results' + (imgType) + '}';


			$('textarea.tinymce').tinymce().execCommand('mceInsertContent',false, searchWidget);
		})
	})

	function load() {
		$.getJSON($('#website_url').val() + 'backend/backend_page/listpages/', function(response) {
			$.each(response.responseData, function() {
				var optVal  = this.id;
				var optText = this.h1;
				$('#search-results')
					.append($('<option></option>').attr({
						value: optVal
					})
					.text(optText));
			})
		})
	}
</script>