<script type="text/javascript">
    function update() {
        var url = '<?php echo $this->websiteUrl ?>backend/backend_update/update';
        var $subBtn = $("input[type=submit]");
        if ($('input[type=checkbox]').is(':checked')) {
            url = url + '/withoutBackup/true';
        }
        $subBtn.attr("disabled", "disabled");
        $.ajax({
            url: url,
            dataType: 'json',
            timeout: 60000,
            beforeSend: function () {
                showSpinner();
            },
            success: function (response) {
                if (!response.error) {
                    if(!$("#progress").length){
                        $('.update-form').append('<ul id="progress" class="seo-tip grid_11"></ul>');
                    }
                    $("#progress").append('<li class="mb10px mleft10px">' + response.responseText.message + '</li>');

                    if (response.responseText.status == 0) {
                        $('.current-version').text('<?php echo $this->remoteVersion; ?>');
                        $subBtn.removeAttr("disabled");
                        hideSpinner();
                        return;
                    }
                    update();
                } else {
                    hideSpinner();
                    $subBtn.removeAttr("disabled");
                    $subBtn.val('Continue');
                    showMessage(response.responseText.message, true);
                }
            },
            error: function (err) {
                showMessage(err, true);
            }
        });
    }
    $(function () {
        $('#update').submit(function (e) {
            e.preventDefault();
            update();
        });
    });
</script>
<div class="seotoaster container">
    <?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Updater', 'helpSection' => $this->helpSection)); ?>
    <div class="content-small-footer update-form grid_12">
        <p class="message info">This is a beta version of the updater. Use at your own risk. You should create database dump before you start.</p>
        <p class="grid_6 text-center">Local toaster version: <strong class="current-version"><?php echo $this->localVersion; ?></strong></p>
        <p class="grid_6 text-center">Remote toaster version: <strong><?php echo $this->remoteVersion; ?></strong></p>
        <div class="what-new">
            <ul>
                <?php if (is_array($this->whatIsNew)) : ?>
                    <?php foreach ($this->whatIsNew as $news) : ?>
                        <li><?php echo $news ?></li>
                    <?php endforeach ?>
                <?php endif ?>
            </ul>
        </div>
    </div>
    <div class="footer grid_12">
        <form id="update" action="<?php echo $this->websiteUrl ?>backend/backend_update/update" method="get">
            <label class="fl-left">Without backup: <input type ="checkbox" name="withoutBackup" value = "true"></label>
            <input type="submit" name="update" value="<?php echo $this->translate('Update'); ?>">
        </form>
    </div>
</div>
