<?php if($this->newsItem): ?>
	<h2><?php echo $this->newsItem->getHeaderTitle();?></h2>
	<div class="news-intro">
		<?php echo $this->newsItem->getTeaserText();?>
	</div>
	<div class="news-text">
		<?php echo $this->newsItem->getText();?>
	</div>
	<style type="text/css">
		.news-intro {
			font-size: 18px;
			text-align: justify;
			margin: 3px;
			padding: 5px;
			font-style: italic;
		}

		.news-text {
			font-size: 25px;
			text-align: justify;
			padding: 5px;
		}
	</style>
<?php endif; ?>