<div id="newsScroller" onmouseover="stopScroller();" onmouseout="startScroller();">
	<?php $i=0; foreach ($this->newsList as $newsItem): ?>
		<div class="scrollerItem" style="display: <?php if ($i == 0): ;?>block<?php else: ?>none<?php endif; ?>;">
			<h2><a href="<?php echo $this->websiteUrl . $this->newsFolder . '/' . $newsItem->getUrl(); ?>"><?php echo $newsItem->getHeaderTitle();?></a></h2>
			<p><?php echo $newsItem->getTeaserText(); ?></p>
		</div>
	<?php $i++; endforeach; ?>
</div>
<script type="text/javascript">
$(function() {
	initScroller('newsScroller');
})

var scroller;
var scrollerInterval;
var started = false;

function initScroller(scrollerId) {
	scroller = document.getElementById(scrollerId);
	startScroller();
}

function showNextItem() {
    if (!started)
        return false;
	var scrollerItems = $('#'+scroller.id).find('div');
	if(scrollerItems.length > 0 && scrollerItems != 'undefined') {
		for (var i = 0; i < scrollerItems.length; i++) {
			if (scrollerItems[i].style.display == 'block') {
				$(scrollerItems[i]).hide()
				break;
			}
		}
		if (i+1 >= scrollerItems.length) {
			$(scrollerItems[0]).fadeIn('slow');
			$(scrollerItems[i+1]).css({'display':'block'});
		}
		else {
			$(scrollerItems[i+1]).fadeIn('slow');
			$(scrollerItems[i+1]).css({'display':'block'});
		}
	}
	else {
		return false;
	}
}

function startScroller() {
	if (!started) {
		started = true;
		scrollerInterval = setInterval('showNextItem()', 4000);
	}
}

function stopScroller() {
    if (started) {
        started = false;
		clearInterval(scrollerInterval);
	}
}
</script>