<div class="seotoaster container_12 w960 h640 rounded8px">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('innerHeaderHtml' => $this->render('backend/content/top.phtml'))); ?>
	<div class="grid_8 above-editor-links">
		<a href="#">Some Plugin here</a> | <a href="#">Some seotoaster.com communication</a> | <a href="#">HELP Screen</a> | <a id="toogletinymce" href="javascript:;">No editor</a>
		<?php
			$this->contentForm->setAction($this->url());
			echo $this->contentForm;
		?>
	</div>

	<?php $this->tabPane('tabs', $this->render('backend/content/righttoolbar.phtml'), array('title' => 'Content'));?>
	<?php $this->tabPane('tabs', 'Products tab', array('title' => 'Products'));?>
	<?php $this->tabPane('tabs', 'Something', array('title' => 'Tab3'));?>
	<?php echo $this->tabContainer('tabs', array(), array('class' => 'grid_4 tabs'));?>

</div>

<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/tinymce/jquery.tinymce.js'); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/tinymceInit.js'); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/content.js'); ?>