<!--$this->render('backend/content/top.phtml')-->
<div class="seotoaster container_12 w960 h650 rounded3px">
	<?php
		$draftOrLive = $this->toasterDraftorlive(array(
			'published'        => $this->contentForm->getPublished(),
			'publishAt'        => $this->publishingDate,
			'onselectCallback' => null
		));
		echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('innerHeaderHtml' => $draftOrLive));
	?>
	<div class="grid_8 above-editor-links">
		<div id="links">
			<a href="#">Help</a> | <a href="#">Latest toaster news</a> | <a id="toogletinymce" href="javascript:;"><?php echo $this->translate('No editor'); ?></a>
		</div>
		<?php
			/*$this->contentForm->setAction($this->url());
			echo $this->contentForm;*/
		?>
		<form id="frm_content" action="<?php echo $this->url(); ?>" method="post" enctype="application/x-www-form-urlencoded">
			<?php echo $this->contentForm->getElement('content'); ?>
			<?php echo $this->contentForm->getElement('containerType'); ?>
			<?php echo $this->contentForm->getElement('containerName'); ?>
			<?php echo $this->contentForm->getElement('pageId'); ?>
			<?php echo $this->contentForm->getElement('containerId'); ?>
		</form>
	</div>

	<?php $this->tabPane('tabs', $this->render('backend/content/righttoolbar.phtml'), array('title' => 'Content'));?>
	<?php $this->tabPane('tabs', 'Shopping', array('title' => 'Shopping'));?>
	<?php //$this->tabPane('tabs', 'Smth', array('title' => 'Tab3'));?>

	<?php if(isset($this->pluginsTabs) && is_array($this->pluginsTabs)): ?>

		<?php foreach($this->pluginsTabs as $tabData): ?>
			<?php $this->tabPane('tabs', $tabData['content'], array('title' => $tabData['title']));?>
		<?php endforeach; ?>

	<?php endif; ?>

	<?php echo $this->tabContainer('tabs', array(), array('class' => 'grid_4 tabs'));?>
	<?php echo $this->contentForm->getElement('submit'); ?>

</div>

<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/tinymce/jquery.tinymce.js'); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/tinymceInit.js'); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/content.js'); ?>

<script type="text/javascript">
	$(function() {
		$('#tabs ul').removeClass('ui-corner-all').addClass('ui-corner-top')
		$('#btn-submit').click(function(){
			$('#frm_content').submit();
		})
	})
</script>