<div class="seotoaster container">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('innerHeaderHtml' => 'Edit header', 'helpSection' => $this->helpSection)); ?>
    <form id="frm_content" action="<?php echo $this->url(); ?>" class="<?php echo $this->contentForm->getAttrib('class');?>" method="post" enctype="application/x-www-form-urlencoded">
        <dl class="zend_form">
            <?php echo $this->contentForm->getElement('content'); ?>
            <?php echo $this->contentForm->getElement('submit'); ?>
            <?php echo $this->contentForm->getElement('containerType'); ?>
            <?php echo $this->contentForm->getElement('containerName'); ?>
            <?php echo $this->contentForm->getElement('pageId'); ?>
            <?php echo $this->contentForm->getElement('containerId'); ?>
            <input type="hidden" name="secureToken" class="secureToken" value="<?php echo $this->secureToken;?>" />
        </dl>
    </form>
</div>