<div class="tab_content">
	<select name="adminselectimgfolder" id="adminselectimgfolder">
		<option value="0" selected="selected"><?php echo $this->translate('select folder'); ?></option>
		<?php if(isset($this->imageFolders) && is_array($this->imageFolders)): ?>
			<?php foreach ($this->imageFolders as $folder): ?>
				<option value="<?php echo $folder; ?>"><?php echo $folder; ?></option>
			<?php endforeach; ?>
		<?php endif; ?>
	</select>
	<div id="selector">
		<div id="borderfortoolbar">
			<div id="adminthingsviewer">
				<div id="small" class="button"><?php echo $this->translate('Small'); ?>&nbsp;<span>(<?php echo $this->imagesSizes['small']; ?>px)</span></div>
				<div id="images_small" class="show_div"><h3 style="text-align: center;"><?php echo $this->translate('Please, select a folder'); ?></h3></div>

				<div id="medium" class="button"><?php echo $this->translate('Medium'); ?>&nbsp;<span>(<?php echo $this->imagesSizes['medium']; ?>px)</span></div>
				<div id="images_medium" class="show_div"><h3 style="text-align: center;"><?php echo $this->translate('Please, select a folder'); ?></h3></div>

				<div id="large" class="button" ><?php echo $this->translate('Large'); ?>&nbsp;<span>(<?php echo $this->imagesSizes['large']; ?>px)</span></div>
				<div id="images_large" class="show_div"><h3 style="text-align: center;"><?php echo $this->translate('Please, select a folder'); ?></h3></div>

				<div id="original" class="button"><?php echo $this->translate('Original'); ?></div>
				<div id="images_original" class="show_div"><h3 style="text-align: center;"><?php echo $this->translate('Please, select a folder'); ?></h3></div>

				<div id="files" class="button"><?php echo $this->translate('Files'); ?></div>
				<div id="list_files" class="show_div"></div>

<!--				<div id="widgets" class="button"><?php echo $this->translate('Widgets Maker'); ?></div>
				<div id="widgets_maker" class="show_div"></div>-->

				<div id="upload_things_button" class="button">
					<a style="padding: 0px;" title="<?php echo $this->translate('Upload Things'); ?>" data-url="<?php echo $this->websiteUrl; ?>backend/backend_media/uploadthings/" data-pheight="504" data-pwidth="480" href="javascript:;" class="tpopup"><?php echo $this->translate('Upload Things'); ?></a>
				</div>
			</div>
		</div>
	</div>
</div>
<?php $this->jQuery()->addJavascript('$(function() {$(\'#adminthingsviewer\').accordion({autoHeight: false, navigation: true, collapsible: true, active: false})});'); ?>
<script type="text/javascript">
	$(function() {
		//var el = $('#adminselectimgfolder');
		$(document).on('change', '#adminselectimgfolder', function() {
			if($(this).val() != 0) {
				var el = $('#upload_things_button a');
				var dataUrl = el.data('url').replace(/folder\/.*/, '') + 'folder/' + $(this).val() + '/';
				el.data('url', dataUrl);
			}
			console.log(dataUrl);
		}).on('focus', '#adminselectimgfolder', function() {
			var el = $(this);
			$.get('<?php echo $this->websiteUrl; ?>backend/backend_content/refreshfolders/', function(response) {
			    if(!response.error) {
				    el.empty();
				    el.append('<option value="0" selected="selected"><?php echo $this->translate('Select folder'); ?></option>');
				    $.each(response.responseText, function(id, folderName) {
					    el.append('<option value="' + folderName + '">' + folderName + '</option>')
				    });
			    }
		    });
		});
	})
</script>