<input type="checkbox" id="published" <?php echo ($this->contentForm->getPublished()) ? 'checked="checked"' : ''; ?>/>
<?php echo $this->translate('Published');?>? &nbsp;&nbsp;<?php echo $this->translate('OR');?>&nbsp;&nbsp; <?php echo $this->translate('Publish Date');?>:

<?php echo $this->datePicker(
	'dpkr',
	date('M j, Y', ($this->publishingDate) ? strtotime($this->publishingDate) : time()),
	array(
		'defaultDate' => date('M j, Y', ($this->publishingDate) ? strtotime($this->publishingDate) : time())
	),
	array(
		'style' => 'width:200px !important; border-radius:2px;'
	));

?>
