<input type="checkbox" id="published" <?php echo ($this->contentForm->getPublished()) ? 'checked="checked"' : ''; ?>/>
Published Now? &nbsp;&nbsp;OR&nbsp;&nbsp; Publish Date:
<?php echo $this->datePicker('dpkr', date('Y-m-d', ($this->publishingDate) ? strtotime($this->publishingDate) : time()), array(
						'defaultDate' => date('Y-m-d', ($this->publishingDate) ? strtotime($this->publishingDate) : time())
			)
);?>
