<?php foreach($this->widgetsData as $key => $widgetData): ?>
    <?php $this->accordionPane('widgets_maker', $widgetData['content'], array(
        'title' => (isset($widgetData['title']) ? ((isset($widgetData['icons']) ? '<img src="' . $widgetData['icons'][0] . '" />' : '') . $widgetData['title']) : 'NOTITLE'),
    )); ?>
<?php endforeach; ?>
<?php echo $this->accordionContainer('widgets_maker'); ?>
<script type="text/javascript">
	$(function () {
        checkboxRadio();
        $('#widgets_maker').accordion({
            collapsible: true,
            active: false,
            icons: false,
            autoHeight: false
        });
        $(document).on('click', '.apply-widget', function () {
            var error = false;
            var widgetForm = $(this).closest('form');
            var widgetHtml = '{$' + widgetForm.data('name');
            widgetForm.find(':input:visible, label:visible>:checkbox').not('[type=hidden], [type=submit]').each(function () {
                if ($(this).attr('type') == 'checkbox' && !$(this).prop('checked')) {
                    if ($(this).hasClass('allowzero')) {
                        widgetHtml += ':0';
                    }
                    return;
                }
                if ($(this).hasClass('validate')) {
                    if (!$(this).val() || $(this).val() == 0) {
                        $(this).addClass('error');
                        error = true;
                    }
                }

                if (!error) {
                    if ($(this).val() == 'imgc') {
                        widgetHtml = widgetHtml.replace(':img', '');
                    }
                    widgetHtml += ':' + $(this).val();
                }
            });
            if (!error) {
                widgetHtml += '}';
                $('textarea.tinymce').tinymce().execCommand('mceInsertContent', false, widgetHtml);
            }
        });

        //loading forlders list
        $.getJSON($('#website_url').val() + 'backend/backend_media/loadfolders/img/1', function (response) {
            $.each(response.responseText, function (val) {
                $('.folders')
                    .append($('<option></option>').attr({
                        value: val
                    })
                        .text(val));
            })
        });
    })
</script>
