<ul class="listcategories">
	<?php if($this->categoriesList): ?>
        <?php foreach ($this->categoriesList as $page): ?>
			<li>
				<?php if($this->useImage): ?>
					<a class="page-teaser-image" href="<?php echo $this->escape($this->websiteUrl . $page->getUrl()); ?>" title="<?php echo $page->getH1(); ?>">
						<img src="<?php echo Tools_Page_Tools::getPreview($page, $this->crop); ?>" alt="<?php echo $page->getH1(); ?>"/>
					</a>
				<?php endif; ?>
				<a href="<?php echo $this->escape($this->websiteUrl . $page->getUrl()); ?>" title="<?php echo $page->getH1(); ?>" class="page-title"><?php echo $page->getNavName(); ?></a>
				<span><?php echo $page->getTeaserText(); ?></span>
			</li>
		<?php endforeach; ?>
	<?php endif; ?>
</ul>