<?php if(isset($this->pagesList)): ?>
    <?php if($this->ajax) :?>
        <ul class="listpages <?php echo md5($this->categoryName); ?> <?php echo $this->listClass; ?>">
            <li>Please wait...</li>
        </ul>
        <script type="text/javascript">
            $(function() {
                $.get('<?php echo $this->websiteUrl?>backend/backend_page/listpages', {'pageId': '<?php echo $this->pageId;?>'<?php if(isset($this->categoryName)): ?>, 'categoryName': '<?php echo $this->categoryName;?>'<?php endif;?>}, function(resp) {
                    var currentList = $('ul.<?php echo md5($this->categoryName); ?>');
                    $(currentList).empty();
                    for(var i = 0; i < resp.responseData.length; i++) {
                        $(currentList).append($('<li>')
                            <?php if($this->useImage): ?>
                                .append($('<a>').addClass('page-teaser-image').attr({'href': resp.responseData[i].url, 'title': resp.responseData[i].h1})
                                .append($('<img>').attr({'src': (resp.responseData[i].previewImage == '') ? $('#website_url').val() + 'system/images/noimage.png' : $('#website_url').val() + 'previews/' + resp.responseData[i].previewImage}))
                                )
                            <?php endif;?>
                            .append($('<a>').addClass('page-teaser-image').attr({'href': resp.responseData[i].url, 'title': resp.responseData[i].h1}).text(resp.responseData[i].navName))
                            .append($('<span>').text(resp.responseData[i].teaserText))
                        );
                    }
                }, 'json');
            });
        </script>
    <?php else: ?>
	<ul class="listpages <?php echo $this->listClass; ?>">
		<?php foreach ($this->pagesList as $page):  ?>
			<li>
                <?php if ($page->getExternalLinkStatus() === '1'): ?>
                    <?php $pageUrl = $this->escape($page->getExternalLink()); ?>
                    <?php $targetBlank = 'target="_blank"'; ?>
                <?php else: ?>
                    <?php $pageUrl = $this->escape($this->websiteUrl . $page->getUrl()); ?>
                    <?php $targetBlank = ''; ?>
                <?php endif; ?>
                <?php if($this->useImage): ?>
                    <?php $src =  Tools_Page_Tools::getPreview($page, $this->crop); ?>
					<a class="page-teaser-image" href="<?php echo $pageUrl; ?>" <?php echo $targetBlank;?> title="<?php echo $page->getH1(); ?>">
						<img src="<?php echo $src; ?>" alt="<?php echo $page->getH1(); ?>" />
					</a>
				<?php endif; ?>
				<a href="<?php echo $pageUrl; ?>" title="<?php echo $page->getH1(); ?>" <?php echo $targetBlank;?> class="page-title"><?php echo $page->getNavName(); ?></a>
				<span><?php echo $page->getTeaserText(); ?></span>
			 </li>
		<?php endforeach; ?>
	</ul>
    <?php endif; ?>
<?php else: ?>
	<!-- NO PAGES TO LIST -->
<?php endif; ?>