<script type="text/javascript">
	$(function(){
		$('#editcssform').submit(function(){
			$.ajax({
				url: $(this).attr('action'),
				type: $(this).attr('method'),
				data: $(this).serialize(),
				dataType: 'json',
				success: function(response){
					if (response.done) {
						$('#ajax_msg').text('CSS saved').delay(3000).fadeOut();
					}
				},
				beforeSend: function(){
					$('#ajax_msg_fail').hide();
					$('#ajax_msg').text('saving css content...').fadeIn();
				},
				error: function(){
					$('#ajax_msg').hide();
					$('#ajax_msg_fail').text('Error occured.').show();
				}
			})
			return false;
		});

		$('#csslist').bind('change',function(){
			$.ajax({
				url: '<?php echo $this->websiteUrl.$this->url(); ?>',
				type: 'POST',
				data: {"getcss": $(this).val()},
				dataType: 'json',
				success: function(response){
					if (response.done == true){
						$('#ajax_msg').fadeOut();
						$('#content').val(response.content).focus();
					}
				},
				beforeSend: function(){
					$('#ajax_msg_fail').hide();
					$('#ajax_msg').text('loading css content...').fadeIn();
				},
				error: function(){
					$('#ajax_msg').hide();
					$('#ajax_msg_fail').text('Error occured.').show();
				}
			});
		});

	});
</script>
<div class="seotoaster editor container_12 w960 rounded8px">
	<div class="header" style="overflow:hidden;">
		<div class="closebutton">Close</div>
		<label>Manage templates</label>
	</div>
	<?php
		$this->editcssForm->setAction($this->websiteUrl.$this->url());
	?>
	<form action="<?php echo $this->editcssForm->getAction(); ?>" id="<?php echo $this->editcssForm->getId(); ?>" method="<?php echo $this->editcssForm->getMethod(); ?>">
		<div class="grid_8">&nbsp;</div>
		<div class="grid_4"><?php echo $this->editcssForm->getElement('cssname')->removeDecorator('DtDdWrapper'); ?></div>
		<div class="grid_12"><?php echo $this->editcssForm->getElement('content'); ?></div>
		<?php echo $this->editcssForm->getElement('submit'); ?>
	</form>
	
</div>