<?php foreach ($this->templates as $template) : ?>
<div class="grid_3 template_item" title="<?php echo sprintf($this->translate('Click to edit %s template'), $template['name']); ?>">
	<div class="template_preview">
		<div class="h200 mt10px mb10px">
		<?php if ($template['preview_image']) : ?>
		<img src="<?php echo $this->websiteUrl.$template['preview_image']; ?>" alt="<?php echo $template['name']; ?>" />
		<?php else: ?>
		<img src="<?php echo $this->websiteUrl; ?>system/images/no_preview.png" alt="<?php echo $template['name']; ?>" />
		<?php endif; ?>
		</div>
		<div class="template_name">
			<?php echo $template['name']; ?>
			<?php if (!in_array($template['name'], $this->protectedTemplates)): ?>
			<div class="template_delete"><img style="vertical-align:middle;" src="<?php echo $this->websiteUrl;?>/system/images/delete.png" alt="<?php echo $this->translate('Delete');?>" /></div>
			<?php endif; ?>
		</div>
		<?php echo $this->formHidden('template-id', $template['name'], array('id' => 'template-id-'.$template['name'])); ?>
	</div>
	
</div>

<?php endforeach; ?>