<div class="seotoaster container_12 w960 h640 rounded8px">
	<div class="header" style="overflow:hidden;">
		<div class="closebutton">Close</div>
		<label>Manage templates</label>
	</div>
	<div id="templatelist" class="grid_12 alpha omega h550 ui-helper-clearfix ui-helper-reset" style="display: none;"></div>
	<?php $this->templateForm->setAction($this->websiteUrl.$this->url()); ?>
	<form action="<?php echo $this->templateForm->getAction(); ?>" id="<?php echo $this->templateForm->getId();?>" method="<?php echo $this->templateForm->getMethod();?>">
		<div class="grid_8">
			<div class="w300">
				<?php echo $this->templateForm->getElement('name'); ?>
			</div>
			<div class="clear mt5px"></div>
			<?php echo $this->templateForm->getElement('content'); ?>
		</div>

		<div class="grid_4">
			<div class="largebutton">
			<?php
			echo $this->ajaxLink(
				$this->translate('Select another template to edit'),
				$this->websiteUrl . 'backend/backend_theme/gettemplate/',
				array(
					'complete' => 'showTemplateList(data)'
				),
				array('listtemplates' => 'all')
				); ?>
			</div>
			<div class="mt20px textcentered h350 img-teaser">
				<p style="border:1px dashed red;">@todo: Upload image mechanism. Coming soon</p>
				<?php if(($previewImage = $this->templateForm->getElement('previewImage')->getValue()) != null): ?>
					<img id="template_preview" src="<?php echo $this->websiteUrl.$previewImage; ?>" alt="<?php echo $this->translate('Template preview'); ?>" />
				<?php else: ?>
					<img id="template_preview" src="<?php echo $this->websiteUrl; ?>system/images/no_image.png" alt="<?php echo $this->translate('Template preview'); ?>" />
				<?php endif; ?>
			</div>
		</div>
		<?php echo $this->templateForm->getElement('id')->setDecorators(array('ViewHelper')); ?>
		<?php echo $this->templateForm->getElement('previewImage')->setDecorators(array('ViewHelper')); ?>
		<div class="grid_4 textcentered  mt20px"><?php echo $this->templateForm->getElement('submit'); ?></div>
	</form>
	<div class="grid_12 clear"></div>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/theme.js'); ?>
