<?php $this->jQuery()->addJavascriptFile($this->websiteUrl.'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js'); ?>
<div class="seotoaster container">
	<?php echo $this->partial('admin'.DIRECTORY_SEPARATOR.'_header.phtml', array('headerText' => 'Remove things', 'helpSection' => $this->helpSection)); ?>
	<div class="grid_12 content-footer">
		<form id="removeForm" class="">
			<div class="grid_7 alpha">
			<?php echo $this->formSelect('folder', null, null, $this->listFolders); ?>
			</div>
            <label id="check-all-label" class="btn link grid_5 omega"><input type="checkbox" id="check-all" class="processed hidden"/>[ <?php echo $this->translate('Check all?'); ?> ]</label>
            <div id="filebrowser" class="grid_12 alpha omega mt15px">
                <ul>
                    <li><a href="#filebrowser-images" ><?php echo $this->translate('Images');?></a></li>
                    <li><a href="#filebrowser-files" ><?php echo $this->translate('Files');?></a></li>
                </ul>
                <div id="filebrowser-images" class="filebrowser-zone list-images"></div>
                <div id="filebrowser-files" class="filebrowser-zone"></div>
            </div>
		</form>
	</div>
	<div class="grid_12 footer">
		<button id="deleteBtn" class="btn block error"><?php echo $this->translate('Delete Selected');?></button>
	</div>
</div>
<script id="imageContainerTemplate" type="text/x-jquery-tmpl">
    <div class="file-container">
        <img src="${src}" alt="${name}" title="${name}" />
        <input type="checkbox" class="toremove hidden" name="removeImages[]" value="${name}" />
    </div>
</script>
<script id="fileContainerTemplate" type="text/x-jquery-tmpl">
    <div class="file-container">
        <label data-type="${name}">${name}</label>
        <input type="checkbox" class="toremove toremove-file hidden" name="removeFiles[]" value="${name}" />
    </div>
</script>
<script id="errorMsgTemplate" type="text/x-jquery-tmpl">
    <div class="ui-widget">
        <div class="ui-state-error">
            <p><span class="ui-icon ui-icon-alert"></span>${errorMsg}</p>
        </div>
    </div>
</script>
<script id="fileErrorTemplate" type="text/x-jquery-tmpl">
    <div class="ui-widget">
        <div class="ui-state-error">
            <p><span class="ui-icon ui-icon-alert"></span>
                <strong>${name}&nbsp;</strong>
                {{if errors instanceof Array}}
                <?php echo $this->translate('is used');?>
                {{each errors}}
                {{if $index > 0}} and {{/if}}
                <a href="<?php echo $this->websiteUrl;?>${$value}" target="_blank">here</a>. Please go remove or replace it with another image first so that your website stays pretty.
                {{/each}}
                {{else}}
                ${errors}
                {{/if}}
            </p>
        </div>
    </div>
</script>
<script>
    var btnCheckAll = $('#check-all'),
        btnDelete   = $('#deleteBtn');

    btnCheckAll.button();
    btnDelete.button();

    $('#ajax_msg').unbind('click').removeAttr('style').removeClass().html('').dialog({
        maxHeight: 500,
        width: 400,
        resizable: false,
        modal: true,
        autoOpen: false
    });

    $('#filebrowser').tabs({
        select: function(event, ui) {
            var total = $(ui.panel).find('input.toremove').size();
            var checked = $(ui.panel).find('input.toremove:checked').size();
            if (total > 0 && total === checked) {
                btnCheckAll.prop('checked', true);
            } else {
                btnCheckAll.prop('checked', false);
            }
            btnCheckAll.button('refresh');
        }
    });

    $('.ui-tabs-nav').removeClass('ui-corner-all').addClass('ui-corner-top');

    // disabling clicking on non-folder item
    $('#folder>option:first').prop('disabled', true);

    $('#folder').change(function(){
        $('.filebrowser-zone').html('');
        showSpinner();
        $('.counter').text('');

        if ($(this).val() == 0){
            return false;
        }

        $('#check-all:checked').prop('checked', false);

        $.ajax({
            url: '<?php echo $this->url(array('action'=>'getdirectorycontent'));?>',
            type: 'post',
            data: {folder: $(this).val()},
            dataType: 'json',
            success: function(response){
                $('#imageContainerTemplate').tmpl(response.imageList).appendTo('#filebrowser-images');
                $('#fileContainerTemplate').tmpl(response.filesList).appendTo('#filebrowser-files');
                hideSpinner();
            }
        });
    });

    /**
     * Handler for delete
     */
    $(document).on('click', '#deleteBtn', function(event) {
        event.preventDefault();
        var fileForm = $('#removeForm');
        if ($('#folder').val() === '0') {
            proccessError({errorMsg: '<?php echo $this->translate('No folder specified');?>'});
            return false;
        }

        if (fileForm.find('input.toremove:checked').size() == 0) {
            proccessError({errorMsg: '<?php echo $this->translate('Nothing to remove');?>'});
            return false;
        }

        $.ajax({
            url: '<?php echo $this->url(array('action' => 'removefile'));?>',
            type: 'post',
            data: fileForm.serialize(),
            dataType: 'json',
            beforeSend: function(){
                showSpinner()
            },
            complete: function(){
                hideSpinner()
            },
            success: function(response) {
                proccessError(response);

                if (response.hasOwnProperty('deleted') && response.deleted.length > 0) {
                    var removedFiles = [];
                    for (var i in response.deleted) {
                        $('#filebrowser').queue(function(next){
                            $('.file-container:has(input.toremove:checked[value="'+response.deleted[i]+'"])').remove();
                            next();
                        });
                    }
                }
                if (response.hasOwnProperty('folderRemoved')) {
                    if (response.folderRemoved === true){
                        $('#folder').find('option:selected').remove().end().val('0');
                    }
                }
            }
        });
    });

    $(document).on('toggleActive', '.file-container', function() {
        var $flag   = $(this).children('input.toremove');
        var $parent = $(this).parent('.filebrowser-zone');

        if ($flag.prop('checked')){
            $flag.prop('checked', false);
            $(this).removeClass('active');
            if ($parent.find('.active').size() < $parent.find('.file-container').size() ) {
                $('#check-all').prop('checked', false);
            }
        } else {
            $(this).addClass('active');
            $flag.prop('checked', true);
            if ($parent.find('.file-container:not(.active)').size() === 0){
                btnCheckAll.prop('checked', true);
            }
        }
        btnCheckAll.button('refresh');
    }).on('click', '.file-container', function() {
            $(this).trigger('toggleActive');
        }).on('click', '.file-container > input.toremove', function(event) {
            $(this).parent('.file-container').trigger('toggleActive');
        });

    /**
     * handling "check all" checkbox
     */
    $(document).on('change', '#check-all', function() {
        var selectedIndex = $( "#filebrowser" ).tabs('option', 'active');
        if (this.checked === true) {
            var items = $('.filebrowser-zone:eq('+selectedIndex+')').find('.file-container:not(.active)')
        } else {
            var items = $('.filebrowser-zone:eq('+selectedIndex+')').find('.file-container.active');
        }
        if (items.size()){
            items.trigger('toggleActive');
        }
    });
    $('#check-all-label').bind('click', function() {
        $('#check-all').trigger('change');
    });

    /**
     * function proccessing errors coming in ajax response to dialog box
     */
    function proccessError(ajaxResponse) {
        //var dialogHolder = $('#ajax_msg');
        var openFlag   = false;
        var errorsHtml = '';
        //dialogHolder.html('');

        if (ajaxResponse.hasOwnProperty('errorMsg')){
            errorsHtml = $('#errorMsgTemplate').tmpl(ajaxResponse);
            openFlag = true;
        }

        if (ajaxResponse.hasOwnProperty('errors')){
            if (ajaxResponse.errors !== false) {
                openFlag = true;
                errorsHtml = $('#fileErrorTemplate').tmpl(ajaxResponse.errors);
            }
        }

        if (openFlag){
            showMessage($('<div></div>').html(errorsHtml).html(), true);
        }
    }
</script>
