<div class="seotoaster container_12 h570 rounded3px">
    <?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array('headerText' => 'Remove things', 'helpSection' => $this->helpSection)); ?>
    <div class="grid_12">
        <h1 class="ui-helper-reset mb10px" style="text-align:center;">
            <?php echo $this->translate('Remove your files and images'); ?>
        </h1>
        <iframe width="400" height="420" style="display: block; margin-left: auto; margin-right: auto;"
                src="https://player.vimeo.com/video/37408304?title=0&amp;b$"
        </iframe>
    </div>
</div>