<div class="seotoaster container_12 h500 rounded3px">
    <?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array('headerText' => 'Upload things', 'helpSection' => $this->helpSection)); ?>
    <div class="grid_12">
        <h1 class="ui-helper-reset mb10px" style="text-align:center;">
            <?php echo $this->translate('Upload your files and images'); ?>
        </h1>
        <iframe width="400" height="370" style="display: block; margin-left: auto; margin-right: auto;"
                src="http://player.vimeo.com/video/37347832?title=0&amp;b$"></iframe>
    </div>
</div>
