<script>
    <?php $this->jQuery()->onLoadCaptureStart();?>
    $('.change-image-quality').attr('checked', true);
    $('#things-new-folder')
            .focus(function () {
                if ($(this).val() == $(this).attr('data-defaultlabel')) {
                    $(this).val('')
                }
            })
            .blur(function () {
                if ($(this).val() == '') {
                    $(this).val($(this).attr('data-defaultlabel'))
                }
            });
    <?php $this->jQuery()->onLoadCaptureEnd();?>
</script>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl.'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js'); ?>
<div class="seotoaster container">
    <?php echo $this->partial(
        'admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array('headerText' => 'Upload your files and images', 'helpSection' => $this->helpSection)
    ); ?>
    <div class="grid_12 content">
        <fieldset class="background mb10px">
            <div class="grid_5">
                <?php echo $this->formSelect(
                    'things-select-folder',
                    (isset($this->currFolder) ? $this->currFolder : null),
                    null,
                    $this->listFolders
                ); ?>
            </div>
            <span class="grid_2 or"><?php echo $this->translate('OR'); ?></span>
            <div class="grid_5">
                <?php
                $newFolderLabel = $this->translate('create new folder');
                echo $this->formText(
                    'things-new-folder',
                    null,
                    array(
                        'placeholder'       => $newFolderLabel,
                        'data-defaultlabel' => $newFolderLabel
                    )
                ); ?>
            </div>
        </fieldset>
        <div class="grid_8 alpha omega mt5px image-preview">
            <?php $hiddenClass = !empty($this->listPictures) ? '' : 'hidden';?>
            <label id="check-all-label" class="btn link grid_12 alpha omega <?php echo $hiddenClass;?>"><input type="checkbox" id="check-all" class="processed hidden"/>[ <?php echo $this->translate('Check all?'); ?> ]</label>
            <form id="removeForm" class="">
            <div id="filebrowser" class="grid_12 alpha omega mt0px">
                <ul>
                    <li><a href="#filebrowser-images" class="switch-tab" data-tab-type="images"><?php echo $this->translate('Images');?></a></li>
                    <li><a href="#filebrowser-files" class="switch-tab" data-tab-type="files"><?php echo $this->translate('Files');?></a></li>
                </ul>
                <div id="filebrowser-images" class="filebrowser-zone list-images1 content scroll column_4 full-width" style="height: 330px;">
                    <?php if(!empty($this->listPictures) && !empty($this->picturesPath)):?>
                        <?php foreach ($this->listPictures as $picture):?>
                            <div class="file-container grid_4 alpha">
                                <img title="<?php echo $picture;?>" alt="<?php echo $picture;?>" border="0" src="<?php echo $this->websiteUrl . $this->picturesPath . $picture;?>">
                                <input type="checkbox" class="toremove hidden" name="removeImages[]" value="<?php echo $picture;?>" />
                            </div>
                        <?php endforeach;?>
                    <?php endif;?>
                </div>
                <div id="filebrowser-files" class="filebrowser-zone grid_12 alpha omega scroll" style="height: 330px;">
                    <?php if(!empty($this->filesList)):?>
                        <?php foreach ($this->filesList as $file):?>
                            <div class="file-container">
                                <label data-type="<?php echo $file['name'];?>"><?php echo $file['name'];?></label>
                                <input type="checkbox" class="toremove toremove-file hidden" name="removeFiles[]" value="<?php echo $file['name'];?>">
                            </div>
                        <?php endforeach;?>
                    <?php endif;?>
                </div>
            </div>
            </form>

            <script id="imageContainerTemplate" type="text/x-jquery-tmpl">
            <div class="file-container grid_3 alpha">
                <div class="img-wrap-box"><img class="img-container" src="${src}" alt="${name}" title="${name}" /></div>
                <input type="checkbox" class="toremove hidden" name="removeImages[]" value="${name}" />
                <div class="grid_12 alpha omega img-edit-box">
                    <span class="btn ticon-pencil edit-name grid_3 alpha omega"></span>
                    <input type="text" class="img-name grid_12 alpha omega" data-extension="${imgExtension}" data-current-name="${clearImgName}" value="${clearImgName}" />
                    <span class="btn success success-btn ticon-checkmark grid_3 alpha omega" style="display:none;"></span>
                </div>
            </div>
            </script>
            <script id="fileContainerTemplate" type="text/x-jquery-tmpl">
            <div class="file-container img-container">
                <label data-type="${name}">${name}</label>
                <input type="checkbox" class="toremove toremove-file hidden" name="removeFiles[]" value="${name}" />
            </div>
            </script>
            <hr class="mb0px mt5px">
            <div class="deleteBtnBlock grid_12 mt5px alpha omega text-center">
                <div id="delete-info-msg" class="mt5px"><?php echo $this->translate('Please select least one element to delete');?></div>
                <div id="attention-info-msg" class="error hide mt5px"><?php echo $this->translate('Be careful when renaming files! The link to the file will be modified!');?></div>
                <button id="deleteBtn" class="btn error grid_12" style="display: none;"><?php echo $this->translate('Delete selected');?></button>
            </div>
        </div>
        <?php
        $mimetypes = '<div>' . $this->translate('File upload max size') . ': ' . $this->uploadMaxSize . '</div>';
        $mimetypes .= $this->translate('File extension formats'). ': ' . '<div>';
        foreach ($this->mimeTypes as $mimetype){
            $mimetypes .= ' '. $mimetype . ' ';
        }
        $mimetypes .= '</div>';

        ?>
        <div><i title="<?php echo $mimetypes;?>" class="grid_12 info-block-detailed tooltip fl-right ticon-info icon16"></i></div>
        <div class="grid_4 omega mb15px">

            <?php
            $thingsUploader = $this->toasterUploader(
                array(
                    'id'      => 'media-toaster-uploader',
                    'type'    => 'dragdrop',
                    'caption' => $this->translate('Drag & drop files here'),
                    'caller'  => 'media'
                )
            );
            echo $thingsUploader;
            ?>
            <label class="fl-right mt15px pointer"><input type="checkbox" name="change-image-quality"
                                                          class="change-image-quality"
                                                          value="0"/> <?php echo $this->translate(
                    'Optimize image size.'
                ); ?></label>
            <div id="media-toaster-uploader-filelist" class="grid_12 alpha omega ui-widget-content scroll mt10px h300px">
                <?php echo $this->translate('Upload progress will appear here.'); ?>
            </div>
        </div>
        <input type="hidden" class="secureToken" name="secureToken" value="<?php echo $this->secureToken;?>">
    </div>
</div>
<script type="text/javascript">

    $('.info-block-detailed').tooltip({
        content: "<?php echo $mimetypes;?>"
    });

    var btnCheckAll = $('#check-all'),
        btnDelete   = $('#deleteBtn');

    btnCheckAll.button();
    btnDelete.button();

    $('#filebrowser').tabs({
        select: function(event, ui) {
            var total = $(ui.panel).find('input.toremove').size();
            var checked = $(ui.panel).find('input.toremove:checked').size();
            if (total > 0 && total === checked) {
                btnCheckAll.prop('checked', true);
            } else {
                btnCheckAll.prop('checked', false);
            }
            btnCheckAll.button('refresh');
        }
    });

    $(document).on('toggleActive', '.img-wrap-box', function() {
        var fileContainerEl = $(this).closest('.file-container');
        var $flag   = fileContainerEl.find('input.toremove');
        var $parent = $(this).closest('.filebrowser-zone');
        var selectedIndex = $( "#filebrowser" ).tabs('option', 'active');

        $('.success-btn').hide();
        $('#attention-info-msg').addClass('hide');
        if ($flag.prop('checked')){
            $flag.prop('checked', false);
            fileContainerEl.removeClass('active');
            if ($parent.find('.active').size() < $parent.find('.file-container').size() ) {
                $('#check-all').prop('checked', false);
                fileContainerEl.css({'background': ''});
                fileContainerEl.find('img').css({'opacity': ''});
                $('.img-name').removeClass('grid_9').addClass('grid_12');
                $('.file-container').removeClass('editing');
                if($parent.find('.active').size() == 0) {
                    $('#delete-info-msg').removeClass('hide');
                    $('#deleteBtn').hide();
                    $('.img-name').prop('disabled',false);
                    $('.edit-name').removeClass('hidden');
                }
            }
            if($('#removeForm').find('input.toremove:checked').size() == 0) {
                $('#delete-info-msg').removeClass('hide');
                $('#deleteBtn').hide();
                $('.img-name').prop('disabled',false);
                $('.edit-name').removeClass('hidden');
            }
        } else {
            // fileContainerEl.addClass('active').css({'background': 'rgba(231,76,60,.2)'});
            fileContainerEl.addClass('active');
            fileContainerEl.find('img');
            $flag.prop('checked', true);
            if ($parent.find('.file-container:not(.active)').size() === 0){
                btnCheckAll.prop('checked', true);
            } else {
                if(selectedIndex == 0) {
                    $('.img-name').prop('disabled',true).removeClass('grid_9').addClass('grid_12');
                }
            }
                $('#delete-info-msg').addClass('hide');
                $('#deleteBtn').show();
                $('.edit-name').addClass('hidden');
        }
        btnCheckAll.button('refresh');
    }).on('click', '.img-wrap-box', function() {
        $(this).trigger('toggleActive');
    }).on('click', '.file-container > input.toremove', function(event) {
        $(this).parent('.file-container').trigger('toggleActive');
    });

    $(document).on('change', '#check-all', function() {
        var selectedIndex = $( "#filebrowser" ).tabs('option', 'active');
        if (this.checked === true) {
            var items = $('.filebrowser-zone:eq('+selectedIndex+')').find('.file-container:not(.active)')
        } else {
            var items = $('.filebrowser-zone:eq('+selectedIndex+')').find('.file-container.active');
            if(selectedIndex == 0) {
                $('.img-name').prop('disabled',false);
            }
        }
        if (items.size()){
            if(selectedIndex == 0) {
                items.find('.img-wrap-box').trigger('toggleActive');
                $('.img-name').prop('disabled',true).removeClass('grid_9').addClass('grid_12');
            } else {
                items.trigger('toggleActive');
            }
        }
    });

    $('#check-all-label').bind('click', function() {
        $('#check-all').trigger('change');
    });

    $('#things-select-folder').change(function(){
        $('.filebrowser-zone').html('');

        $('.counter').text('');

        if ($(this).val() == 0){
            $('#check-all-label').addClass('hidden');
            $('#delete-info-msg').removeClass('hide');
            $('#deleteBtn').hide();
            $('#attention-info-msg').addClass('hide');
            return false;
        }

        $('#check-all:checked').prop('checked', false);

        $.ajax({
            url: '<?php echo $this->websiteUrl;?>/backend/backend_media/getdirectorycontent/',
            type: 'post',
            data: {'folder': $(this).val()},
            dataType: 'json',
            beforeSend: function(){
                showSpinner()
            },
            complete: function(){
                hideSpinner()
            },
            success: function(response){
                var imgPreview = '';

                $('.file-container').empty();
                $('#check-all-label').removeClass('hidden');
                $('#delete-info-msg').removeClass('hide');
                $('#deleteBtn').hide();
                $('#attention-info-msg').addClass('hide');


                if(response.imageList.length > 0){
                    $('#imageContainerTemplate').tmpl(response.imageList).appendTo('#filebrowser-images');
                }
                if(response.filesList.length > 0){
                    $('#fileContainerTemplate').tmpl(response.filesList).appendTo('#filebrowser-files');
                }
                hideSpinner();
            }
        });
    });

    $(document).on('click', '.success-btn', function (e) {
        var currentEl = $(e.currentTarget).prev();
        if(currentEl.val() == currentEl.data('current-name')) {
            $('.success-btn').hide();
            $('.img-name').removeClass('grid_9').addClass('grid_12');
            $('.file-container').removeClass('editing');
            $('#attention-info-msg').addClass('hide');
            $('#delete-info-msg').removeClass('hide');
        }
    });

    $(document).on('click', '.switch-tab', function () {
        var type = $(this).data('tab-type'),
            typeBlock = $('#filebrowser-' + type),
            content = typeBlock.find('.file-container'),
            selectedIndex = $( "#filebrowser" ).tabs('option', 'active');
        if(content.length > 0){
            $('#check-all-label').removeClass('hidden');
            if(typeBlock.find('input.toremove:checked').size() > 0) {
                $('#delete-info-msg').addClass('hide');
                $('#deleteBtn').show();
                $('#attention-info-msg').addClass('hide');
                if(selectedIndex == 0) {
                    $('.img-name').prop('disabled',true).removeClass('grid_10').addClass('grid_12');
                }
            } else {
                $('#delete-info-msg').removeClass('hide');
                $('#deleteBtn').hide();
                $('#attention-info-msg').removeClass('hide');
                $('.success-btn').hide();
            }
        }else{
            $('#check-all-label').addClass('hidden');
            $('#delete-info-msg').removeClass('hide');
            $('#deleteBtn').hide();
            $('#attention-info-msg').addClass('hide');
        }
    });

    function renameImg(fileName, oldName, extension) {
        var fileNewName = fileName.val(),
            fileOldName = oldName,
            fileExtension = extension,
            folderName = $('#things-select-folder').val();

        if(fileNewName.length > 0) {
            $.ajax({
                url: '<?php echo $this->websiteUrl;?>backend/backend_media/renamefile/',
                type: 'post',
                data: {'fileNewName': fileNewName, 'fileExtension': fileExtension, 'fileOldName': fileOldName, 'folderName': folderName, 'secureToken': $('.secureToken').val()},
                dataType: 'json',
                success: function(response) {
                    if(response.error == 1) {
                        $(fileName).val(fileOldName);
                    } else {
                        $(fileName).val(response.responseText.fileNewName).data('current-name', response.responseText.fileNewName);
                        $('.success-btn').hide();
                        $('#attention-info-msg').addClass('hide');
                        $('#delete-info-msg').addClass('hide');
                        showMessage('<?php echo $this->translate("Renamed");?>', false, 3000);
                    }
                }
            });
        }
    }

    $(document).on('click', '.edit-name', function(e){
        $('.img-name').removeClass('grid_9').addClass('grid_12');
        $('.file-container').removeClass('editing');
        if($('#filebrowser-image').find('input.toremove:checked').size() == 0) {
            e.preventDefault();
            $('.success-btn').hide();
            $(e.currentTarget).closest('.file-container').addClass('editing');
            $(e.currentTarget).closest('.img-edit-box').find('input').toggleClass('grid_12 grid_9').next().show();
            // $(e.currentTarget).toggleClass('grid_12 grid_9').next().show();
            $('#delete-info-msg').addClass('hide');
            $('#attention-info-msg').removeClass('hide');
        }
    });

    $(document).on('click', '.img-name', function (e) {
        $(e.currentTarget).prev().trigger('click');
    });

    $(document).on('blur', '.img-name', function (e) {
        e.preventDefault();
        var currentEl = $(e.currentTarget);
        if(currentEl.val() != currentEl.data('current-name')) {
            showConfirmCustom('<?php echo $this->translate("Do you want to rename the file?");?>', '<?php echo $this->translate("Rename");?>', '<?php echo $this->translate("Cancel changes");?>', function(){
                    renameImg(currentEl, currentEl.data('current-name'), currentEl.data('extension'));
                    $(currentEl).closest('.editing').removeClass('editing');
                    $(currentEl).toggleClass('grid_9 grid_12');

                },
                function(){
                    $('.success-btn').hide();
                    $('#delete-info-msg').addClass('hide');
                    $('#attention-info-msg').addClass('hide');
                    $(currentEl).closest('.editing').removeClass('editing');
                    $(currentEl).toggleClass('grid_12 grid_9');

                    currentEl.val(currentEl.data('current-name'));
            });
        }
    });

    $(document).on('click', '#deleteBtn', function(e) {
        e.preventDefault();
        var fileForm = $('#removeForm');
        var imagesBlock = $('#filebrowser-images');
        var filesBlock = $('#filebrowser-files');
        if ($('#things-select-folder').val() === '0') {
            showMessage('<?php echo $this->translate("No folder specified");?>', true, 5000);
            return false;
        }

        if (fileForm.find('input.toremove:checked').size() == 0) {
            showMessage('<?php echo $this->translate("Nothing to remove");?>', true, 5000);
            return false;
        }

        //images
        var images = imagesBlock.find('input.toremove:checked');
        var imagesArr = [];
        if(images.size() != 0){
            $(images).each(function(index, el) {
                var img = el.value;
                imagesArr.push(img);
            });
        }

        //files
        var files = filesBlock.find('input.toremove:checked');
        var filesArr = [];
        if(files.size() != 0){
            $(files).each(function(index, el) {
                var file = el.value;
                filesArr.push(file);
            });
        }

        $.ajax({
            url: '<?php echo $this->websiteUrl;?>/backend/backend_media/removefile/',
            type: 'post',
            data: {'folder': $('#things-select-folder').val(), 'removeImages': imagesArr, 'removeFiles': filesArr, 'secureToken': $('.secureToken').val()},
            dataType: 'json',
            beforeSend: function(){
                showSpinner()
            },
            complete: function(){
                hideSpinner()
            },
            success: function(response) {
                if (response.hasOwnProperty('deleted') && response.deleted.length > 0) {
                    var removedFiles = [];
                    for (var i in response.deleted) {
                        $('#filebrowser').queue(function(next){
                            $('.file-container:has(input.toremove:checked[value="'+response.deleted[i]+'"])').remove();
                            next();
                        });
                    }
                }
                if (response.hasOwnProperty('folderRemoved')) {
                    if (response.folderRemoved === true){
                        $('#check-all-label').addClass('hidden');
                        $('#things-select-folder').find('option:selected').remove().end().val('0');
                    }
                }
                if(response.errors.length > 0){
                    var errorsItems = response.errors;
                    var errorsHtml = '';
                    $.each(errorsItems, function(index, val) {
                        errorsHtml += '<strong>'+ val.name +'</strong> <?php echo $this->translate("is used on");?> <a href="<?php echo $this->websiteUrl;?>'+ val.errors[0] +'" target="_blank"><?php echo $this->websiteUrl;?>'+ val.errors[0] +'</a><br/>';
                    });
                    errorsHtml += ' <?php echo $this->translate("Please go remove or replace it with another image first so that your website stays pretty.");?>';
                    showMessage(errorsHtml, true, 5000);
                }

                $('.img-name').prop('disabled',false);
                $('#delete-info-msg').removeClass('hide');
                $('#deleteBtn').hide();
                $('#attention-info-msg').addClass('hide');
            }
        });
    });
</script>