<?php if (!empty($this->plugins)): ?>
    <?php foreach ($this->plugins as $plugin): ?>
        <div class="plugin-item">
            <p class="plugin-name text-right">
                <span class="grid_8 alpha omega text-left"><?php echo ucfirst($plugin->getName()); ?></span>
                <a class="readme-plugin icon16 ticon-info2" href="javascript:;"
                   data-name="<?php echo $plugin->getName(); ?>" id="<?php echo $plugin->getName(); ?>"></a>
                <a class="del-plugin _tdelete icon14 ticon-close"
                   data-url="<?php echo $this->toasterLink('backend_plugin', 'delete', '', null, true); ?>"
                   data-eid="<?php echo $plugin->getName(); ?>" data-callback="pluginCallback" href="javascript:;"></a>
            </p>

            <div class="plugin-image">
                <img src="<?php echo $plugin->getPreview(); ?>" alt="<?php echo $plugin->getName(); ?> preview"/>
            </div>
            <a class="plugin-control btn small <?php echo ($plugin->getId()) ? 'grid_6 alpha omega' : 'block'; ?>"
               id="<?php echo $plugin->getName(); ?>" href="javascript:;" data-name="<?php echo $plugin->getName(); ?>"
               data-operation="<?php echo ($plugin->getId()) ? 'uninstall' : 'install'; ?>"
               title="<?php echo ($plugin->getId()) ? $this->translate('Uninstall') : $this->translate(
                   'Install'
               ); ?>"><?php echo ($plugin->getId()) ? $this->translate('Uninstall') : $this->translate(
                    'Install'
                ); ?></a>
            <a class="plugin-endis btn small grid_6 alpha omega <?php echo(($plugin->getId()) ? (($plugin->getStatus(
                ) == Application_Model_Models_Plugin::ENABLED && $plugin->getId()) ? '' : 'disable') : 'hide'); ?>"
               id="endis-<?php echo $plugin->getName(); ?>" data-name="<?php echo $plugin->getName(); ?>"
               href="javascript:;"><?php echo ($plugin->getStatus(
                    ) == Application_Model_Models_Plugin::ENABLED && $plugin->getId()) ? $this->translate(
                    'Disable'
                ) : $this->translate('Enable'); ?></a>
        </div>
    <?php endforeach; ?>
<?php endif; ?>
