<div class="seotoaster container_12 h570 rounded3px">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Manage plugins')); ?>

	<div id="upload-plugin" class="grid_12">
		<fieldset>
			<div class="grid_5"><?php if(extension_loaded('zip')): ?>
				<?php
					$uploader = $this->toasterUploader(array(
						'id'            => 'plugin-uploader',
						'caller'        => 'plugin',
						'caption'       => $this->translate('Upload a new plugin'),
						'noMultiupload' => true));
					echo $uploader;
				?>
				<?php else: ?>

				<?php endif; ?>
			</div>
			<div class="grid_7">
				<div id="plugin-uploader-filelist"></div>
			</div>
		</fieldset>
	</div>
    <div class="grid_12">
        <fieldset class="h200">
            <legend><?php echo $this->translate('Available plugins'); ?></legend>
            <?php echo $this->toasterFrame('plugins-for-mojo.html', array(
                'height' => 180
            )); ?>
        </fieldset>
    </div>
    <div class="grid_12">
		<fieldset><legend><?php echo $this->translate('Installed plugins'); ?></legend>
	      <div id="plugins-list" class="h210"></div>
        </fieldset>
    </div>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/plugin.js'); ?>
