<?php if(isset($this->faeaturedAreas) && is_array($this->faeaturedAreas)): ?>
	<?php foreach($this->faeaturedAreas as $fa): ?>
		<div class="list-row">
			<div class="grid_6 list-row-item"><?php echo $fa->getName(); ?></div>
			<div class="grid_2 list-row-item pcount-<?php echo $fa->getId(); ?>"><?php echo sizeof($fa->getPages()); ?></div>
			<div class="grid_2 list-row-item"><input type="checkbox" name="addPageToFa" id="<?php echo $fa->getId(); ?>" class="add-page" <?php echo (in_array($fa->getId(), $this->currentFareasIds)) ? 'checked="checked"' : ''; ?>/></div>
			<div class="grid_2 list-row-item">
				<a style="float:left;" data-url="<?php echo $this->toasterLink('featured', 'delete', '', null, true); ?>" data-eid="<?php echo $fa->getId(); ?>" data-callback="loadFaList" class="del-fa _tdelete" href="javascript:;"><img src="<?php echo $this->websiteUrl; ?>system/images/delete.png" alt="delete"/></a>
			</div>
		</div>
	<?php endforeach; ?>
<?php endif; ?>