<div class="seotoaster container_12 rounded8px refreshOnClose">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Order featured area pages')); ?>
	<?php if(isset($this->faPages) && is_array($this->faPages) && !empty($this->faPages)): ?>
		<ul id="fa-pages-list">
			<?php foreach($this->faPages as $key => $page): ?>
			<li id="<?php echo $page->getId(); ?>" style="cursor: pointer;">
					<div class="grid_1"><?php echo ++$key; ?></div>
					<div class="grid_11"><?php echo $page->getNavName(); ?></div>
				</li>
			<?php endforeach; ?>
		</ul>
	<?php endif; ?>
</div>
<script type="text/javascript" charset="utf-8">
	$(function() {
		$('#fa-pages-list').sortable({
			helper  : 'clone',
			stop    : function() {
				var ordered = [];
				var number  = 0;
				var els     = $('#fa-pages-list').find('li');
				$.each(els, function() {
					ordered.push($(this).attr('id'));
					$(this).find('div:first').text(++number);
				});
				$('#ajax_msg').text('Saving order...').show();
				$.post($('#website_url').val() + 'backend/backend_featured/order/', {
					ordered : ordered,
					id      : <?php echo $this->faId; ?>
				}, function() {
					$('#ajax_msg').text('Saved').fadeOut();
				});
			}
		});
	});
</script>