<?php $this->jQuery()->onLoadCaptureStart(); ?>
	$('#editcssform').submit(function(){
		$.ajax({
			url: $(this).attr('action'),
			type: $(this).attr('method'),
			data: $(this).serialize(),
			dataType: 'json',
			success: function(response){
				$('#ajax_msg').text(response.responseText).delay(3000).fadeOut();
			},
			beforeSend: function(){
				$('#ajax_msg').text('<?php echo $this->translate('saving css content...'); ?>').fadeIn();
			},
			error: function(){
				$('#ajax_msg').text('<?php echo $this->translate('Error occured.'); ?>').fadeIn();
			}
		})
		return false;
	});

	$('#csslist').bind('change',function(){
		$.ajax({
			url: '<?php echo $this->websiteUrl . $this->url(); ?>',
			type: 'POST',
			data: {"getcss": $(this).val()},
			dataType: 'json',
			success: function(response){
				if (response.error == false){
					$('#ajax_msg').fadeOut();
					$('#csscontent').val(response.responseText).focus();
				}
			},
			beforeSend: function(){
				$('#ajax_msg').text('<?php echo $this->translate('Loading css content...'); ?>').fadeIn();
			},
			error: function(){
				$('#ajax_msg').text('<?php echo $this->translate('Error occured.'); ?>').show();
			}
		});
	});
	$('#csscontent').keydown(function(e) {
		if(e.ctrlKey && e.keyCode == 83) {
			e.preventDefault();
			$('#editcssform').submit();
		}
	})
<?php $this->jQuery()->onLoadCaptureEnd(); ?>
<div class="seotoaster editor container_12 w960 rounded8px">
	<?php echo $this->partial('admin'.DIRECTORY_SEPARATOR.'_header.phtml', array('headerText' => 'Edit css')); ?>

	<?php
		$this->editcssForm->setAction($this->websiteUrl.$this->url());
	?>
	<form action="<?php echo $this->editcssForm->getAction(); ?>" id="<?php echo $this->editcssForm->getId(); ?>" method="<?php echo $this->editcssForm->getMethod(); ?>">
		<div class="grid_8">&nbsp;</div>
		<div class="grid_4"><?php echo $this->editcssForm->getElement('cssname')->removeDecorator('DtDdWrapper'); ?></div>
		<div class="grid_12"><?php echo $this->editcssForm->getElement('content'); ?></div>
		<div class="grid_12"><?php echo $this->editcssForm->getElement('submit'); ?></div>
	</form>

</div>
