<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/theme.js'); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/aceajax/ace.js' ); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/aceajax/theme-crimson_editor.js'); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/aceajax/mode-html.js'); ?>
<div class="seotoaster container_12 h590 rounded3px refreshOnClose">
	<?php echo $this->partial('admin'.DIRECTORY_SEPARATOR.'_header.phtml', array('headerText' => $this->templateForm->getElement('id')->getValue() == ''?'Add template':'Edit template')); ?>

	<div id="templatelist" class="h640 ui-helper-hidden" style="z-index: 99; overflow: hidden; width: 100%; margin-top: -42px;"></div>
	<?php $this->templateForm->setAction($this->url()); ?>
	<form action="<?php echo $this->templateForm->getAction(); ?>" id="<?php echo $this->templateForm->getId();?>" method="<?php echo $this->templateForm->getMethod();?>">
		<div class="grid_9">
			<div class="grid_6">
				<?php echo $this->templateForm->getElement('name'); ?>
			</div>
			<div class="grid_6">
				<?php echo $this->templateForm->getElement('templateType'); ?>
			</div>
			<div class="grid_12"><?php echo $this->templateForm->getElement('content')->renderLabel(); ?></div>
			<div class="h450" id="edittemplate">
				<?php echo $this->templateForm->getElement('content')->renderViewHelper(); ?>
			</div>
		</div>
		<?php if ($this->templateForm->getElement('id')->getValue() != ''): ?>
			<input type="button" class="grid_3" id="listtemplates-btn" value="<?php echo $this->translate('Other templates');?>" />
		<?php endif; ?>
		<div class="grid_3 h450">
			<div class="mt20px mb20px textcentered img-teaser">
				<img id="template_preview" src="<?php echo $this->websiteUrl . (($this->templatePreview) ? $this->templatePreview : 'system/images/no_preview.png'); ?>" alt="<?php echo $this->translate('Template preview'); ?>" />
			</div>
			<div style="text-align: center">
				<div id="template-preview-uploader-filelist" class="ui-helper-hidden"></div>
				<?php
								$previewUploader = $this->toasterUploader(
									array(
										'id'      => 'template-preview-uploader',
										'caller'  => 'templatePreview',
										'caption' => $this->translate('Upload image')
									)
								);
								echo $previewUploader;
							?>
			</div>
		</div>
		<?php echo $this->templateForm->getElement('id')->setDecorators(array('ViewHelper')); ?>
<!--		<div class="grid_3 textcentered  mt15px">-->
			<?php echo $this->templateForm->getElement('submit'); ?>
<!--		</div>-->
		<?php echo $this->templateForm->getElement('pageId'); ?>
	</form>
</div>
