<?php foreach ($this->templates as $template) : ?>
<div class="grid_2 template_item" title="<?php echo sprintf($this->translate('Click to edit %s template'), $template['name']); ?>">
	<div class="template_preview">
		<div style="height:220px;">
			<img src="<?php echo $this->websiteUrl.$template['preview_image']; ?>" alt="<?php echo $template['name']; ?>" style="z-index:1;width:125px;"/>
		</div>
		<div class="template_name">
			<?php echo $template['name']; ?>
			<?php if (!in_array($template['name'], $this->protectedTemplates)): ?>
			<div class="template_delete"><img style="vertical-align:middle;" src="<?php echo $this->websiteUrl;?>/system/images/delete.png" alt="<?php echo $this->translate('Delete');?>" /></div>
			<?php endif; ?>
		</div>
		<?php echo $this->formHidden('template-id', $template['name'], array('id' => 'template-id-'.$template['name'])); ?>
	</div>
</div>
<?php endforeach; ?>