<div class="header">
	<div class="closebutton">
		<a class="hide-block ticon-chevron-right" href="javascript:;" title="<?php echo $this->translate('Close'); ?>"></a>
	</div>
    <select id="template-categories" class="grid_9 alpha mt5px">
        <?php foreach ($this->types as $type => $caption ) : ?>
        <?php
            $templates = array_filter($this->templates, function($tmpl)use($type){ return $tmpl['type'] === $type; });
            if (empty($templates)) continue;
        ?>
        <option value="<?php echo $type; ?>"><?php echo $caption; ?></option>
        <?php endforeach; ?>
    </select>
</div>
<div class="content scroll">
<?php foreach ($this->types as $type => $caption ) : ?>
<?php
	$templates = array_filter($this->templates, function($tmpl)use($type){ return $tmpl['type'] === $type; });
	if (empty($templates)) continue;
?>
	<div id="<?php echo $type; ?>" class="template_group grid_12 <?php echo $type !== 'typeregular' ? 'hide' : ''; ?>">
		<?php foreach ($templates as $template) : ?>
		<div class="template_item <?php echo ((isset($template['isCurrent']) && $template['isCurrent']) ? 'curr-template' : ''); ?>" title="<?php echo sprintf($this->translate('%s template'), $template['fullName']); ?>">
			<?php if (!in_array($template['name'], $this->protectedTemplates)): ?>
				<span class="template_delete ticon-remove icon16" title="<?php echo $this->translate('Delete');?>" />
			<?php endif; ?>
            <?php if (isset($template['isCurrent']) && $template['isCurrent']): ?>
                <span class="template-check ticon-check icon16"/></span>
            <?php endif; ?>
			<div class="template_name" <?php echo  ((int) $template['pagesCount'] >= 1) ? 'title="' . sprintf($this->translate('%s template'), $template['fullName']) . ' - ' . $this->translate('used %s times', $template['pagesCount']) . '"' : ''?>>
				<?php echo ucfirst($template['name']); ?>
			</div>
			<?php echo $this->formHidden('template-id', $template['name'], array('id' => 'template-id-'.$template['name'])); ?>
		</div>
		<?php endforeach; ?>
	</div>
<?php endforeach; ?>
</div>