<div class="seotoaster container_12 h570 rounded3px">
	<?php echo $this->partial('admin'.DIRECTORY_SEPARATOR.'_header.phtml', array('headerText' => 'Manage themes', 'helpSection' => $this->helpSection)); ?>

	<div  class="grid_12 mb10px">
		<fieldset>
		<div class="grid_5"><?php echo $this->toasterUploader(array(
						'id'=>'themes-uploader',
						'filters' => array('zip'),
						'caption' => $this->translate('Upload a new theme'),
						'caller' => 'themes'
						)); ?></div>
		<div class="grid_7">
			<div id="themes-uploader-filelist"></div>
		</div>
		</fieldset>
	</div>
	<div class="grid_12">
		<fieldset><legend>Themes list</legend>
			<div id="themes-list" class="h380">
			<?php foreach ($this->themesList as $theme) :?>
				<div class="themebox" style="position: relative;">
					<span class="label" style="position:relative"><?php echo $theme['name']; ?><div class="cat-tools">
						<?php if ($theme['isCurrent']): ?>
						<a href="javascript:;" title="this is the current theme"><img src="<?php echo $this->websiteUrl;?>system/images/current-theme.png"></a>
						<?php else : ?>
						<a href="javascript:;" class="theme-delete" title="<?php echo $this->translate('trash this theme');?>"><img src="<?php echo $this->websiteUrl;?>system/images/delete.png"></a>
						<?php endif; ?>
						</div>
					</span>
					<img src="<?php echo $theme['preview'];  ?>" class="preview" alt="<?php echo $theme['name']; ?>" />
					<label>
						<?php if ($theme['isCurrent']): ?>
							<span style="display: block; padding: 0px 5px;"><?php echo $this->translate('Current theme'); ?></span>
						<?php else: ?>
							<input type="radio" name="select-theme" value="<?php echo $theme['name']; ?>"/>&nbsp;<?php echo $this->translate('Select theme'); ?>
						<?php endif; ?>
					</label>
					<input type="hidden" class="theme-name" value="<?php echo $theme['name']; ?>"/>
					<a class="lnk-download" style="position: absolute; left: 149px; top: 170px;" href="javascript:;" title="<?php echo ($this->translate('Download') . ' ' . $theme['name'] . ' ' . $this->translate('theme')); ?>"><img src="<?php echo $this->websiteUrl;?>system/images/download.png" /></a>
				</div>
			<?php endforeach; ?>
			</div>
		</fieldset>
	</div>
	<div class="grid_12">
		<?php echo $this->formSubmit('done', $this->translate('Done')); ?>
	</div>
	<div class="clear"></div>
</div>

<script type="text/javascript">
$(function(){
	$('#themes-list').bind('updateContent', function(){
		$(this).load('<?php echo $this->websiteUrl;?>backend/backend_theme/themes/ .themebox');
	});

	$('#themes-list').delegate('.theme-delete', 'click', function(){
		var themeName = $(this).closest('div.themebox').find('input.theme-name').val();
		showConfirm('You are about to remove theme. Are you sure?', function() {
			$.ajax({
		        url: '<?php echo $this->url(array('action'=>'deletetheme')); ?>',
		        type: 'post',
			    beforeSend: function() {showSpinner();},
			    data: {name: themeName},
		        success: function(response) {
			        hideSpinner();
			        $('#themes-list').trigger('updateContent');
		        },
		        dataType: 'json'
		    });
		});
		return false;
	});

	$('#done').bind('click', function(){
		if ($('input[name="select-theme"]:checked').size()){
			var themeName = $('input[name="select-theme"]:checked').val();
			$.post('<?php echo $this->url(array('action'=>'applytheme')); ?>',
			{'themename' : themeName},
			function(response){
				if (response.error == false) {
					smoke.signal(response.responseText);
					$('.smoke-base').fadeOut();
				}
				$('#themes-list').trigger('updateContent');
			},
			'json'
			);
		}
	});

	$('.lnk-download').live('click', function() {
		var themeName = $(this).prev().val();
		var url       = '<?php echo $this->websiteUrl;?>backend/backend_theme/downloadtheme/name/' + themeName;
		document.location.href = url;
	})
});
</script>
