<?php echo $this->doctype(); ?>
<!--[if IE 7 ]><html class="ie ie7" lang="<?php echo $this->htmlLang; ?>"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="<?php echo $this->htmlLang; ?>"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="<?php echo $this->htmlLang; ?>"> <![endif]-->
<!--[if !(IE)]><!-->
<?php
    $device = Zend_Controller_Action_HelperBroker::getStaticHelper('mobile');
    $deviceType = $device->isTablet() ? "tablet" : "mobile";
    $deviceType = $device->isMobile() ? $deviceType : "desktop";
?>
<html class="<?php echo $deviceType; ?>" lang="<?php echo $this->htmlLang; ?>">
<!--<![endif]-->
<head>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headMeta()->setIndent(8); ?>
    <?php

    $excludeSystemCss = false;

    if($this->minifyCss && $this->excludeSystemCss) {
        $excludeSystemCss = true;
    }

    // link and script block start
    // adding canonical link
    if ($this->tplType !== 'typemail') {
        if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PAGE_PROTECTED)) {
            if (empty($this->bodyTag) && !$excludeSystemCss) {
                $this->headLink()
                    ->prependStylesheet($this->websiteUrl.'system/css/seotoaster.css');
            }
        }

        if(!$excludeSystemCss) {
            $this->headLink()->setIndent(8)
                ->prependStylesheet($this->websiteUrl.'system/css/seotoaster-ui.css')
                ->prependStylesheet($this->websiteUrl.'system/css/reset.css');

            if (!empty($this->bodyTag)) {
                $this->headLink()
                    ->appendStylesheet($this->websiteUrl.'system/js/external/magnific-popup/magnific-popup.css');
            }
        }
    }
    if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PAGE_PROTECTED)) {
        if (!empty($this->bodyTag) && !$excludeSystemCss) {
            $this->headLink()
                ->prependStylesheet($this->websiteUrl.'system/css/seotoaster-reset.css');
        }
    }
    $this->headLink()->headLink(array('rel' => 'canonical', 'href' => $this->canonicalUrl), 'PREPEND');


    if(isset($this->minifyCss) && $this->minifyCss === true) {
        echo Tools_System_Minify::minify($this->headLink(), true, Tools_System_Minify::MINIFY_CSS);
    } else {
        echo $this->headLink();
    }

    $this->jQuery()->uiEnable();

    if($device->isTablet() || $device->isMobile()){
        $this->headScript()
             ->prependFile($this->websiteUrl.'system/js/external/hammer/hammer.min.js')
             ->prependFile($this->websiteUrl.'system/js/external/jquery/plugins/touchpunch/jquery.ui.touch-punch.min.js');
    }

    echo $this->jQuery();

    if (!empty($this->bodyTag)) {
        $this->inlineScript()->setIndent(8)->setAllowArbitraryAttributes(true)
            ->prependFile($this->websiteUrl.'system/js/external/smoke/smoke.min.js')
            ->prependFile($this->websiteUrl.'system/js/internal/system.min.js')
            ->prependFile($this->websiteUrl.'system/js/external/magnific-popup/jquery.magnific-popup.min.js')
            ->prependFile($this->websiteUrl.'system/js/external/jquery/plugins/mousewheel/jquery.mousewheel.min.js')
            ->prependFile($this->websiteUrl.'system/js/external/jquery/plugins/cookie/jquery.cookie.js')
            ->prependFile($this->websiteUrl.'system/js/external/jquery/plugins/maskedinput/jquery.maskedinput.min.js');
    }else{
        $this->headScript()->setIndent(8)->setAllowArbitraryAttributes(true)
            ->prependFile($this->websiteUrl.'system/js/external/smoke/smoke.min.js')
            ->prependFile($this->websiteUrl.'system/js/internal/system.min.js')
            ->prependFile($this->websiteUrl.'system/js/external/jquery/plugins/mousewheel/jquery.mousewheel.min.js')
            ->prependFile($this->websiteUrl.'system/js/external/jquery/plugins/cookie/jquery.cookie.js')
            ->prependFile($this->websiteUrl.'system/js/external/jquery/plugins/maskedinput/jquery.maskedinput.min.js');
    }

    if(isset($this->minifyJs) && $this->minifyJs === true) {
        echo Tools_System_Minify::minify($this->headScript(), true, Tools_System_Minify::MINIFY_JS);
    } else {
        echo $this->headScript();
    }

    echo $this->headStyle();
    // link and script block end

    echo $this->placeholder('misc');
    echo isset($this->placeholder('seo')->seoHead) ? $this->placeholder('seo')->seoHead: '';
    ?>
</head>
<?php echo !empty($this->bodyTag) ? $this->bodyTag : '<body>'; ?>
<?php echo isset($this->placeholder('seo')->seoTop) ? $this->placeholder('seo')->seoTop: ''; ?>
<?php echo $this->layout()->content; ?>
<?php echo isset($this->placeholder('seo')->seoBottom) ? $this->placeholder('seo')->seoBottom: ''; ?>
<input type="hidden" id="website_url" value="<?php echo $this->websiteUrl; ?>" />
<input type="hidden" id="current_theme" value="<?php echo $this->currentTheme; ?>" />
<input type="hidden" id="page_id" value="<?php echo $this->pageData['id']; ?>">
<?php if(isset($this->sculptingReplacement)): ?>
    <!-- PRSCULPTING -->
    <script type="text/javascript" charset="utf-8">$(function() {var sculptingReplacement = <?php echo $this->sculptingReplacement; ?>;$.each(sculptingReplacement, function() {$('span.' + this.id).replaceWith(this.repl);})});</script>
    <!-- /PRSCULPTING -->
<?php endif; ?>
<?php
/**
 * Plugins additional content
 */
    echo $this->placeholder('plugins');

    if((isset($this->minifyCss) && $this->minifyCss === true) ||  (isset($this->minifyJs) && $this->minifyJs === true)) {
        if (isset($this->minifyCss) && $this->minifyCss === true) {
            $minifiedCssList = Tools_System_Minify::minify($this->inlineScript(), true, Tools_System_Minify::MINIFY_CSS);
        }

        if (isset($this->minifyJs) && $this->minifyJs === true) {
            if (isset($minifiedCssList)) {
                echo Tools_System_Minify::minify($minifiedCssList, true, Tools_System_Minify::MINIFY_JS);
            } else {
                echo Tools_System_Minify::minify($this->inlineScript(), true, Tools_System_Minify::MINIFY_JS);
            }
        } else {
            echo $minifiedCssList;
        }
    } else {
        echo $this->inlineScript();
    }
?>
<?php $websiteConfig = Zend_Controller_Action_HelperBroker::getExistingHelper('config')->getConfig();
$grecaptchaPublicKey = $websiteConfig[Tools_System_Tools::GRECAPTCHA_PUBLIC_KEY];
?>
<?php if (!empty($grecaptchaPublicKey)): ?>
    <script src="https://www.google.com/recaptcha/api.js?onload=CaptchaCallback&render=explicit" async defer></script>
    <script>
        var CaptchaCallback = function () {
            var captchas = document.getElementsByClassName("g-recaptcha");
            for (var i = 0; i < captchas.length; i++) {
                grecaptcha.render(captchas[i], {'sitekey': '<?php echo $grecaptchaPublicKey;?>'});
            }
        };
    </script>
<?php endif; ?>
</body>
</html>
