<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<!-- added by Seotoaster layout -->
		<?php if(!preg_match('/<meta charset="utf-8">/is', $this->head)): ?>
			<?php echo $this->headMeta()->setCharset('utf-8'); ?>
		<?php endif; ?>

		<?php if(!preg_match('~<link rel="canonical" href=".*"[\s/]*>~is', $this->head)): ?>
			<link rel="canonical" href="<?php echo $this->websiteUrl . (($this->pageData['url'] != $this->websiteMainPage) ? $this->pageData['url'] : ''); ?>" />
		<?php endif; ?>

		<?php $this->jQuery()->enable(); ?>
		<?php $this->jQuery()->uiEnable(); ?>

		<?php $this->headLink()->prependStylesheet($this->websiteUrl . 'system/js/external/fancybox/jquery.fancybox.css'); ?>
		<?php $this->headLink()->prependStylesheet($this->websiteUrl . 'system/js/external/smoke/smoke.css'); ?>

		<?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PAGE_PROTECTED) || Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PAGE_PROTECTED, $this->roleId)): ?>
		<?php $this->headLink()->prependStylesheet($this->websiteUrl . 'system/css/seotoaster.css'); ?>
		<?php $this->headLink()->prependStylesheet($this->websiteUrl . 'system/css/grid.css'); ?>
		<?php $this->headLink()->prependStylesheet($this->websiteUrl . 'system/css/reset.css'); ?>
		<?php $this->headLink()->prependStylesheet($this->websiteUrl . 'system/uithemes/seotoasterui/seotoasterui.css'); ?>
			<?php if((bool)Zend_Controller_Action_HelperBroker::getExistingHelper('config')->getConfig('inlineEditor')):?>
			<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/js/external/redactor/css/redactor.css'); ?>
			<?php endif; ?>
		<?php endif; ?>

		<?php echo $this->headLink(); ?>

		<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/fancybox/jquery.fancybox.js'); ?>
		<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/jquery/plugins/mousewheel/jquery.mousewheel.min.js'); ?>
		<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/jquery/plugins/cookie/jquery.cookie.js'); ?>
		<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/smoke/smoke.min.js'); ?>

		<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/system.js'); ?>

		<?php
		if( (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PAGE_PROTECTED) || Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PAGE_PROTECTED, $this->roleId))
			&& (bool)Zend_Controller_Action_HelperBroker::getExistingHelper('config')->getConfig('inlineEditor')
		  ){
			$this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/redactor/redactor.min.js');
		}
		?>

		<?php echo $this->jQuery(); ?>

		<!-- end of Seotoaster layout -->
		<!-- from theme -->
		<?php echo $this->head; ?>
		<!-- end from theme -->
	</head>
	<?php echo !empty($this->bodyTag) ? $this->bodyTag : '<body>'; ?>
		<?php echo $this->layout()->content; ?>
		<input type="hidden" id="website_url" value="<?php echo $this->websiteUrl; ?>" />
		<input type="hidden" id="current_theme" value="<?php echo $this->currentTheme; ?>" />
		<?php if(isset($this->sculptingReplacement)): ?>
			<!-- PRSCULPTING -->
			<script type="text/javascript" charset="utf-8">$(function() {var sculptingReplacement = <?php echo $this->sculptingReplacement; ?>;$.each(sculptingReplacement, function() {$('span.' + this.id).replaceWith(this.repl);})});</script>
			<!-- /PRSCULPTING -->
		<?php endif; ?>
	</body>
</html>

