<html>
	<body>
		<style>

		</style>
		<h3><?php echo $this->translate('New message was posted on the website.'); ?></h3>
		<?php if(is_array($this->params) && !empty ($this->params)): ?>
			<dl>
				<?php foreach($this->params as $name => $param): ?>
					<?php if(!in_array($name, $this->badParams)): ?>
						<dt><?php echo $name; ?></dt>
						<dd><?php echo $param; ?></dd>
					<?php endif;?>
				<?php endforeach; ?>
			</dl>
		<?php endif; ?>
	</body>
</html>