<div class="seotoaster container_12 w450 h590 rounded3px">
    <?php echo $this->partial('admin'.DIRECTORY_SEPARATOR.'_header.phtml', array('headerText' => 'Form properties')); ?>
    <form class="_fajax _reload" data-norefresh="1" id="formWidget" action="<?php echo $this->websiteUrl?>backend/backend_form/manageform/" method="post">
			<div class="grid_6">
				<?php echo $this->formForm->getElement('code')->renderLabel(); ?>
				<?php echo $this->formForm->getElement('code')->renderViewHelper(); ?>
			</div>
			<div class="grid_6">
				<?php echo $this->formForm->getElement('trackingCode')->renderLabel(); ?>
				<?php echo $this->formForm->getElement('trackingCode')->renderViewHelper(); ?>
			</div>
            <div class="grid_12 alpha">
                <?php if(isset($this->trackingPageUrl)):?>
                    <a style="font-size: 11px; float:right;" target="_blank" href="<?php echo $this->websiteUrl.$this->trackingPageUrl;?>"><?php echo $this->websiteUrl.$this->trackingPageUrl;?></a>
                <?php else:?>
                    <div class="grid_5">
                        <span style="font-size: 11px; float:right; color:#cd5c5c; margin-top: 10px;">[<?php echo $this->translate('Create a success page');?>]</span>
                    </div>
                    <div class="grid_7">
                        <select name="thankyouTemplate">
                            <option value="select"><?php echo $this->translate('select template');?></option>
                            <?php foreach($this->regularTemplates as $regularTemplate):?>
                                <option value="<?php echo $regularTemplate->getName();?>"><?php echo $regularTemplate->getName();?></option>
                            <?php endforeach;?>
                        </select>
                    </div>    
                <?php endif;?>
            </div>
			<div class="grid_12"><?php echo $this->formForm->getElement('contactEmail')->renderLabel(); ?></div>
			<div class="grid_12"><?php echo $this->formForm->getElement('contactEmail')->renderViewHelper(); ?></div>
            <div class="grid_12"><?php echo $this->formForm->getElement('replyFromName')->renderLabel(); ?></div>
			<div class="grid_12"><?php echo $this->formForm->getElement('replyFromName')->renderViewHelper(); ?></div>
			<div class="grid_12"><?php echo $this->formForm->getElement('replyFrom')->renderLabel(); ?></div>
			<div class="grid_12"><?php echo $this->formForm->getElement('replyFrom')->renderViewHelper(); ?></div>
			<div class="grid_6">
                <?php echo $this->formForm->getElement('replySubject')->renderLabel(); ?>
			    <?php echo $this->formForm->getElement('replySubject')->renderViewHelper(); ?>
            </div>
			<div class="grid_6" style="position: relative;">
                <?php echo $this->formForm->getElement('replyMailTemplate')->renderLabel(); ?>
			    <?php echo $this->formForm->getElement('replyMailTemplate')->renderViewHelper(); ?>
            </div>
            <div class="grid_12"><?php echo $this->formForm->getElement('replyText')->renderLabel(); ?></div>
            <div class="grid_12"><?php echo $this->formForm->getElement('replyText')->renderViewHelper(); ?></div>
			<div class="grid_6">
                <?php echo $this->formForm->getElement('messageSuccess')->renderLabel(); ?>
			    <?php echo $this->formForm->getElement('messageSuccess')->renderViewHelper(); ?>
            </div>
			<div class="grid_6">
                <?php echo $this->formForm->getElement('messageError')->renderLabel(); ?>
			    <?php echo $this->formForm->getElement('messageError')->renderViewHelper(); ?>
            </div>
            <input type="hidden" name="pageId" value="<?php echo $this->pageId;?>" />
		<div class="grid_12 mt5px"><?php echo $this->formForm->getElement('submit')->renderViewHelper();?></div>
		<?php echo $this->formForm->getElement('name')->renderViewHelper(); ?>
		<?php echo $this->formForm->getElement('id')->renderViewHelper(); ?>
     </form>
</div>

<style>
    #tracking-code{
        height: 70px;
    }
    #code{
        height: 70px;
    }
    #reply-text{
        height: 35px;
    }
</style>