<header class="grid_12">
	<img class="logo" src="assets/logo.jpg" width="215" height="275" alt="Seotoaster install">
	<form action="" method="post" id="language" class="grid_7">
		<?php foreach($this->langs as $locale => $flag): ?>
		<input type="radio" name="lang" value="<?php echo $locale;?>" id="lang-<?php echo $locale;?>"
			   <?php echo $this->translate()->getLocale() === $locale ? 'checked="checked"' : '' ; ?>
			   />
		<label for="lang-<?php echo $locale;?>">
			<img src="../<?php echo $flag;?>" alt="<?php echo Zend_Locale::getTranslation($locale, 'language');?>" />
		</label>
		<?php endforeach; ?>
	</form>
	<script>
		$('#language').delegate('input[type="radio"]','change', function(){
			$(this).closest('form').submit();
		}).buttonset();
	</script>
	<h1 class="grid_7"><?php echo $this->translate('Seotoaster install');?></h1>
	<h2 class="step grid_7"><?php echo $this->translate('Step 1: System setup');?></h2>
</header>
<!-- STEP 1 -->
<div id="step-content">
	<div id="left" class="grid_6 alpha omega" style="border-right:2px dashed #ccc;">
		<h3 class="title-step"><?php echo $this->translate("Checking Server Requirements"); ?></h3>
		<span class="description-step"><?php echo $this->translate('Your server needs to meet the minimum requirements configuration in order to run the toaster.');?></span>
		<ul>
			<li><strong>Web server:</strong> Apache2, Light-Httpd, Nginx. Any web server that can do re-writes and support php should work too (not tested).</li>
			<?php if (false !== strpos(strtolower($_SERVER["SERVER_SOFTWARE"]), 'apache')) :?>
			<li <?php if(!in_array('mod_rewrite', apache_get_modules())) echo 'class="error"'; ?>><strong>mod_rewrite module:</strong> For Apache 2 only</li>
			<?php endif; ?>
			<li <?php if (!$this->checks['php']) echo 'class="error"'; ?>><strong>PHP 5.3.3</strong> or higher</li>
			<li <?php if (!$this->checks['pdo']) echo 'class="error"'; ?>><strong>PDO extension</strong> for PHP</li>
			<li <?php if (!$this->checks['mbstring']) echo 'class="error"'; ?>><strong>MBString:</strong> Works with any language</li>
			<li <?php if (!$this->checks['gd']) echo 'class="error"'; ?>><strong>GD Libaries 2.0</strong> or newer: Works with images</li>
			<li <?php if (!$this->checks['zip']) echo 'class="error"'; ?>><strong>Zip extension for PHP:</strong> Permit themes management through the interface</li>
			<li <?php if (!$this->checks['curl']) echo 'class="error"'; ?>><strong>Curl extension for PHP:</strong> 3rd party services connection: Google, Yahoo, PayPal, etc.</li>
			<?php if (get_magic_quotes_gpc()) : ?>
			<li class="important"><strong style="color:#CE553F;">Important!</strong> Make sure you <strong>turn OFF Magic quotes,</strong> either with the htacces that comes with the packege or in your PHP.ini (Otherwise you will get a bunch of'\' in the templates when loading themes).</li>
			<?php endif;?>
		</ul>
	</div>

	<div id="right" class="grid_6 alpha omega">
		<h3 class="title-step"><?php echo $this->translate('Checking file system permissions');?></h3>
		<span class="description-step"><?php echo $this->translate('Some folders need to be writable to allow the toaster to function properly.');?></span>
		<ul>
			<?php foreach ($this->permissions['dir'] as $dirname => $status): ?>
				<li class="<?php if ($status !== 'writable' ) echo "error red";  ?>">
					<?php echo $this->translate("Folder %1\$s is %2\$s ", $dirname,  $status); ?>
				</li>
			<?php endforeach; ?>
			<?php foreach ($this->permissions['file'] as $filename => $status): ?>
				<li class="<?php if ($status !== 'writable' ) echo "error red";  ?>">
                    <?php echo $this->translate("File %1\$s is %2\$s", $filename, $status); ?>
				</li>
			<?php endforeach; ?>
		</ul>
		<?php if ($this->gotoNext === true): ?>
		<div class="bravo green"><?php echo $this->translate('Bravo, All good to go!');?></div>
		<?php endif; ?>
		<form method="post" action="" id="gotonext">
			<?php if ($this->gotoNext === true): ?>
			<input type="submit" value="<?php echo $this->translate('Next');?>" name="submit" />
			<?php else: ?>
			<input type="submit" value="<?php echo $this->translate('Check again');?>" name="check" />
			<?php endif; ?>
		</form>
	</div>
</div>