<header class="grid_12">
	<img class="logo" src="assets/logo.jpg" width="215" height="275" alt="Seotoaster install">
	<form action="" method="post" id="language" class="grid_7">
		<?php foreach($this->langs as $locale => $flag): ?>
		<input type="radio" name="lang" value="<?php echo $locale;?>" id="lang-<?php echo $locale;?>"
			   <?php echo $this->translate()->getLocale() === $locale ? 'checked="checked"' : '' ; ?>
			   />
		<label for="lang-<?php echo $locale;?>">
			<img src="../<?php echo $flag;?>" alt="<?php echo Zend_Locale::getTranslation($locale, 'language');?>" />
		</label>
		<?php endforeach; ?>
	</form>
	<script>
		$('#language').delegate('input[type="radio"]','change', function(){
			$(this).closest('form').submit();
		}).buttonset();
	</script>
	<h1 class="grid_7"><?php echo $this->translate('Seotoaster install');?></h1>
	<h2 class="step grid_7"><?php echo $this->translate('Step 1: System setup');?></h2>
</header>
<!-- STEP 1 -->
<div id="step-content">
	<div id="left" class="grid_6 alpha omega" style="border-right:2px dashed #ccc;">
		<h3 class="title-step"><?php echo $this->translate("Checking Server Requirements"); ?></h3>
		<span class="description-step"><?php echo $this->translate('Your server needs to meet the minimum requirements configuration in order to run the toaster.');?></span>
		<ul>
			<li><strong><?php echo $this->translate('Web server');?>:</strong>&nbsp;<?php echo $this->translate('Apache2, Nginx. Any web server that can do re-writes and support php should work too (not tested).');?></li>
			<?php if (false !== strpos(strtolower($_SERVER["SERVER_SOFTWARE"]), 'apache')) :?>
			<li <?php if (function_exists('apache_get_modules')){ if (!in_array('mod_rewrite', apache_get_modules())) echo 'class="error important"';  } ?>><strong>mod_rewrite <?php echo $this->translate('module');?>:</strong>&nbsp;<?php echo $this->translate('For Apache 2 only');?></li>
			<?php endif; ?>
			<li <?php if (!$this->checks['php']) echo 'class="error"'; ?> ><?php echo $this->translate('<strong>PHP 5.3.3</strong> or higher'); ?></li>
			<li <?php if (!$this->checks['pdo']) echo 'class="error"'; ?> ><?php echo $this->translate('<strong>PDO</strong> extension for PHP'); ?></li>
			<li <?php if (!$this->checks['mbstring']) echo 'class="error"'; ?> ><?php echo $this->translate('<strong>MBString:</strong> Works with any language');?></li>
			<li <?php if (!$this->checks['gd']) echo 'class="error"'; ?> ><?php echo $this->translate('<strong>GD Libaries 2.0</strong> or newer: Works with images');?></li>
			<li <?php if (!$this->checks['zip']) echo 'class="error"'; ?> ><?php echo $this->translate('<strong>Zip extension for PHP:</strong> Permit themes management through the interface'); ?></li>
			<li <?php if (!$this->checks['curl']) echo 'class="error"'; ?> ><?php echo $this->translate('<strong>Curl extension for PHP:</strong> 3rd party services connection: Google, Yahoo, PayPal, etc.'); ?></li>
            <li <?php if (isset($this->checks['json']) && !$this->checks['json']) echo 'class="error"'; ?> ><?php echo $this->translate('<strong>JSON extension for PHP:</strong> JSON (JavaScript Object Notation) support. JSON is a lightweight data-interchange format.'); ?></li>
			<?php if ($this->checks['magicquotes'] !== true) : ?>
			<li class="error important"><?php echo $this->translate("<strong>Important!</strong> Make sure you <strong>turn OFF Magic quotes,</strong> either with the htacces that comes with the package or in your PHP.ini (Otherwise you will get a bunch of'\' in the templates when loading themes)."); ?></li>
			<?php endif;?>
			<?php if(!extension_loaded('IonCube Loader')): ?>
			<li class="important error">
                <?php echo $this->translate('<strong>Optional but recommended:</strong>');?>&nbsp;<strong>IonCube Loader</strong>
				<p style="text-align:justify;">
                <?php echo $this->translate("We've detected that your web server is not equipped with the Ion Cube encryption loader. Don't settle for less than the entire Seotoaster experience! Seotoaster uses IonCube to encrypt great time-saving plug-ins available on the marketplace, get your website instantly setup with free real-time web analytics, create a KML file so that your local business can be found online. It is free and easy to download and install IonCube. Do it or contact your web host to do it for you."); ?>
                <a target="_blank"  title="<?php echo $this->translate('download and install IonCube loader'); ?>" href="http://www.ioncube.com/loaders.php">(<?php echo $this->translate('download and install IonCube loader'); ?>)</a>
				</p>
			</li>
			<?php endif;?>
		</ul>
	</div>

	<div id="right" class="grid_6 alpha omega">
		<h3 class="title-step"><?php echo $this->translate('Checking file system permissions');?></h3>
		<span class="description-step"><?php echo $this->translate('Some folders need to be writable to allow the toaster to function properly.');?></span>
		<ul>
			<?php foreach ($this->permissions['dir'] as $dirname => $status): ?>
				<li class="<?php if ($status !== 'writable' ) echo "error red";  ?>">
					<?php echo $this->translate("Folder %1\$s is " . $status, $dirname); ?>
				</li>
			<?php endforeach; ?>
			<?php foreach ($this->permissions['file'] as $filename => $status): ?>
				<li class="<?php if ($status !== 'writable' ) echo "error red";  ?>">
                    <?php echo $this->translate("File %1\$s is " . $status, $filename); ?>
				</li>
			<?php endforeach; ?>
		</ul>
		<?php if ($this->gotoNext === true): ?>
		<div class="bravo green"><?php echo $this->translate('Bravo! All good to go!');?></div>
		<?php endif; ?>
		<form method="post" action="" id="gotonext">
			<?php if ($this->gotoNext === true): ?>
			<input type="submit" value="<?php echo $this->translate('Next');?>" name="submit" />
			<?php else: ?>
			<input type="submit" value="<?php echo $this->translate('Check again');?>" name="check" />
			<?php endif; ?>
		</form>
	</div>
</div>