<header class="grid_12">
	<img class="logo" src="assets/logo.jpg" width="215" height="275" alt="Seotoaster install">
	<h1 class="grid_7" style="margin-top: 48px"><?php echo $this->translate('Seotoaster install');?></h1>
	<h2 class="step grid_7"><?php echo $this->translate('Step 2: Database setup'); ?></h2>
</header>
<!-- STEP 2 -->
<div id="step-content">
	<form method="post" action="" enctype="application/x-www-form-urlencoded" id="installer_form_config">
		<fieldset id="dbinfo" class="grid_6 alpha omega" style="border-right:2px dashed #ccc;margin-right:-2px;">
			<h3 class="title-step"><?php echo $this->translate('Setting up the Database.');?></h3>
			<span class="description-step"><?php echo $this->translate('Your server needs to meet the minimum requirements configuration in order to run the toaster. (You need MySQL server 5.x running)');?></span>
			<?php echo $this->configform->getElement('host'); ?>
			<?php echo $this->configform->getElement('username'); ?>
			<?php echo $this->configform->getElement('password'); ?>
			<?php echo $this->configform->getElement('dbname'); ?>
		</fieldset>

		<fieldset id="coreinfo" class="grid_6 alpha omega" >
			<div class="opacity">
				<h3 class="title-step"><?php echo $this->translate('Advanced settings (Optional)');?></h3>
				<span class="description-step">
					<img src="assets/toasters.jpg" alt="Multi-toasters setup" style="float:right;"/><?php echo $this->translate('Multi-toasters setup');?>:<br/>
                    <?php echo $this->translate("Did you know? You can share seotoaster's core files to run multiple websites from the same server. This is great to expedite upgrades for your  toaster. Simply enter the path for your master seotoaster core files and an unique name you wish to use for this website install.");?>
				</span>
				<div class="mt20px"></div>
				<?php echo $this->configform->getElement('corepath'); ?>
				<?php echo $this->configform->getElement('sitename'); ?>
			</div>



		</fieldset>

		<?php if (!empty($this->messages)): ?>
		<div class="grid_10 prefix_1 suffix_1 textcentered">
			<?php foreach ($this->messages as $msg) :?>
			<div class="box-error mt10px">
				<?php echo $msg; ?>
			</div>
			<?php endforeach; ?>
		</div>
		<?php endif;?>

		<div class="grid_6 prefix_6 textcentered">
			<?php echo $this->configform->getElement('check'); ?>
			<?php echo $this->configform->getElement('submit'); ?>
		</div>
	</form>
</div>