<div class="grid_12">
	<div class="header">
		<h1>SEOTOASTER 2.0 - <?php echo $this->translate('Our congratulations!'); ?></h1>
	</div>
	<div class="content ui-helper-clearfix">
		
		<div class="ui-helper-clearfix">
			<p class="header">New seotoaster has been installed for you!</p>
			
			<p>Now you need to remove or rename folder <strong>"install"</strong> in <code><?php echo INSTALL_PATH; ?></code> before going live.</p>
			
			<p>Then click on the following link and login with your e-mail and password.</p>
		
			<p>Your login url:
			<a href="<?php echo $this->protocol . '://' .$this->websiteUrl.'go'; ?>"><?php echo $this->protocol . '://' .$this->websiteUrl.'go'; ?></a>
			</p>
		</div>
        <?php if(!$this->serverConfigGenerated): ?>
		    <?php echo $this->partial('_server.phtml'); ?>
        <?php endif?>
	</div>
    <img border="0" height="1" width="1" src="https://www.seotoaster.com/beacon.png.php?url=<?php echo $this->websiteUrl; ?>" />
</div>