<form action="javascript:;" method="post" data-name="imgrotator" id="imgrotator-widget-form" class="wmc-block">
    <p>
        <?php echo $this->formLabel('rotator-folders', $this->translate('Select a folder'), array('class' => 'grid_5 alpha mt0-25em')); ?>
        <?php echo $this->formSelect('rotatorFolders', null, array('id' => 'rotator-folders', 'class' => 'grid_7 alpha omega small folders')); ?>
    </p>
    <p class="mt5px">
        <label class="pointer">
            <span class="grid_5 alpha"><?php echo $this->translate('Slide show'); ?></span>
            <?php echo $this->formCheckbox('rotatorSlideshow', null, array('id' => 'rotator-slideshow', 'class' => 'wmc-input allowzero')); ?>
        </label>
    </p>
    <p class="mt5px">
        <?php echo $this->formLabel('rotator-interval', $this->translate('Rotate time'), array('class' => 'grid_5 alpha mt0-25em')); ?>
        <?php echo $this->formText('rotatorInterval', Widgets_Imgrotator_Imgrotator::DEFAULT_SWAP_TIME, array('id' => 'rotator-interval', 'class' => 'grid_7 alpha omega small')); ?>
    </p>
    <p class="mt5px">
        <?php echo $this->formLabel('rotator-thumb-width', $this->translate('Max. width'), array('class' => 'grid_5 alpha mt0-25em')); ?>
        <?php echo $this->formText('rotatorThumbWidth', Widgets_Imgrotator_Imgrotator::DEFAULT_SLIDER_WIDTH, array('id' => 'rotator-thumb-width', 'class' => 'grid_7 alpha omega small')); ?>
    </p>
    <p class="mt5px">
        <?php echo $this->formLabel('rotator-thumb-height', $this->translate('Max. height'), array('class' => 'grid_5 alpha mt0-25em')); ?>
        <?php echo $this->formText('rotatorThumbHeight', Widgets_Imgrotator_Imgrotator::DEFAULT_SLIDER_HEIGHT, array('id' => 'rotator-thumb-height', 'class' => 'grid_7 alpha omega small')); ?>
    </p>
    <p class="mt5px">
        <?php echo $this->formLabel('rotator-effect', $this->translate('Effect'), array('class' => 'grid_5 alpha mt0-25em')); ?>
        <?php echo $this->formSelect('rotatorEffect', 'none', array('id' => 'rotator-effect', 'class' => 'grid_7 alpha omega small'), Widgets_Imgrotator_Imgrotator::$_defaultEffects); ?>
    </p>
    <p class="mt5px">
        <label class="pointer">
            <span class="grid_5 alpha"><?php echo $this->translate('Pager'); ?></span>
            <?php echo $this->formCheckbox('rotatorPager', null, array('id' => 'rotator-pager', 'class' => 'wmc-input allowzero')); ?>
        </label>
    </p>
    <p class="mt5px">
        <label class="pointer">
            <span class="grid_5 alpha"><?php echo $this->translate('Prev/Next'); ?></span>
            <?php echo $this->formCheckbox('rotatorPrevnext', null, array('id' => 'rotator-prevnext', 'class' => 'wmc-input allowzero')); ?>
        </label>
    </p>
    <p class="mt5px">
        <label class="pointer">
            <span class="grid_5 alpha"><?php echo $this->translate('Content'); ?></span>
            <?php echo $this->formCheckbox('rotatorContent', null, array('id' => 'rotator-content', 'class' => 'wmc-input allowzero')); ?>
        </label>
    </p>
    <?php echo $this->formSubmit('applyWidget', 'Apply', array('class' => 'apply-widget btn block small')); ?>
</form>
<script type="text/javascript">
	$(function() {
		$(document).on('blur', '#rotator-thumb-width', function() {
			$('#rotator-thumb-height').val($(this).val());
		});
	});
</script>