<script type="text/javascript">
    $(function() {
        var params = JSON.parse('<?php echo $this->params; ?>'),
            data   = {
                pid  : '<?php echo $this->pageId;?>',
                name : '<?php echo $this->name;?>',
                type : '<?php echo $this->type;?>',
                co   : 1
            };
        $.get('<?php echo $this->websiteUrl?>api/toaster/containers/', $.extend(data, params),
            function(resp) {
                var content = $('div.<?php echo md5($this->name . $this->type); ?>');
                content.empty();
                if(typeof resp !== 'undefined') {
                    content.html(resp['<?php echo $this->name; ?>'] + '<?php echo $this->controls; ?>');
                }
        }, 'json');
    });
</script>
<div class="ajax-content <?php echo md5($this->name.$this->type).($this->isPublished ? '' : ' unpublished'); ?>">
    <img src="<?php echo $this->websiteUrl; ?>system/images/ajax-loader-small.gif" style="margin: 20px auto; display: block;">
</div>