<script type="text/javascript">
    $(function() {
        $.get('<?php echo $this->websiteUrl?>api/toaster/containers/', {
                pid  : '<?php echo $this->pageId;?>',
                name : '<?php echo $this->name;?>',
                type : '<?php echo $this->type;?>',
                co   : 1
            },
            function(resp) {
                var content = $('div.<?php echo md5($this->name . $this->type); ?>');
                $(content).empty().html(resp['<?php echo $this->name; ?>'] + '<?php echo $this->controls; ?>');
        }, 'json');
    });
</script>
<div class="ajax-content <?php echo md5($this->name . $this->type); ?>"><?php echo $this->translate('Please wait'); ?>...</div>