<?php if(!empty($this->pages)): ?>
	<ul class="main_menu">
		<?php foreach ($this->pages as $key => $page): ?>
			<li class="category cat-<?php echo $key; ?>"><a title="<?php echo $page['category']->getH1(); ?>" href="<?php echo $this->websiteUrl . $page['category']->getUrl(); ?>"><?php echo $page['category']->getNavName(); ?></a>
				<?php if(isset($page['subPages'])): ?>
					<ul id="<?php echo $page['category']->getUrl(); ?>">
						<?php foreach ($page['subPages'] as $subPage): ?>
							<li class="page"><a title="<?php echo $subPage->getH1(); ?>" href="<?php echo $this->websiteUrl . $subPage->getUrl(); ?>"><?php echo $subPage->getNavName(); ?></a></li>
						<?php endforeach; ?>
					</ul>
				<?php endif; ?>
			</li>
		<?php endforeach; ?>
	</ul>
<script type="text/javascript" charset="utf-8">
	$(function() {
		var currentUrl = window.location.href;
		//currentUrl     = currentUrl.replace(/#.*/g, '');
		if(currentUrl && typeof currentUrl != 'undefined') {
			$('*').find("a[href='" + currentUrl + "']").each(function() {
				$(this).addClass('current');
			});
		}
	});
</script>
<?php endif; ?>