<?php if(!empty($this->pages)): ?>
<ul class="main_menu">
    <?php $i = 1; ?>
    <?php foreach ($this->pages as $key => $page): ?>
    <li class="category cat-<?php echo $i++; ?>"><a title="<?php echo ($page['optimizedH1']) ? $page['optimizedH1'] : $page['h1']; ?>" href="<?php echo $this->websiteUrl . ($page['optimizedUrl'] ? $page['optimizedUrl'] : $page['url']); ?>"><?php echo ($page['optimizedNavName'] ? $page['optimizedNavName'] : $page['navName']) ; ?></a>
        <?php if(isset($page['subPages']) && !empty($page['subPages']) ): ?>
            <ul id="<?php echo str_replace('.html', '', ($page['optimizedUrl'] ? $page['optimizedUrl'] : $page['url'])); ?>">
                <?php foreach ($page['subPages'] as $subPage): ?>
                <li class="page"><a title="<?php echo ($subPage['optimizedH1']) ? $subPage['optimizedH1'] : $subPage['h1']; ?>" href="<?php echo $this->websiteUrl . ($subPage['optimizedUrl'] ? $subPage['optimizedUrl'] : $subPage['url']); ?>"><?php echo ($subPage['optimizedNavName'] ? $subPage['optimizedNavName'] : $subPage['navName']) ; ?></a></li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<script type="text/javascript" charset="utf-8">
    $(function() {
        var currentUrl = decodeURI(window.location.href);
        if(currentUrl && typeof currentUrl != 'undefined') {
            $("a[href='" + currentUrl + "']").addClass('current');
        }
    });
</script>
<?php endif; ?>