<?php if(!empty($this->pages)): ?>
<ul class="main_menu">
    <?php $i = 1; ?>
    <?php foreach ($this->pages as $key => $page): ?>
    <li class="category cat-<?php echo $i++; ?>"><a title="<?php echo ($page['category']['optimizedH1']) ? $page['category']['optimizedH1'] : $page['category']['h1']; ?>" href="<?php echo $this->websiteUrl . ($page['category']['optimizedUrl'] ? $page['category']['optimizedUrl'] : $page['category']['url']); ?>"><?php echo ($page['category']['optimizedNavName'] ? $page['category']['optimizedNavName'] : $page['category']['navName']) ; ?></a>
        <?php if(isset($page['subPages'])): ?>
            <ul id="<?php echo str_replace('.html', '', ($page['category']['optimizedUrl'] ? $page['category']['optimizedUrl'] : $page['category']['url'])); ?>">
                <?php foreach ($page['subPages'] as $subPage): ?>
                <li class="page"><a title="<?php echo ($subPage['optimizedH1']) ? $subPage['optimizedH1'] : $subPage['h1']; ?>" href="<?php echo $this->websiteUrl . ($subPage['optimizedUrl'] ? $subPage['optimizedUrl'] : $subPage['url']); ?>"><?php echo ($subPage['optimizedNavName'] ? $subPage['optimizedNavName'] : $subPage['navName']) ; ?></a></li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
    </li>
    <?php endforeach; ?>
</ul>
<script type="text/javascript" charset="utf-8">
    $(function() {
        var currentUrl = decodeURI(window.location.href);
        if(currentUrl && typeof currentUrl != 'undefined') {
            $('*').find("a[href='" + currentUrl + "']").each(function() {
                $(this).addClass('current');
            });
        }
    });
</script>
<?php endif; ?>