<ul class="static_menu">
	<?php foreach ($this->staticPages as $staticPage): ?>
        <?php
            $targetBlank = '';
            $staticPageUrl = $staticPage->getUrl();
        ?>
        <?php if($staticPageUrl == 'index.html') {
            $staticPageUrl = '';
        }?>
        <?php $staticUrl = $this->websiteUrl . $staticPageUrl;?>
        <?php if($staticPage->getExternalLinkStatus() === '1'):?>
            <?php $staticUrl = $staticPage->getExternalLink();?>
            <?php $targetBlank = 'target="_blank"';?>
        <?php elseif($staticPage->getPageTargetBlank()):?>
            <?php $targetBlank = 'target="_blank"';?>
        <?php endif;?>
        <li>
            <?php if($staticPage->getNotClickable() === '1'):?>
                <a title="<?php echo ucwords($staticPage->getH1());?>"><span><?php echo $staticPage->getNavName(); ?></span></a>
            <?php else:?>
                <a href="<?php echo $staticUrl;?>" <?php echo $targetBlank;?> title="<?php echo ucwords($staticPage->getH1());?>"><span><?php echo $staticPage->getNavName(); ?></span></a>
            <?php endif;?>
        </li>

	<?php endforeach; ?>
</ul>
