<form action="" method="post" class="grid_12" style="text-align: center; margin-top: 10px;">
	<div id="language" class="seotoaster" id="seotoaster">
	<?php foreach($this->langs as $locale => $flag): ?>
	<input type="radio" name="lang" value="<?php echo $locale;?>" id="lang-<?php echo $locale;?>"
		   <?php echo $this->translate()->getLocale() === $locale ? 'checked="checked"' : '' ; ?>
		   />
	<label for="lang-<?php echo $locale;?>">
		<img src="../<?php echo $flag;?>" alt="<?php echo Zend_Locale::getTranslation($locale, 'language');?>" />
	</label>
	<?php endforeach; ?>
	</div>
</form>
<script>
	$('#language').delegate('input[type="radio"]','change', function(){
		$(this).closest('form').submit();
	}).buttonset();
</script>