<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<?php echo $this->headMeta()->setCharset('utf-8'); ?>
		
		<?php $this->headTitle('Welcome to SEOTOASTER 2.0'); ?>
		<?php echo $this->headTitle(); ?>
		
		<?php $this->headLink()->appendStylesheet('../system/css/reset.css'); ?>
		<?php $this->headLink()->appendStylesheet('../system/css/grid.css'); ?>
		<?php $this->headLink()->appendStylesheet('../system/uithemes/seotoasterui/seotoasterui.css'); ?>
		<?php $this->headLink()->appendStylesheet('assets/styles.css'); ?>

		<?php echo $this->headLink(); ?>
		
		<?php $this->jQuery()->enable(); ?>
		<?php $this->jQuery()->uiEnable(); ?>

		<script>
        <?php $this->jQuery()->onLoadCaptureStart();?>
        $('#container').on('submit', 'form', function(e){
            // display loading message
            $('#loading').fadeIn();

            if( !$(e.target).attr('action'))
                e.target = $(e.target).closest('form');

            $.ajax({
                type: "POST",
                url: $(e.target).attr('action'),
                data: $(e.target).serialize(),
                beforeSend : function(xhr) {
                    return xhr.setRequestHeader('X-PJAX','true'); // IMPORTANT
                },
                success: function(response){
                    $('#container').html(response);
                    $('#container .content').prepend($('<div></div>', {id: 'loading'}));
                    $('#loading').fadeOut();
                },
                error: function() {
                    $('#loading').fadeOut();
                }
            });

          e.preventDefault();
          return false;
		}).on('change', 'div.opacity :input', function(){
			$(this).closest('div.opacity').removeClass('opacity');
        });
        <?php $this->jQuery()->onLoadCaptureEnd();?>
		</script>

		<?php echo $this->jQuery(); ?>
	</head>
	<body>
		<div class="seotoaster container_12">

			<div id="container">
				<?php echo $this->layout()->content; ?>
			</div>

			<footer class="grid_10 prefix_1">
				<p>
					Sometimes web hosting providers do not offer a suitable environment to the latest technology platforms like seotoaster.<br />
					If you run into difficulties, please visit <a href="http://www.seotoaster.com" title="SEOTOASTER open source CMS">seotoaster.com</a> for solutions.
				</p>
			</footer>

		</div>
	</body>
</html>

