<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<?php echo $this->headMeta()->setCharset('utf-8'); ?>
		
		<?php $this->headTitle('Welcome to SEOTOASTER 2.0'); ?>
		<?php echo $this->headTitle(); ?>
		
		<?php $this->headLink()->appendStylesheet('../system/css/reset.css'); ?>
		<?php $this->headLink()->appendStylesheet('../system/css/grid.css'); ?>
		<?php $this->headLink()->appendStylesheet('../system/uithemes/seotoasterui/seotoasterui.css'); ?>
		<?php $this->headLink()->appendStylesheet('css/styles.css'); ?>

		<?php echo $this->headLink(); ?>
		
		<?php $this->jQuery()->enable(); ?>
		<?php $this->jQuery()->uiEnable(); ?>
		<?php $this->jQuery()->addJavascriptFile('http://cdn.jquerytools.org/1.2.5/tiny/jquery.tools.min.js'); ?>

		<script>
        <?php $this->jQuery()->onLoadCaptureStart();?>
        $('#container').on('submit', 'form', function(e){
            // display loading message
            $('#loading').fadeIn();

            if( !$(e.target).attr('action'))
                e.target = $(e.target).closest('form');

            $.ajax({
                type: "POST",
                url: $(e.target).attr('action'),
                data: $(e.target).serialize(),
                beforeSend : function(xhr) {
                    return xhr.setRequestHeader('X-PJAX','true'); // IMPORTANT
                },
                success: function(response){
                    $('#container').html(response);
                    $('#container form :input[title!=""]').tooltip({
                           position: "top center",
                           opacity: 0.8
                    });
                    $('#container .content').prepend($('<div></div>', {id: 'loading'}));
                    $('#loading').fadeOut();
                },
                error: function() {
                    $('#loading').fadeOut();
                }
            });

          e.preventDefault();
          return false;
       });

//       $('#content form input.livecheck').live('change', function(){
//            $(this).closest('form').trigger('submit');
//       });
        <?php $this->jQuery()->onLoadCaptureEnd();?>
		</script>

		<?php echo $this->jQuery(); ?>
	</head>
	<body>
		<div id="container" class="installer seotoaster container_12 ui-helper-clearfix">
			<?php echo $this->layout()->content; ?>
		</div>
		<footer>
			<a href="http://www.seotoaster.com/" target="_blank" title="Visit our site for better experience"><span>www.seotoaster.com</span></a>
		</footer>
	</body>
</html>

