<div class="seotoaster container_12 w960 h640 rounded8px">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Manage drafts')); ?>
	<?php if($this->draftPages && is_array($this->draftPages)): ?>
		<?php foreach($this->draftPages as $draftPage): ?>
			<p style="overflow: hidden;">
				<a class="draft-page-link" data-url="<?php echo $this->websiteUrl . $draftPage->getUrl(); ?>" style="text-decoration: underline; font-size: 50px; font-family: Arial;"  href="javascript:;" title="<?php echo $draftPage->getH1(); ?>"><?php echo $draftPage->getNavName(); ?></a>
			</p>
		<?php endforeach; ?>
	<?php endif; ?>
</div>
<script type="text/javascript">
	$(function(){
		$('.draft-page-link').click(function() {
			top.location.href = $(this).data('url');
		})
	})
</script>