<div class="seotoaster container_12 w950 h570 rounded3px" id="addedit-page">
	<?php // echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('innerHeaderHtml' => $this->render('backend/page/top.phtml'))); ?>

	<?php
		$draftOrLive = $this->toasterDraftorlive(array(
			'published'        => !$this->pageForm->getDraft(),
			'publishAt'        => $this->pageForm->getPublishAt(),
			'onselectCallback' => 'datepickerCallback'
		));
		echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('innerHeaderHtml' => $draftOrLive));
	?>

	<div id="templatelist" class="h580 ui-helper-hidden" style="overflow: auto !important; width: 100%; z-index: 1; margin-top: -42px;"></div>
	<div id="falist" class="h570 ui-helper-hidden" style="overflow: auto !important; width: 100%; z-index: 1; margin-top: -42px;"></div>
	<form id="frm-page" action="<?php echo $this->url(); ?>" method="post" class="_fajax _reload">
		<div class="grid_6">
			<fieldset>
				<legend><?php echo $this->translate('Page Information'); ?></legend>
				<?php echo $this->pageForm->getElement('h1'); ?>
				<?php echo $this->pageForm->getElement('headerTitle'); ?>
				<?php echo $this->pageForm->getElement('url'); ?>
				<?php echo $this->pageForm->getElement('navName'); ?>
				<?php echo $this->pageForm->getElement('metaDescription'); ?>
				<?php echo $this->pageForm->getElement('metaKeywords'); ?>
			</fieldset>
		</div>
		<div class="grid_6">
			<fieldset>
				<legend><?php echo $this->translate('Navigation'); ?></legend>
				<?php echo $this->toasterRadio('inMenu', $this->pageForm->getShowInMenu(), array('class' => 'menu-selector'), $this->pageForm->getElement('inMenu')->getMultiOptions(), ''); ?>
				<div class="clear"></div>
				<div class="grid_12">
					<?php echo $this->formSelect('pageCategory', $this->pageForm->getParentId(), null, $this->pageForm->getElement('pageCategory')->getMultiOptions()); ?>
				</div>
			</fieldset>
			<fieldset>
				<legend><?php echo $this->translate('Settings'); ?></legend>
					<div class="grid_6"><label><?php echo $this->translate('Current template'); ?>:</label></div>
					<div class="grid_6">
						<?php
							echo $this->ajaxLink(
								$this->translate(!($this->pageForm->getElement('templateId')->getValue()) ? 'Select template' : $this->pageForm->getElement('templateId')->getValue()),
								$this->websiteUrl . 'backend/backend_theme/gettemplate/pageId/' . $this->pageForm->getElement('pageId')->getValue(),
								array(
									'complete' => "$('#templatelist').html(data).slideDown().css('overflow-y', 'auto');",
									'attribs'  => array(
										'id' => 'curr-template'
									)

								),
								array('listtemplates' => Application_Model_Models_Template::TYPE_REGULAR)
							);
						?>
					</div>
					<div class="grid_12 clear mt5px"></div>
					<div class="grid_6"><label><?php echo $this->translate('Is this page featured?'); ?></label></div>
					<div class="grid_6">
						<?php echo $this->toasterLink('backend_featured', 'featured', ((!$this->faCount) ? $this->translate('Not yet') : $this->translate('Yes') . ', ' . $this->faCount . ' ' . $this->translate('times')), 'pid/' . $this->pageForm->getElement('pageId')->getValue(), false, array('width' => '484', 'height' => '554')); ?>

						<?php
//							echo $this->ajaxLink(
//								$this->translate((!$this->faCount) ? $this->translate('Not yet') : $this->translate('Yes') . ', ' . $this->faCount . ' ' . $this->translate('times')),
//								$this->websiteUrl . 'backend/backend_featured/featured/pageId/' . $this->pageForm->getElement('pageId')->getValue(),
//								array(
//									'complete' => "$('#falist').html(data).slideDown();",
//								)
//							);
						?>

					</div>
					<div class="grid_12 mt10px">
						<label class="nopad grid_6">
							<?php echo $this->translate('Not found 404 page'); ?>
							<?php echo $this->pageForm->getElement('is404page')->renderViewHelper(); ?>
						</label>
						<label class="nopad grid_5">
							<?php echo $this->translate('Member only area'); ?>
							<?php echo $this->pageForm->getElement('protected')->renderViewHelper(); ?>
						</label>
						<label class="nopad grid_6">
							<?php echo $this->translate('Member landing page'); ?>
							<?php echo $this->pageForm->getElement('protected')->renderViewHelper(); ?>
						</label>
					</div>
			</fieldset>
			<fieldset>
				<legend><?php echo $this->translate('Page Teasers'); ?></legend>
				<div  class="grid_4 h160" style="overflow: hidden;">
					<img id="page-preview-image" style="max-height: 200px;" src="<?php echo $this->pagePreviewImage !== false ? $this->pagePreviewImage : $this->websiteUrl.'/system/images/noimage.png'; ?>" width="140px" alt="<?php echo $this->translate('Page preview image');?>" />
				</div>
				<div  class="grid_8 h150">
					<?php echo $this->pageForm->getElement('teaserText'); ?>
					<?php
						$uploader = $this->toasterUploader(array('id' => 'page-teaser-uploader','caller' => 'pagePreview', 'noMultiupload' => true, 'caption' => $this->translate('Upload teaser image')));
						echo $uploader;
					?>
				</div>
				<div class="clear"></div>
			</fieldset>
			<?php echo $this->pageForm->getElement('templateId'); ?>
			<?php echo $this->pageForm->getElement('pageId'); ?>
			<?php echo $this->pageForm->getElement('draft'); ?>
			<?php echo $this->pageForm->getElement('publishAt'); ?>
			<?php echo $this->pageForm->getElement('updatePage'); ?>
		</div>
	</form>
	<div class="clear"></div>
</div>
<script type="text/javascript">
$(function() {
	$('#h1').focus();
})
</script>

<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/page.js'); ?>
<?php //$this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/featuredarea.js'); ?>