<div class="seotoaster container">
    <?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Add / Remove subfolder', 'helpSection' => $this->helpSection)); ?>
    <div class="content-footer">
        <form id="frm-pagefolder" class="_fajax grid_12 mb15px form-inline" action="<?php echo $this->url(); ?>" method="post" data-callback="reloadPageFolders">
            <div class="grid_5 alpha">
                <?php echo $this->form->getElement('pageFolder'); ?>
            </div>
            <div class="grid_5 alpha omega mt0px type-url">
                <?php echo $this->form->getElement('indexPage'); ?>
            </div>
            <?php echo $this->form->getElement('addFolder')->renderViewHelper(); ?>
            <input type="hidden" name="secureToken" value="<?php echo $this->secureToken;?>" />
        </form>

        <div id="redirect-title" class="grid_12 list-title">
            <div class="grid_5 alpha omega ml-grid mr-grid"><?php echo $this->translate('Folders'); ?></div>
            <div class="grid_6 mr0"><?php echo $this->translate('Index page url'); ?></div>
        </div>
        <div id="folders-list" class="grid_12 items-list"></div>
    </div>
    <div class="footer">
        <div class="grid_12">
            <?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_saveandclose.phtml'); ?>
        </div>
    </div>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/folders.js'); ?>
