<div class="seotoaster container_12 w960 h640 rounded8px" id="addedit-page">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('innerHeaderHtml' => $this->render('backend/page/top.phtml'))); ?>
	<div id="templatelist" class="h600 ui-helper-hidden" style="overflow: auto !important; width: 100%; z-index: 1;"></div>
	<div id="falist" class="h640 ui-helper-hidden" style="overflow: auto !important; width: 100%; z-index: 1;"></div>
	<form id="frm-page" action="<?php echo $this->url(); ?>" method="post" class="_fajax _reload">
		<div class="grid_6">
			<fieldset>
				<legend><?php echo $this->translate('Meta Information'); ?></legend>
				<?php echo $this->pageForm->getElement('h1'); ?>
				<?php echo $this->pageForm->getElement('headerTitle'); ?>
				<?php echo $this->pageForm->getElement('url'); ?>
				<?php echo $this->pageForm->getElement('navName'); ?>
				<?php echo $this->pageForm->getElement('metaDescription'); ?>
				<?php echo $this->pageForm->getElement('metaKeywords'); ?>
			</fieldset>
		</div>
		<div class="grid_6">
			<fieldset>
				<legend><?php echo $this->translate('Navigation'); ?></legend>
				<?php echo $this->toasterRadio('inMenu', $this->pageForm->getShowInMenu(), array('class' => 'menu-selector'), $this->pageForm->getElement('inMenu')->getMultiOptions(), ''); ?>
				<div class="clear"></div>
				<div class="grid_12">
					<?php echo $this->formSelect('pageCategory', $this->pageForm->getParentId(), null, $this->pageForm->getElement('pageCategory')->getMultiOptions()); ?>
				</div>
			</fieldset>
			<fieldset>
				<legend><?php echo $this->translate('Settings'); ?></legend>
					<div class="grid_6 label">Current Template:</div>
					<div class="grid_6" style="padding:5px 0px">
						<?php
							echo $this->ajaxLink(
								$this->translate(!($this->pageForm->getElement('templateId')->getValue()) ? 'Select template' : $this->pageForm->getElement('templateId')->getValue()),
								$this->websiteUrl . 'backend/backend_theme/gettemplate/',
								array(
									'complete' => "$('#templatelist').html(data).slideDown().css('overflow-y', 'auto');",
									'attribs'  => array(
										'id' => 'curr-template'
									)

								),
								array('listtemplates' => Application_Model_Models_Template::TYPE_REGULAR)
							);
						?>
					</div>
					<div class="grid_12 clear mt5px"></div>
					<div class="grid_6 label">Page is featured:</div>
						<div class="grid_6" style="padding:5px 0px">
							<?php echo $this->toasterLink('backend_featured', 'featured', (!$this->faCount) ? $this->translate('Not yet') : $this->translate('Yes') . ', ' . $this->faCount . ' ' . $this->translate('times'), 'pid/' . $this->pageForm->getElement('pageId')->getValue()); ?>
							<?php
//								echo $this->ajaxLink(
//									$this->translate((!$this->faCount) ? $this->translate('Not yet') : $this->translate('Yes') . ', ' . $this->faCount . ' ' . $this->translate('times')),
//									$this->websiteUrl . 'backend/backend_featured/featured/',
//									array(
//										'update'   => '#falist',
//										'complete' => '$("#falist").slideDown();loadFaList()'
//									),
//									array()
//								);
							?>
						</div>
					<div class="grid_12 mt10px">
						<label>This page is also</label>
						<div class="page-opts">
							<p><?php echo $this->pageForm->getElement('is404page'); ?></p>
							<p><?php echo $this->pageForm->getElement('protected'); ?></p>
						</div>
					</div>
			</fieldset>
			<fieldset>
				<legend><?php echo $this->translate('Page Teasers'); ?></legend>
				<div  class="grid_4 h150">
					<img id="page-preview-image" src="<?php echo $this->pagePreviewImage !== false ? $this->pagePreviewImage : $this->websiteUrl.'/system/images/noimage.png'; ?>" width="140px" alt="<?php echo $this->translate('Page preview image');?>" />
				</div>
				<div  class="grid_8 h150">
					<?php echo $this->pageForm->getElement('teaserText'); ?>
				</div>
				<div class="clear"></div>
			</fieldset>
			<?php echo $this->pageForm->getElement('templateId'); ?>
			<?php echo $this->pageForm->getElement('pageId'); ?>
			<?php echo $this->pageForm->getElement('draft'); ?>
			<?php echo $this->pageForm->getElement('publishAt'); ?>
			<?php echo $this->pageForm->getElement('updatePage'); ?>
		</div>
	</form>
	<?php
		$uploader = $this->toasterUploader(array('id' => 'page-teaser-uploader','caller' => 'pagePreview', 'noMultiupload' => true, 'caption' => $this->translate('Upload image')));
		echo $uploader;
	?>
	<div id="page-teaser-uploader-filelist" class="ui-helper-hidden"></div>
	<div class="clear"></div>
</div>
<script type="text/javascript">
$(function() {
	$('#h1').focus();
})
</script>

<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/page.js'); ?>