<div class="seotoaster container refreshOnClose">
    <?php echo $this->partial('admin'.DIRECTORY_SEPARATOR.'_header.phtml', array('headerText' => 'Edit repeat')); ?>
    <form class="content-auto" action="<?php echo $this->configRepeat->getAction(); ?>" method="<?php echo $this->configRepeat->getMethod(); ?>">
        <div class="grid_2">
            <label><?php echo $this->translate('Quantity'); ?></label>
            <?php echo $this->configRepeat->getElement('quantity'); ?>
        </div>
        <div class="grid_7 mt0px">
            <label><?php echo $this->translate('Order'); ?></label>
            <?php echo $this->configRepeat->getElement('orderContent'); ?>
        </div>
        <div class="grid_3 alpha mt2em">
            <label>
                <?php echo $this->translate('Use inversion'); ?>
                <?php echo $this->configRepeat->getElement('inversion'); ?>
            </label>
        </div>
        <?php echo $this->configRepeat->getElement('submit')->renderViewHelper(); ?>
    </form>
</div>
