<?php if(!empty($this->pages)): ?>
    <ul class="sitemap">
        <?php foreach ($this->pages as $key => $page): ?>
            <li>
                <?php if($page['category']['external_link_status'] === '1'):?>
                    <?php $pageUrl = $page['category']['external_link'];?>
                    <?php $targetBlank = 'target="_blank"';?>
                <?php else:?>
                    <?php $targetBlank = '';?>
                    <?php $pageUrl = $this->websiteUrl . $page['category']['url'];?>
                <?php endif;?>
                <a title="<?php echo $page['category']['h1']; ?>"
                   href="<?php echo $pageUrl; ?>" <?php echo $targetBlank; ?>><?php echo $page['category']['navName']; ?></a>
                <?php if(isset($page['subPages'])): ?>
                    <ul id="<?php echo str_replace('.html', '', $page['category']['url']); ?>">
                        <?php foreach ($page['subPages'] as $subPage): ?>
                            <?php if($subPage['external_link_status'] === '1'):?>
                                <?php $subPageUrl = $subPage['external_link'];?>
                                <?php $targetBlank = 'target="_blank"';?>
                            <?php else:?>
                                <?php $targetBlank = '';?>
                                <?php $subPageUrl = $this->websiteUrl . $subPage['url'];?>
                            <?php endif;?>
                            <li class="page">
                                <a title="<?php echo $subPage['h1']; ?>"
                                   href="<?php echo $subPageUrl; ?>" <?php echo $targetBlank;?>><?php echo $subPage['navName']; ?></a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<!-- flat pages here -->
<?php $newsPageNavName = $this->translate('News'); ?>
<?php if(!empty($this->flatPages)): ?>
    <ul class="sitemap">
        <?php foreach ($this->flatPages as $key => $flatPage): ?>
            <?php $flatPage = $flatPage->toArray(); ?>
            <?php if(empty($flatPage['extraOptions'])) :?>
                <?php if($flatPage['externalLinkStatus'] === '1'):?>
                    <?php $flatPageUrl = $flatPage['externalLink'];?>
                    <?php $targetBlank = 'target="_blank"';?>
                <?php else:?>
                    <?php $targetBlank = '';?>
                    <?php $flatPageUrl = $this->websiteUrl . $flatPage['url'];?>
                <?php endif;?>
                <li class="page">
                    <a title="<?php echo $flatPage['h1']; ?>"
                       href="<?php echo $flatPageUrl; ?>" <?php echo $targetBlank;?>><?php echo $flatPage['navName']; ?></a>
                </li>
            <?php elseif(!empty($flatPage['extraOptions']) && in_array('option_newsindex', $flatPage['extraOptions'])): ?>
                <?php $newsPageNavName = $flatPage['navName'];?>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if(isset($this->newsFolder)):?>
            <li>
                <a href="<?php echo $this->websiteUrl . (empty($this->newsFolder) ? '' : $this->newsFolder . '/'); ?>"
                   title="<?php echo $newsPageNavName; ?>" ><?php echo $newsPageNavName; ?></a>
            </li>
        <?php endif;?>
    </ul>
<?php endif; ?>
    <!-- nomenu pages here -->
<?php if(!empty($this->nomenuPages)): ?>
    <ul class="sitemap">
        <?php foreach ($this->nomenuPages as $key => $page): ?>
            <?php $page = $page->toArray(); ?>
            <li class="page">
                <?php if($page['externalLinkStatus'] === '1'):?>
                    <?php $pageUrl = $page['externalLink'];?>
                    <?php $targetBlank = 'target="_blank"';?>
                <?php else:?>
                    <?php $targetBlank = '';?>
                    <?php $pageUrl = $this->websiteUrl . (isset($page['optimizedUrl']) ? $page['optimizedUrl'] : $page['url']);?>
                <?php endif;?>
                <a title="<?php echo isset($page['optimizedH1']) ? $page['optimizedH1'] : $page['h1']; ?>"
                   href="<?php echo $pageUrl; ?>" <?php echo $targetBlank;?>>
                    <?php echo (isset($page['optimizedNavName']) ? $page['optimizedNavName'] : $page['navName']) ; ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>