<?php
class Widgets_Mobile_Mobile extends Widgets_Abstract {

    const MODE_MOBILE = 'mobile';

    const MODE_TABLET = 'tablet';

    const MODE_DESKTOP = 'desktop';


    protected $_cacheable = false;

    /**
     * @var Helpers_Action_Session
     */
    protected $_sessionHelper;

    /**
     * @var Helpers_Action_Mobile
     */
    protected $_mobileHelper;

    protected function _init() {
        parent::_init(); // TODO: Change the autogenerated stub
        $this->_sessionHelper = Zend_Controller_Action_HelperBroker::getStaticHelper('session');
        $this->_mobileHelper = Zend_Controller_Action_HelperBroker::getStaticHelper('mobile');
    }


    protected function _load() {
        if (!empty($this->_options)) {
            $method = '_render' . ucfirst(array_shift($this->_options));
            if (method_exists($this, $method)) {
                return $this->$method();
            }
        }
    }

    /**
     * Renders link that switch between mobile and desktop templates
     * @return string Widget html
     */
    protected function _renderSwitch() {
        if (null !== ($mobileSwitch = $this->_sessionHelper->mobileSwitch)) {
            $mobileSwitch = !$mobileSwitch ?  0 : 1;
        } else {
            $mobileSwitch = $this->_mobileHelper->isMobile() ? 0 : 1;
        }

        $thisPageUrl = $this->_toasterOptions['websiteUrl'].$this->_toasterOptions['url'];
        $cssClass    = ($mobileSwitch == 1) ? ' full' : ' mobile';
        $textLink    = ($mobileSwitch == 1) ? $this->_translator->translate('Go to mobile site') : $this->_translator->translate('Go to full site');
        $content     = '<a class="widgets-mobile-switch'.$cssClass.'" href="'.$thisPageUrl.'?mobileSwitch='.$mobileSwitch.'" title="'.$textLink.'">'.$textLink.'</a>';

        return $content;
    }

    protected function _renderDevice() {
        // detecting on what device we are now
        if ($this->_mobileHelper->isMobile()) {
            $deviceType = $this->_mobileHelper->isTablet() ? self::MODE_TABLET : self::MODE_MOBILE ;
        } else {
            $deviceType = self::MODE_DESKTOP;
        }

        // if nothing passed into widget options - simple return current device type
        if (empty($this->_options)) {
            return $deviceType;
        }

        // parse if we got some options

        $option = preg_grep('/^(?:'.$deviceType.')=/i', $this->_options);
        if (!empty($option)) {
            $option = reset($option);
            list ($key, $params) = explode('=', $option);
            if ($key === $deviceType && !empty($params)){
                $params = explode(',', $params);
                return implode(' ', $params);
            }
        }
    }

}