<div class="seotoaster container_12 w900">
	<form id="frm-page" action="<?php echo $this->url(); ?>" method="post" class="_fajax">
		<div class="grid_6">
			<fieldset>
				<legend>Meta Information</legend>
				<?php echo $this->pageForm->getElement('h1'); ?>
				<?php echo $this->pageForm->getElement('headerTitle'); ?>
				<?php echo $this->pageForm->getElement('url'); ?>
				<?php echo $this->pageForm->getElement('navName'); ?>
				<?php echo $this->pageForm->getElement('metaDescription'); ?>
				<?php echo $this->pageForm->getElement('metaKeywords'); ?>
			</fieldset>
		</div>
		<div class="grid_6">
			<fieldset>
				<legend>Navigation</legend>
				<?php echo $this->toasterRadio('inMenu', $this->pageForm->getShowInMenu(), null, $this->pageForm->getElement('inMenu')->getMultiOptions(), ''); ?>
				<?php //echo $this->pageForm->getElement('inMenu'); ?>
				<div class="clear"></div>
				<div class="grid_12">
					<?php //echo $this->pageForm->getElement('pageCategory'); ?>
					<?php echo $this->formSelect('pageCategory', $this->pageForm->getParentId(), null, $this->pageForm->getElement('pageCategory')->getMultiOptions()); ?>
				</div>
			</fieldset>
			<fieldset>
				<legend>Settings</legend>
					<div class="grid_6 label">Current Template:</div>
					<div class="grid_6" style="padding:5px 0px"><a href="#">Select Template</a></div>
					<div class="grid_12 clear mt5px"></div>
					<div class="grid_6 label">Page is featured:</div>
					<div class="grid_6"  style="padding:5px 0px"><a href="#">Not Yet</a></div>
					<div class="grid_12 mt10px">
						<label>This page is also</label>
						<div class="grid_6">
							<p><?php echo $this->pageForm->getElement('404Page'); ?></p>
							<p><?php echo $this->pageForm->getElement('protectedPage'); ?></p>
						</div>
					</div>
			</fieldset>
			<fieldset>
				<legend>Page Teasers</legend>
				<div  class="grid_4 h100">Image here <br />button here</div>
				<div  class="grid_8 h100">
					<?php echo $this->pageForm->getElement('teaserText'); ?>
				</div>
				<div class="clear"></div>
			</fieldset>
			<?php echo $this->pageForm->getElement('updatePage'); ?>
		</div>
	</form>
	<div class="clear"></div>
</div>