<div class="seotoaster container_12 h570 rounded3px">
    <?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml',
        array('headerText' => 'Manage action e-mails', 'helpSection' => 'actionemails')); ?>
    <div class="grid_12">
        <h1 class="ui-helper-reset mb10px" style="text-align:center;">
            <?php echo $this->translate('Manage action e-mails'); ?>
        </h1>
        <iframe width="530" height="440" style="display: block; margin-left: auto; margin-right: auto;"
                src="https://player.vimeo.com/video/49227390?title=0&amp;byline=0&amp;portrait=0" frameborder="0"
                webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="">
        </iframe>
    </div>
</div>
