<?php $this->jQuery()->addJavascriptFile($this->websiteUrl.'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js');?>
<div class="seotoaster container">
    <?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array(
		'headerText' => 'Manage action e-mails & SMS',
		'innerHeaderHtml' =>  $this->formSelect('actions', null, array('class' => 'fl-none grid_4'), $this->actionsOptions),
		'helpSection' => 'actionemails'
	)); ?>
    <div class="content-footer">
		<form action="javascript:;" method="post" id="ations-triggers-frm">
			<div class="grid_12" id="action-triggers">
				<p>
					<?php echo $this->translate('Please, select an event area above to view & edit currently configured related action emails & SMS or create new ones.'); ?>
				</p>
				<ul class="actions-list list-unstyled column_4 full-width">
					<?php foreach($this->actionsOptions as $trigger):?>
						<?php if ($trigger != $this->translate('Select event area') ): ?>
							<li><span class="action-preview ticon-action-emails" data-action="<?php echo str_replace(" ","-",strtolower($trigger));?>"></span><span class="action-name"><?php echo $trigger;?></span></li>
						<?php endif; ?>
					<?php endforeach;?>
				</ul>
			</div>
            <input type="hidden" name="secureToken" value="<?php echo $this->secureToken;?>" />
		</form>
	</div>
	<?php //echo $this->formSubmit('saveActions', 'Save changes', array('id' => 'save-actions', 'class' => 'btn ticon-save')); ?>
    <div class="footer grid_12">
        <button id="save-actions" class="btn ticon-save" name="saveActions" type="submit"><?php echo $this->translate('Save changes'); ?></button>
    </div>

<script id="triggerActionTemplate" type="text/x-jquery-tmpl">
    {{each(key, trigger) triggers}}
        {{each(name, data) trigger}}
            {{if name == triggerName}}
                <fieldset class="background">
                    {{if triggerId}}
                        <?php echo $this->formHidden('actions[${index}][id]', '${triggerId}'); ?>
                        <?php echo $this->formHidden('actions[${index}][delete]', 'false'); ?>
                    {{/if}}
                    <span class="ticon-close btn icon link error" style="float:right; cursor:pointer;"></span>
                    <?php echo $this->formHidden('actions[${index}][trigger]', '${name}'); ?>
                    <div class="trigger-title mt0px">
                        <?php echo $this->translate('When'); ?> <strong>${title}</strong><br />
                    </div>
                    {{if triggerName == 'store_neworder' || triggerName == 'store_trackingnumber'}}
                    <p>
                        <?php echo $this->formLabel('recipients', 'send', array('class' => 'grid_4 mt5px')); ?>
                        <?php echo $this->formSelect('actions[${index}][service]', '${sendto}', array('class' => 'grid_8'), $this->services); ?>
                    </p>
                    {{else}}
                        <?php echo $this->formHidden('actions[${index}][service]', 'email', array('class' => 'grid_8')); ?>
                    {{/if}}
					<p>
						<?php echo $this->formLabel('recipients', 'send to', array('class' => 'grid_4 mt5px')); ?>
						<?php echo $this->formSelect('actions[${index}][recipient]', '${sendto}', array('class' => 'grid_8'), $this->recipients); ?>
					</p>
					<p>
						<?php echo $this->formLabel('mailTemplates', 'use template', array('class' => 'grid_4 mt5px')); ?>
						<?php echo $this->formSelect('actions[${index}][template]', null, array('class' => 'grid_8'), $this->mailTemplates); ?>
					</p>
                    <p class="{{if serviceName == 'sms'}}hide{{/if}}">
                        <?php echo $this->formLabel('message', 'with message', array('class' => 'grid_4 mt5px')); ?>
                        <?php echo $this->formTextarea('actions[${index}][message]', '${message}', array('rows' => 4, 'class' => 'grid_8')); ?>
                    </p>
					<p>
						<?php echo $this->formLabel('from', 'from', array('class' => 'grid_4 mt5px')); ?>
						<?php echo $this->formText('actions[${index}][from]', '${from}', array('class' => 'grid_8')); ?>
					</p>
					<p>
						<?php echo $this->formLabel('subject', 'with subject', array('class' => 'grid_4 mt5px')); ?>
						<?php echo $this->formText('actions[${index}][subject]', '${subject}', array('class' => 'grid_8')); ?>
					</p>
                    {{if triggerName == 'store_neworder' || triggerName == 'store_trackingnumber'}}
                    <p class="{{if serviceName != 'sms'}}hide{{/if}}">
                        <?php echo $this->formLabel('smsText', 'insert plain text message only', array('class' => 'grid_12')); ?>
                        <?php echo $this->formTextarea('actions[${index}][smsText]', '', array('class' => 'grid_12', 'placeholder' => 'SMS are text only', 'rows' => '5', 'style' => 'height:172px;')); ?>
                    </p>
                    {{/if}}
                </fieldset>
            {{/if}}
        {{/each}}
    {{/each}}
</script>

<script type="text/x-jquery-tmpl" id="triggersTabs">
    <div class="tabs-nav-wrap">
        <span class="arrow left ticon-arrow-left3"></span>
        <span class="arrow right ticon-arrow-right3"></span>
        <ul id="triggers-tabs-holder" class="header">
            {{each(key, trigger) triggers}}
                {{if key == currentTrigger }}
                    {{each(name, data) trigger}}
                        <li><a href="#${key}-triegger-${name.replace(/\s+/g, '-')}">${title}</a></li>
                    {{/each}}
                {{/if}}
            {{/each}}
        </ul>
    </div>
    {{each(key, trigger) triggers}}
        {{if key == currentTrigger }}
            {{each(name, data) trigger}}
                <div id="${key}-triegger-${name.replace(/\s+/g, '-')}" class="tabs-contents">
                    <span class="new-trigger-action ticon-plus-sign text-center" data-trigger-name="${name}">
						<?php //echo $this->translate('Add a recipient'); ?>
					</span>
                </div>
            {{/each}}
        {{/if}}
    {{/each}}
</script>

<script type="text/javascript">
    $(function(){
        $('#save-actions').hide();

        var triggersTabsTmpl = $('#triggersTabs').template(),
            actionTriggers = <?php echo json_encode($this->triggers); ?>,
            actions = <?php echo json_encode($this->actions);?>,
            lastId = 0,
            atholder = $('#action-triggers');


        $(document).on('change', '#actions',function(){
            showAction($(this).val());
        }).on('click', '.actions-list li',function(){
            showAction($(this).find('.action-preview').data('action'));
        }).on('click', '.new-trigger-action',function(e){
            e.preventDefault();
            var triggerName       = $(e.target).data('triggerName');
            var actionTriggerTmpl = $('#triggerActionTemplate').template();
            $(e.target).before($.tmpl(actionTriggerTmpl, {triggers: actionTriggers, triggerName: triggerName, index: (lastId++), serviceName: null}));
        }).on('click', '#save-actions', function(e) {
            $.ajax({
                url        : '<?php echo $this->escape($this->url()); ?>',
                type       : 'post',
                dataType   : 'json',
                data       : $('#ations-triggers-frm').serialize(),
                beforeSend : function(){
                    showSpinner();
                },
                success    : function(response){
                    hideSpinner();
                    showMessage(response.responseText);
                }
            });
        }).on('click', '.ticon-close', function(){
            var $trigger = $(this).closest('fieldset');
            var id = $trigger.find('input[name*=id]');
            if(id.length){
                $trigger.find('input[name*=delete]').val(true);
                $trigger.appendTo($trigger.parent()).hide();
            }else{
                $trigger.remove();
            }
        }).on('change', 'select[id*="service"]', function() {
            var rootEl = $(this).parent().nextAll('p');
            var templateEl = rootEl.find('[id*="template"]');
            var fromEl = rootEl.find('[id*="from"]');
            var subjectEl = rootEl.find('[id*="subject"]');
            var messageEl  = rootEl.find('[id*="message"]');
            var smsTextEl  = rootEl.find('[id*="smsText"]');
            var recipientEl  = rootEl.find('[id*="recipient"]');
            var recipientIndex = $('[value="customer"]', recipientEl).index();
            if($(this).val() === 'sms') {
                $(templateEl).closest('p').hide();
                $(fromEl).closest('p').hide();
                $(subjectEl).closest('p').hide();
                $(messageEl).closest('p').hide();
                $(smsTextEl).closest('p').show();
                /*Hide all recipients except client*/
                $('option:eq('+recipientIndex+')', recipientEl).prop("selected", "selected");
                $('option:gt('+recipientIndex+')',recipientEl).hide();
                $('option:lt('+recipientIndex+')',recipientEl).hide();
                $('[value="admin"]').show();
            }
            else {
                $(templateEl).closest('p').show();
                $(fromEl).closest('p').show();
                $(subjectEl).closest('p').show();
                $(messageEl).closest('p').show();
                $(smsTextEl).closest('p').hide();
                $('option:gt('+recipientIndex+')',recipientEl).show();
                $('option:lt('+recipientIndex+')',recipientEl).show();
            }
        });

        function showAction(actionName){
            if(actionName!=0){
                $('#save-actions').show()
            }else{
                //$('#save-actions').hide()
                return false;
            }
            //check if tabs already initialized then destroy
            if(atholder.data('ui-tabs')){
                atholder.tabs('destroy');
            }

			atholder
				.empty()
				.append($.tmpl(triggersTabsTmpl, {triggers: actionTriggers, currentTrigger: actionName}))
				.tabs({
					create: function(event, ui) {
						$.each(actions, function(index, item) {
							var triggerHolderId = actionName + '-triegger-' + item.trigger;
							var triggerHolder   = $(event.target).find('#' + triggerHolderId);
                            var serviceName     = item.service;
							var action          = $.tmpl($('#triggerActionTemplate').template(), {triggers: actionTriggers, triggerName: item.trigger, index: item.id, triggerId: item.id, serviceName: serviceName});
                            if(item.service == 'sms') {
                                $('select[name*=template]', action).closest('p').hide();
                                $('input[name*=from]', action).closest('p').hide();
                                $('input[name*=subject]', action).closest('p').hide();
                                var recipientIndex = $('select[name*=recipient] option[value="customer"]', action).index();
                                $('select[name*=recipient] option:gt('+recipientIndex+')', action).hide();
                                $('select[name*=recipient] option:lt('+recipientIndex+')', action).hide();
                                $('textarea[name*=smsText]', action).val(item.message);

                            }else {
                                $('textarea[name*=message]', action).val(item.message);
                            }
                            $('select[name*=service]', action).val(item.service);
							$('select[name*=trigger]', action).val(item.trigger);
							$('select[name*=recipient]', action).val(item.recipient);
							$('select[name*=template]', action).val(item.template);
							$('input[name*=from]', action).val(item.from);
							$('input[name*=subject]', action).val(item.subject);
							$(triggerHolder).prepend(action);
						});
					}
				});
		}
    });
</script>