<?php $this->jQuery()->addJavascriptFile($this->websiteUrl.'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js');?>
<div class="seotoaster container">
    <?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array(
		'headerText' => 'Manage action e-mails ',
		'innerHeaderHtml' =>  $this->formSelect('actions', null, array('class' => 'fl-none grid_4'), $this->actionsOptions),
		'helpSection' => 'actionemails'
	)); ?>
    <div class="content-footer">
		<form action="javascript:;" method="post" id="ations-triggers-frm">
			<div class="grid_12" id="action-triggers">
				<p>
					<?php echo $this->translate('Please, select an event area above to view & edit currently configured related action emails or create new ones.'); ?>
				</p>
				<ul class="actions-list list-unstyled">
					<?php foreach($this->actionsOptions as $trigger):?>
						<?php if ($trigger != $this->translate('Select event area') ): ?>
							<li><span class="action-preview icon-action-emails" data-action="<?php echo str_replace(" ","-",strtolower($trigger));?>"></span><span class="action-name"><?php echo $trigger;?></span></li>
						<?php endif; ?>
					<?php endforeach;?>
				</ul>
			</div>
		</form>
	</div>
	<?php //echo $this->formSubmit('saveActions', 'Save changes', array('id' => 'save-actions')); ?>
    <div class="footer grid_12">
        <button id="save-actions" name="saveActions" type="submit" value="Save changes"><span class="icon-save"></span> Save changes</button>
    </div>

<script id="triggerActionTemplate" type="text/x-jquery-tmpl">
    {{each(key, trigger) triggers}}
        {{each(name, data) trigger}}
            {{if name == triggerName}}
                <fieldset class="background">
                    {{if triggerId}}
                        <?php echo $this->formHidden('actions[${index}][id]', '${triggerId}'); ?>
                        <?php echo $this->formHidden('actions[${index}][delete]', 'false'); ?>
                    {{/if}}
                    <span class="icon-close btn icon link error" style="float:right; cursor:pointer;"></span>
                    <?php echo $this->formHidden('actions[${index}][trigger]', '${name}'); ?>
                    <div class="trigger-title mt0px">
                        <?php echo $this->translate('When'); ?> <strong>${title}</strong><br />
                    </div>
					<div>
						<?php echo $this->formLabel('recipients', 'send an e-mail to', array('class' => 'grid_4 mt5px')); ?>
						<?php echo $this->formSelect('actions[${index}][recipient]', '${sendto}', array('class' => 'grid_8'), $this->recipients); ?>
					</div>
					<div>
						<?php echo $this->formLabel('mailTemplates', 'use template', array('class' => 'grid_4 mt5px')); ?>
						<?php echo $this->formSelect('actions[${index}][template]', null, array('class' => 'grid_8'), $this->mailTemplates); ?>
					</div>
					<?php //echo $this->formLabel('message', 'with message'); ?>
					<?php //echo $this->formTextarea('actions[${index}][message]', '${message}', array('rows' => 5, 'cols' => 30)); ?>
					<div>
						<?php echo $this->formLabel('from', 'from', array('class' => 'grid_4 mt5px')); ?>
						<?php echo $this->formText('actions[${index}][from]', '${from}', array('class' => 'grid_8')); ?>
					</div>
					<div>
						<?php echo $this->formLabel('subject', 'with subject', array('class' => 'grid_4 mt5px')); ?>
						<?php echo $this->formText('actions[${index}][subject]', '${subject}', array('class' => 'grid_8')); ?>
					</div>
                </fieldset>
            {{/if}}
        {{/each}}
    {{/each}}
</script>

<script type="text/x-jquery-tmpl" id="triggersTabs">
    <ul id="triggers-tabs-holder">
        {{each(key, trigger) triggers}}
            {{if key == currentTrigger }}
                {{each(name, data) trigger}}
                    <li><a href="#${key}-triegger-${name.replace(/\s+/g, '-')}">${title}</a></li>
                {{/each}}
            {{/if}}
        {{/each}}
    </ul>
    {{each(key, trigger) triggers}}
        {{if key == currentTrigger }}
            {{each(name, data) trigger}}
                <div id="${key}-triegger-${name.replace(/\s+/g, '-')}" class="tabs-contents">
                    <span class="new-trigger-action icon-plus-sign text-center" data-trigger-name="${name}">
						<?php //echo $this->translate('Add a recipient'); ?>
					</span>
                </div>
            {{/each}}
        {{/if}}
    {{/each}}
</script>

<script type="text/javascript">
    $(function() {
        $('#save-actions').hide();

        var triggersTabsTmpl  = $('#triggersTabs').template(),
            actionTriggers    = <?php echo json_encode($this->triggers); ?>,
            actions           = <?php echo json_encode($this->actions);?>,
            lastId            = 0,
            atholder          = $('#action-triggers');


        $(document).on('change', '#actions', function() {
			showAction($(this).val());
        }).on('click', '.actions-list li', function() {
			showAction($(this).find('.action-preview').data('action'));
        }).on('click', '.new-trigger-action', function(e) {
            e.preventDefault();
			console.log(e.target);
            var triggerName       = $(e.target).data('triggerName');
            var actionTriggerTmpl = $('#triggerActionTemplate').template();
            $(e.target).before($.tmpl(actionTriggerTmpl, {triggers: actionTriggers, triggerName: triggerName, index: (lastId++)}));
        }).on('click', '#save-actions', function(e) {
            $.ajax({
                url: '<?php echo $this->escape($this->url()); ?>',
                type: 'post',
                dataType: 'json',
                data: $('#ations-triggers-frm').serialize(),
                beforeSend: function() {
                    showSpinner();
                },
                success: function(response) {
                    hideSpinner();
                    showMessage(response.responseText);
                }
            });
        }).on('click', '.icon-close', function(){
            var id = $(this).closest('fieldset').find('input[name*=id]');
            if (id.length) {
                $(this).closest('fieldset').find('input[name*=delete]').val(true);
                $(this).closest('fieldset').hide();
            } else {
                $(this).closest('fieldset').remove();
            }
        });

		function showAction(actionName){
			if(actionName != 0) {
				$('#save-actions').show()
			} else {
				//$('#save-actions').hide()
				return false;
			}
			//check if tabs already initialized then destroy
			if(atholder.data('ui-tabs')) {
				atholder.tabs('destroy');
			}

			atholder
				.empty()
				.append($.tmpl(triggersTabsTmpl, {triggers: actionTriggers, currentTrigger: actionName}))
				.tabs({
					create: function(event, ui) {
						$.each(actions, function(index, item) {
							var triggerHolderId = actionName + '-triegger-' + item.trigger;
							var triggerHolder   = $(event.target).find('#' + triggerHolderId);
							var action          = $.tmpl($('#triggerActionTemplate').template(), {triggers: actionTriggers, triggerName: item.trigger, index: item.id, triggerId: item.id});
							$('select[name*=trigger]', action).val(item.trigger);
							$('select[name*=recipient]', action).val(item.recipient);
							$('select[name*=template]', action).val(item.template);
							$('textarea[name*=message]', action).val(item.message);
							$('input[name*=from]', action).val(item.from);
							$('input[name*=subject]', action).val(item.subject);
							$(triggerHolder).prepend(action);
						});
					}
				});
		}
    });
</script>