<?php $this->jQuery()->addJavascriptFile($this->websiteUrl.'system/js/external/jquery/plugins/tmpl/jquery.tmpl.min.js');?>
<div class="seotoaster container">
	<?php echo $this->partial('admin'.DIRECTORY_SEPARATOR.'_header.phtml', array(/*'headerText' => 'Manage config',*/ 'helpSection' => $this->helpSection)); ?>
	<form id="tabs" action="<?php echo $this->configForm->getAction(); ?>" method="<?php echo $this->configForm->getMethod();?>">
        <ul class="header">
            <li><a href="#general-config"><?php echo $this->translate('General');?></a></li>
            <li><a href="#email-config"><?php echo $this->translate('Email settings'); ?></a></li>
<!--				<li><a href="#action-triggers">--><?php //echo $this->translate('Action emails'); ?><!--</a></li>-->
            <?php if ($this->isSuperAdmin): ?>
                <li><a href="#security-config"><?php echo $this->translate('Admin access'); ?></a></li>
                <li><a href="#advaced-config"><?php echo $this->translate('Advanced'); ?></a></li>
                <li><a href="#securityForm-config"><?php echo $this->translate('Security'); ?></a></li>
            <?php endif; ?>
        </ul>
        <div id="general-config" class="content-small-footer">
            <?php echo $this->configForm->getElement('currentTheme');?>
            <div class="grid_6">
            <?php echo $this->configForm->getElement('language')->renderLabel(); ?>
            </div>
            <div class="grid_6">
            <?php echo $this->configForm->getElement('language')->renderViewHelper(); ?>
            </div>
            <div class="grid_6 mt10px">
            <?php echo $this->configForm->getElement('imgSmall')->renderLabel(); ?>
            </div>
            <div class="grid_6 mt10px">
            <?php echo $this->configForm->getElement('imgSmall')->renderViewHelper(); ?>
            </div>
            <div class="grid_6 mt10px">
            <?php echo $this->configForm->getElement('imgMedium')->renderLabel(); ?>
            </div>
            <div class="grid_6 mt10px">
            <?php echo $this->configForm->getElement('imgMedium')->renderViewHelper(); ?>
            </div>
            <div class="grid_6 mt10px">
            <?php echo $this->configForm->getElement('imgLarge')->renderLabel(); ?>
            </div>
            <div class="grid_6 mt10px">
            <?php echo $this->configForm->getElement('imgLarge')->renderViewHelper(); ?>
            </div>
            <div class="grid_6 mt10px">
            <?php echo $this->configForm->getElement('teaserSize')->renderLabel(); ?>
            </div>
            <div class="grid_6 mt10px">
            <?php echo $this->configForm->getElement('teaserSize')->renderViewHelper(); ?>
            </div>
            <div class="grid_6 mt10px">
                <?php echo $this->configForm->getElement('memPagesInMenu')->renderLabel(); ?>
            </div>
            <div class="grid_6 mt10px">
                <?php echo $this->configForm->getElement('memPagesInMenu')->renderViewHelper(); ?>
            </div>

            <?php echo $this->configForm->getElement('adminEmail');?>
            <?php echo $this->configForm->getElement('superadminLogin');?>
            <?php echo $this->configForm->getElement('superadminPassword');?>

        </div>
        <div id="email-config" class="content-small-footer">
            <div class="grid_3 mt10px">
            <?php echo $this->configForm->getElement('useSmtp')->renderLabel(); ?>
            </div>
            <div class="grid_9 mt10px">
            <?php echo $this->configForm->getElement('useSmtp')->renderViewHelper(); ?>
            </div>
            <div class="grid_6 mt10px">
                <?php echo $this->configForm->getElement('smtpHost')->renderLabel(); ?>
                <?php echo $this->configForm->getElement('smtpHost')->renderViewHelper(); ?>
            </div>
            <div class="grid_4 alpha mt10px">
                <?php echo $this->configForm->getElement('smtpPort')->renderLabel(); ?>
                <?php echo $this->configForm->getElement('smtpPort')->renderViewHelper(); ?>
            </div>
            <div class="grid_2 alpha mt10px">
                <?php echo $this->configForm->getElement('smtpSsl')->renderLabel(); ?>
                <?php echo $this->configForm->getElement('smtpSsl')->renderViewHelper(); ?>
            </div>
            <?php echo $this->configForm->getElement('smtpLogin'); ?>
            <?php echo $this->configForm->getElement('smtpPassword'); ?>
        </div>

<!--			<div id="action-triggers" class="clearfix h200" style="overflow-x: hidden; overflow-y: scroll;">-->
<!--				<div><button class="blue-btn" id="new-trigger-action">--><?php //echo $this->translate('Add'); ?><!--</button></div>-->
<!--			</div>-->
		<?php if ($this->isSuperAdmin): ?>
			<div id="security-config" class="content-small-footer">
				<?php echo $this->configForm->getElement('suLogin'); ?>
				<?php echo $this->configForm->getElement('suPassword'); ?>
			</div>
			<div id="advaced-config" class="content-small-footer">
				<div class="grid_4 omega mt10px"><?php echo $this->configForm->getElement('canonicalScheme')->renderLabel(); ?></div>
				<div class="grid_2 mt5px"><?php echo $this->configForm->getElement('canonicalScheme')->renderViewHelper(); ?></div>
				<label class="grid_6 alpha mt10px">://<?php echo parse_url($this->websiteUrl, PHP_URL_HOST); ?></label>
				<div class="cl-both grid_6 mt15px">
					<div class="grid_7 alpha">
						<?php echo $this->configForm->getElement('mediaServers')->renderLabel(); ?>
					</div>
					<div class="grid_5 omega">
						<?php echo $this->configForm->getElement('mediaServers')->renderViewHelper(); ?>
					</div>
					<div class="grid_12 mt10px alpha omega">
						<em>Speed up your site. Insert the following CNAME records into your DNS server:</em>
						<ul class="mt10px mb0px">
							<?php
							$host = parse_url($this->websiteUrl, PHP_URL_HOST);
							$host = str_replace('www.', '', $host);
							$medias = Zend_Registry::get('website');
							?>
							<?php foreach($medias['mediaServers'] as $media):?>
							<li class="mb0px"><?php echo $media.'.'.$host;?></li>
							<?php endforeach;?>
						</ul>
					</div>
				</div>
				<div class="grid_6 mt15px">
					<div class="grid_10 alpha">
						<?php echo $this->configForm->getElement('inlineEditor')->renderLabel(); ?>
					</div>
					<div class="grid_2 omega">
						<?php echo $this->configForm->getElement('inlineEditor')->renderViewHelper(); ?>
					</div>
					<div class="grid_12 alpha omega mt15px h150px wrap">
						<a href="<?php echo $this->websiteUrl;?>system/images/zonehighlighting.jpg" class="_lbox" style="cursor:help;">
							<img src="<?php echo $this->websiteUrl;?>system/images/zonehighlighting.jpg" class="h150" />
						</a>
					</div>
				</div>

			</div>
			<div id="securityForm-config" class="content-small-footer">
				<?php echo $this->configForm->getElement('recapthaPublicKey'); ?>
				<?php echo $this->configForm->getElement('recapthaPrivateKey'); ?>
				<div class="grid_12 mt15px">
					<a target="_blank" href="https://www.google.com/recaptcha/admin/create">
							<?php echo $this->translate('Get your own reCAPTCHA key here now.');?>
					</a>
				</div>
			</div>
		<?php endif; ?>
	</form>
    <div class="grid_12 footer"><?php echo $this->configForm->getElement('submit')->renderViewHelper();?></div>
</div>
<script type="text/javascript">
	$(function(){
		$('#tabs').tabs();
		var actionTriggerTmpl = $('#triggerActionTemplate').template(),
			actions = <?php echo json_encode($this->actions);?>,
			lastActionId = 0;

		<?php if (count($this->messages)) : ?>
		//$('#ajax_msg').html('<p><?php echo reset($this->messages); ?></p>').show();
		<?php endif; ?>
		$('#new-trigger-action').on('click', function(e){
			e.preventDefault();
			$('#action-triggers').append($.tmpl(actionTriggerTmpl, {index: lastActionId++}));
		});
		$('#action-triggers').on('click', '.trigger-action span.ui-icon', function(){
			var id = $(this).closest('fieldset').find('input[name*=id]');
			if (id.length) {
				$(this).closest('fieldset').find('input[name*=delete]').val(true);
				$(this).closest('fieldset').hide();
			} else {
				$(this).closest('fieldset').remove();
			}
		});
		$.each(actions, function(index, item){
			item.index = item.id;
			var action = $.tmpl(actionTriggerTmpl, item);
			$('select[name*=trigger]', action).val(item.trigger);
			$('select[name*=recipient]', action).val(item.recipient);
			$('select[name*=template]', action).val(item.template);
			$('textarea[name*=message]', action).val(item.message);
            $('input[name*=from]', action).val(item.from);
            $('input[name*=subject]', action).val(item.subject);
			$('#action-triggers').append(action);
			lastActionId = (lastActionId < item.id) &&  (item.id + 1);
		});
	});
</script>
<script id="triggerActionTemplate" type="text/x-jquery-tmpl">
	<fieldset class="trigger-action">
		{{if id}}
		<input type="hidden" name="actions[${index}][id]" value="${id}"/>
		<input type="hidden" name="actions[${index}][delete]" value="false"/>
		{{/if}}
		<span class="ui-icon ui-icon-closethick" style="float:right; cursor:pointer;"></span>
		When <?php echo $this->formSelect('actions[${index}][trigger]', null, array('id'=>false), $this->triggers);?> notify
		<?php echo $this->formSelect('actions[${index}][recipient]', null, array('id'=>false), $this->recipients);?>
		using template <?php echo $this->formSelect('actions[${index}][template]',null, array('id'=>false), $this->templates);?>
		with following message: <?php echo $this->formTextarea('actions[${index}][message]', null, array('id'=>false, 'rows'=>3)); ?>
        from: <?php echo $this->formText('actions[${index}][from]', null, array('id'=>false)); ?>
        with subject: <?php echo $this->formText('actions[${index}][subject]', null, array('id'=>false)); ?>
	</fieldset>
</script>