<form action="javascript:;" method="post" data-name="form" id="forms-widget-form" class="wmc-block">
    <div>
        <?php echo $this->formLabel('forms-newname', $this->translate('Form name'), array('class' => 'grid_5 alpha mt5px')); ?>
        <?php echo $this->formText('formsNewname', '', array('id' => 'forms-newname', 'class' => 'grid_7 alpha omega')); ?>
    </div>
    <div class="mt5px">
        <?php echo $this->formLabel('forms-existing', $this->translate('Select a form'), array('class' => 'grid_5 alpha mt5px')); ?>
        <?php echo $this->formSelect('formsExisting', null, array('id' => 'forms-existing', 'class' => 'grid_7 alpha omega')); ?>
    </div>
    <label class="mt10px">
        <span class="grid_5 alpha"><?php echo $this->translate('Use recaptcha'); ?></span>
        <?php echo $this->formCheckbox('formsCaptcha', null, array('id' => 'forms-captcha')); ?>
	</label>
    <?php echo $this->formSubmit('applyWidget', 'Apply', array('class' => 'apply-widget-forms')); ?>
</form>
<script type="text/javascript">
	$(function() {
		var formsSelect = $('#forms-existing');
		$.post($('#website_url').val() + 'backend/backend_form/loadforms/', function(response) {
			if(response.formsNames.length) {
				$.each(response.formsNames, function(val) {
					formsSelect.append($('<option></option>').attr({value: response.formsNames[val]}).text(response.formsNames[val]));
				});
			}
			formsSelect.prepend('<option value="0" selected="selected"><?php echo $this->translate('Select a form'); ?></option>')
		});

		$(document).on('click', '.apply-widget-forms', function() {
			var widgetForm = $(this).closest('form');
			var widgetHtml = '{$' + widgetForm.data('name');
			if($('#forms-newname').val().trim() != '') {
				widgetHtml += ':' + $('#forms-newname').val()
			} else if($('#forms-existing').val() != 0) {
				widgetHtml += ':' + $('#forms-existing').val();
			} else {
                $('#forms-existing').addClass('error');
                $('#forms-newname').addClass('error');
				widgetHtml = '';
			}
			if(widgetHtml != '') {
				widgetHtml += ($('#forms-captcha').prop('checked') ? ':recaptcha}' : '}');
				$('textarea.tinymce').tinymce().execCommand('mceInsertContent',false, widgetHtml);
			}
		});
	});
</script>