<form action="javascript:;" method="post" data-name="form" id="forms-widget-form" class="wmc-block">
    <p>
        <?php echo $this->formLabel('forms-newname', $this->translate('Form name'), array('class' => 'grid_5 alpha')); ?>
        <?php echo $this->formText('formsNewname', '', array('id' => 'forms-newname', 'class' => 'grid_7 alpha omega small')); ?>
    </p>
    <p class="mt5px">
        <?php echo $this->formLabel('forms-existing', $this->translate('Select a form'), array('class' => 'grid_5 alpha')); ?>
        <?php echo $this->formSelect('formsExisting', null, array('id' => 'forms-existing', 'class' => 'grid_7 alpha omega small')); ?>
    </p>
    <ul class="mt5px column_2">
        <li>
            <label class="pointer">
                <span class="alpha"><?php echo $this->translate('Grecaptcha'); ?></span>
                <?php echo $this->formCheckbox('formsgRecaptcha', null, array('id' => 'forms-grecaptcha', 'checked' => 'true')); ?>
            </label>
        </li>
        <li>
            <label class="pointer">
                <span class="alpha"><?php echo $this->translate('Recaptcha'); ?></span>
                <?php echo $this->formCheckbox('formsCaptcha', null, array('id' => 'forms-captcha')); ?>
            </label>
        </li>
    </ul>
    <p class="mt5px">
        <label class="pointer hide">
            <span class="grid_5 alpha"><?php echo $this->translate('Recaptcha style'); ?></span>
            <?php echo $this->formSelect('formsCaptchastyle', null, array('id' => 'form-captcha-style', 'class' => 'grid_7 alpha omega small'),
                array('custom' => 'custom', 'red' => 'red', 'white' => 'white'));?>
        </label>
    </p>
    <p class="mt5px">
        <?php echo $this->formLabel('forms-submitlabel', $this->translate('Submit label'), array('class' => 'grid_5 alpha')); ?>
        <?php echo $this->formText('formsSubmitlabel', '', array('id' => 'forms-submit-label', 'class' => 'grid_7 alpha omega small')); ?>
    </p>
    <?php echo $this->formSubmit('applyWidget', 'Apply', array('class' => 'apply-widget-forms btn small')); ?>
</form>
<script type="text/javascript">
	$(function() {
		var formsSelect = $('#forms-existing');
		$.post($('#website_url').val() + 'backend/backend_form/loadforms/', function(response) {
			if(response.formsNames.length) {
				$.each(response.formsNames, function(val) {
					formsSelect.append($('<option></option>').attr({value: response.formsNames[val]}).text(response.formsNames[val]));
				});
			}
			formsSelect.prepend('<option value="0" selected="selected"><?php echo $this->translate('Select a form'); ?></option>')
		});

        $("#forms-captcha").change(function(){
            if(this.checked){
                $("#form-captcha-style").closest('label.pointer').fadeIn('slow');
                $('#forms-grecaptcha').prop('checked', false);
            } else {
                $("#form-captcha-style").closest('label.pointer').fadeOut('slow');
            }
        });

        $('#forms-grecaptcha').change(function() {
            if ($(this).is(':checked')) {
                $('#forms-captcha').prop('checked', false).change();
            }
        });

		$(document).on('click', '.apply-widget-forms', function() {
            var WFORM_NAME_LIMIT_CHARS = 64;
            var recaptchaStyle = "",
                nameLength = $('#forms-newname').val().length;
            var widgetForm = $(this).closest('form');
			var widgetHtml = '{$' + widgetForm.data('name');

            if(nameLength > WFORM_NAME_LIMIT_CHARS){
                return  showMessage("<?php echo $this->translate('Form name is limited to 64 chars!')?>", false, 3000);
            }
			if($('#forms-newname').val().trim() != '') {
				widgetHtml += ':' + $('#forms-newname').val()
			} else if($('#forms-existing').val() != 0) {
				widgetHtml += ':' + $('#forms-existing').val();
			} else {
                $('#forms-existing').addClass('error');
                $('#forms-newname').addClass('error');
				widgetHtml = '';
			}

                recaptchaStyle = $("#form-captcha-style option:selected").text();

			if(widgetHtml != '') {
                if($('#forms-captcha').prop('checked')){
                    widgetHtml += ':recaptcha:' + recaptchaStyle ;
                }

                if($('#forms-grecaptcha').prop('checked')){
                    widgetHtml += ':grecaptcha';
                }

                if($("#forms-submit-label").val().length != 0){
                    widgetHtml += ":" + $("#forms-submit-label").val() + "}";
                } else{
                    widgetHtml += "}";
                }
				tinymce.activeEditor.execCommand('mceInsertContent',false, widgetHtml);
			}
		});
	});
</script>