<?php if(($this->userRole == Tools_Security_Acl::ROLE_GUEST) || $this->userRole == Tools_Security_Acl::ROLE_SUPERADMIN): ?>
    <?php if (!empty($this->messages)) : ?>
        <ul id="messages" class="ui-state-error w350">
            <?php foreach ($this->messages as $message) : ?>
                <?php if(is_array($message) && isset($message['email'])): ?>
                    <li><?php echo $message['email']; ?></li>
                <?php elseif(is_string($message)):?>
                    <li><?php echo $message; ?></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
    <?php
    $this->loginForm->setAction($this->websiteUrl . 'backend/login/index/singintype/member/');
    $this->loginForm->getElement('secureToken')->setValue($this->secureToken);
    echo $this->loginForm;
    ?>
    <a href="javascript:;" title="<?php echo $this->translate('Forgot password?'); ?>" class="forgot-password"> <?php echo $this->translate('Forgot password?'); ?></a>
    <div class="retrieveFormBlock" style="display: none">
        <?php echo $this->retrieveForm;?>
        <a href="javascript:;" title="<?php echo $this->translate('I remembered my password'); ?>" id="remember-password"> <?php echo $this->translate('I remembered my password'); ?></a>
    </div>
<?php endif; ?>
<script type="text/javascript">
    $(function() {
        $(document).on('click', '#remember-password', function() {
            $('.retrieveFormBlock').hide();
            $('#login-form').show();
            $('.forgot-password').show();
        });

        $(document).on('click', '.forgot-password', function() {
            $('.retrieveFormBlock').show();
            $('#login-form').hide();
            $('.forgot-password').hide();
        });
    });
</script>