<div class="featureapage" id="fp-<?php echo $this->page->getId(); ?>">
	<?php if($this->useImage): ?>
		<a class="page-teaser-image" title="<?php echo $this->page->getH1(); ?>" href="<?php echo $this->websiteUrl . $this->page->getUrl(); ?>">
			<img src="<?php echo $this->escape(Tools_Page_Tools::getPreviewPath($this->page->getId(), true, (($this->useImage == 'img') ? false : true))); ?>" alt="<?php echo $this->page->getH1(); ?>" />
		</a>
	<?php endif; ?>
    <a title="<?php echo $this->page->getH1(); ?>" href="<?php echo $this->websiteUrl . $this->page->getUrl(); ?>" class="page-title">
		<?php echo $this->page->getNavName(); ?>
	</a>
	<?php if ($this->descLength): ?>
	<p><?php echo Tools_Text_Tools::cutText($this->page->getTeaserText(), $this->descLength); ?></p>
	<?php endif; ?>
</div>
