<form class="wmc-block" action="javascript:;" method="post">
	<div class="wmc-row">
		<label class="wmc-label" for="featured-item-type"><?php echo $this->translate('Type'); ?></label>
		<select class="wmc-input w100" id="featured-item-type">
			<option value="<?php echo Widgets_Featured_Featured::FEATURED_TYPE_AREA ;?>"><?php echo Widgets_Featured_Featured::FEATURED_TYPE_AREA ;?></option>
			<option value="<?php echo Widgets_Featured_Featured::FEATURED_TYPE_PAGE ;?>"><?php echo Widgets_Featured_Featured::FEATURED_TYPE_PAGE ;?></option>
		</select>
	</div>
	<div class="wmc-row">
		<label class="wmc-label" id="fa-item-lbl" for="featured-area-item"><?php echo $this->translate('Pick an area'); ?></label>
		<select class="wmc-input w100" id="featured-area-item"></select>
	</div>
	<div class="wmc-row">
		<label class="wmc-label" id="fa-maxres-lbl" for="featured-item-maxres"><?php echo $this->translate('Max. result'); ?></label>
		<input class="wmc-input w100" type="text" id="featured-item-maxres" value="<?php echo Widgets_Featured_Featured::AREA_PAGES_COUNT; ?>" />
	</div>
	<div class="wmc-row">
		<label class="wmc-label" for="featured-item-maxres"><?php echo $this->translate('Max. chars.'); ?></label>
		<input class="wmc-input w100" type="text" id="featured-item-maxch" value="<?php echo Widgets_Featured_Featured::AREA_DESC_LENGTH; ?>" />
	</div>
	<div class="wmc-row">
		<label class="wmc-label" for="featured-item-img"><?php echo $this->translate('Use image'); ?></label>
<!--		<input  class="wmc-input w100"type="checkbox" id="featured-item-img" />-->
		<input type="radio" class="featured-item-img" name="useImg" value="imgc"/><span style="font-size: 10px;">Croped</span>
		<input type="radio" class="featured-item-img" name="useImg" value="img"/><span style="font-size: 10px;">Not croped</span>
	</div>
	<div class="wmc-row">
		<label class="wmc-label" for="featured-item-rand"><?php echo $this->translate('Random'); ?></label>
		<input class="wmc-input w100" type="checkbox" id="featured-item-rand" />
	</div>

	<input class="wmc-submit" type="submit" id="fa-done" name="done" value="Done" />
</form>
<script type="text/javascript">
	$(function() {
		loadData($('#featured-item-type').val());

		$('#featured-item-type').change(function() {
			$('#fa-item-lbl').toggleClass('wmc-lable wmc-label-flat').text(($(this).val() == 'page') ? 'Pick a page' : 'Pick an area');
			$('#featured-area-item').toggleClass('wmc-input wmc-input-flat');
			loadData($(this).val());
		});

		$('#fa-done').click(function() {
			var featuredWidget = '{$featured:' + $('#featured-item-type').val() + ':' + $('#featured-area-item option:selected').val() + ':' +
									$('#featured-item-maxres').val() + ':' + $('#featured-item-maxch').val() +
									(($('.featured-item-img:checked').val()) ? (':' + $('.featured-item-img:checked').val()) : '') +
									(($('#featured-item-rand').attr('checked')) ? ':random' : '') + '}';



			$('textarea.tinymce').tinymce().execCommand('mceInsertContent',false, featuredWidget);
		})
	});


	function loadData(type) {
		var websiteUrl = $('#website_url').val();
		var url = websiteUrl + 'backend/backend_featured/loadfalist/render/0/namesonly/1';
		if(type == 'page') {
			url = websiteUrl + 'backend/backend_page/listpages/';
		}
		$.getJSON(url, function(response) {
			$('#featured-area-item').find('option').remove().end();
			$.each(response.responseData, function() {
				var optVal  = (type == 'page') ? this.id : this.name;
				var optText = (type == 'page') ? this.h1 : this.name;
				$('#featured-area-item')
					.append($('<option></option>').attr({
						value: optVal
					})
					.text(optText));
			})
		})
	}
</script>