<?php if(!empty($this->users)): ?>
	<?php foreach($this->users as $user): ?>
		<tr class="user-row block wrap">
			<td class="user-row-item grid_3 alpha omega"><?php echo $user->getEmail(); ?></td>
			<td class="user-row-item grid_2 alpha omega"><?php echo $user->getFullName(); ?></td>
			<td class="user-row-item grid_2 alpha omega"><?php echo $this->translate(ucfirst($user->getRoleId())); ?></td>
			<td class="user-row-item grid_2 alpha omega"><?php echo intval($user->getLastLogin()) ? date('Y-m-d', strtotime($user->getLastLogin())) : '-'; ?></td>
			<td class="user-row-item grid_2 alpha omega"><?php echo ($user->getIpaddress()) ? $user->getIpaddress() : '-'; ?></td>
			<td class="user-row-item grid_1 alpha omega text-center">
				<a data-url="<?php echo $this->toasterLink('user', 'load', '', null, true); ?>" data-eid="<?php echo $user->getId(); ?>" href="javascript:;" class="_tedit icon-pencil"></a>
				<a data-url="<?php echo $this->toasterLink('user', 'delete', '', null, true); ?>" data-eid="<?php echo $user->getId(); ?>" data-callback="userCallback" class="del-user _tdelete error icon-remove" href="javascript:;"></a>
			</td>
		</tr>
	<?php endforeach; ?>
<?php endif; ?>