<div class="seotoaster container_12 h590 rounded3px">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array('headerText' => 'Manage users')); ?>
	<div id="add-user" class="grid_12" style="position: relative;">
		<form id="frm-user" action="<?php echo $this->url(); ?>" method="post" class="_fajax" data-callback="userCallback">
			<div class="grid_6">
				<?php echo $this->userForm->getElement('email'); ?>
			</div>
			<div class="grid_6">
				<?php echo $this->userForm->getElement('fullName'); ?>
			</div>
			<div class="grid_6">
				<?php echo $this->userForm->getElement('password'); ?>
			</div>
			<div class="grid_6">
				<?php echo $this->userForm->getElement('roleId'); ?>
			</div>
			<?php echo $this->userForm->getElement('saveUser'); ?>
			<?php echo $this->userForm->getElement('id'); ?>
		</form>
        <a style="position: absolute; left: 220px; bottom:0px; font-size: 12px;" href="javascript:;" id="export-users"><?php echo $this->translate('export as csv file'); ?></a>
	</div>
	<table class="sortable grid_12" id="users-list">
		<thead class="grid_12">
			<tr class="grid_12">
				<th class="grid_2"><?php echo $this->translate('E-mail'); ?></th>
				<th class="grid_3"><?php echo $this->translate('Full name'); ?></th>
				<th class="grid_2"><?php echo $this->translate('Role'); ?></th>
				<th class="grid_2"><?php echo $this->translate('Last login'); ?></th>
				<th class="grid_2"><?php echo $this->translate('Ip address'); ?></th>
				<th class="grid_1"><?php echo $this->translate('Actions'); ?></th>
			</tr>
		</thead>
		<tbody class="grid_12">
		</tbody>
	</table>
</div>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/external/jquery/plugins/DataTables/jquery.dataTables.min.js'); ?>
<?php $this->jQuery()->addJavascriptFile($this->websiteUrl . 'system/js/internal/users.js'); ?>