<div class="seotoaster container">
	<?php echo $this->partial('admin' . DIRECTORY_SEPARATOR . '_header.phtml', array(
		'headerText'      => $this->translate('Manage users'),
        'helpSection'     => $this->helpSection,
        'innerHeaderHtml' => '<form id="expusrs" action="' . $this->websiteUrl . 'backend/backend_user/export/" method="post"><a href="javascript:;" id="export-users">[ '. $this->translate('export as csv file') . ' ]</a></form>'

    )); ?>
	<div class="content-footer grid_12">
		<div id="add-user" class="show-right">
			<div class="header">
				<?php echo $this->translate('Add new user'); ?>
				<div class="closebutton">
					<a class="hide-block icon-chevron-right" href="javascript:;" title="Close"></a>
				</div>
			</div>
			<form id="frm-user" action="<?php echo $this->url(); ?>" method="post" class="_fajax grid_12 mt15px" data-callback="userCallback">
				<div class="grid_7 omega">
					<?php echo $this->userForm->getElement('fullName'); ?>
				</div>
				<div class="grid_5 mt0px">
					<?php echo $this->userForm->getElement('roleId'); ?>
				</div>
				<div class="grid_12">
					<?php echo $this->userForm->getElement('email'); ?>
				</div>
				<div class="grid_12">
					<?php echo $this->userForm->getElement('password'); ?>
				</div>
				<div class="grid_12">
					<?php echo $this->userForm->getElement('gplusProfile'); ?>
				</div>
				<?php echo $this->userForm->getElement('saveUser'); ?>
				<?php echo $this->userForm->getElement('id'); ?>
			</form>
		</div>
        <form class="grid_6 alpha search" name="search" action="<?php echo $this->websiteUrl; ?>backend/backend_user/manage/by/email/order/<?php echo $this->order; ?>" method="get">
            <input class="grid_9 alpha omega" type="text" name="key" value="<?php echo $this->key ?>">
            <button class="btn grid_3 alpha omega mt0px icon-search" type="submit"><?php echo $this->translate('Search'); ?></button>
        </form>
		<?php echo '<a id="add-user-link" class="btn fl-right icon-user-add" href="javascript:;"> ' . $this->translate('Add new user') . '</a>' ?>
        <span class="clearfix"></span>
		<table id="users-list" class="table-striped mt20px">
			<thead>
				<tr>
					<th>
                        <?php echo $this->translate('E-mail'); ?>
                        <a class="icon-sort" href="<?php echo $this->websiteUrl; ?>backend/backend_user/manage/by/email/order/<?php echo $this->orderParam; ?>"></a>
                    </th>
					<th>
                        <?php echo $this->translate('Full name'); ?>
                        <a class="icon-sort" href="<?php echo $this->websiteUrl; ?>backend/backend_user/manage/by/full_name/order/<?php echo $this->orderParam; ?>"></a>
                    </th>
                    <th>
                        <?php echo $this->translate('Role'); ?>
                        <a class="icon-sort" href="<?php echo $this->websiteUrl; ?>backend/backend_user/manage/by/role_id/order/<?php echo $this->orderParam; ?>"></a>
                    </th>
                    <th>
                        <?php echo $this->translate('Last login'); ?>
                        <a class="icon-sort" href="<?php echo $this->websiteUrl; ?>backend/backend_user/manage/by/last_login/order/<?php echo $this->orderParam; ?>"></a>
                    </th>
                    <th>
                        <?php echo $this->translate('Ip address'); ?>
                        <a class="icon-sort" href="<?php echo $this->websiteUrl; ?>backend/backend_user/manage/by/ipaddress/order/<?php echo $this->orderParam; ?>"></a>
                    </th>
                    <th class="text-center"><?php echo $this->translate('Actions'); ?></th>
				</tr>
			</thead>
			<tbody>
            <?php if(!empty($this->users)): ?>
                <?php foreach($this->users as $user): ?>
                    <tr class="user-row">
                        <td class="user-row-item"><?php echo $user['email']; ?></td>
                        <td class="user-row-item"><?php echo $user['full_name']; ?></td>
                        <td class="user-row-item"><?php echo $this->translate(ucfirst($user['role_id'])); ?></td>
                        <td class="user-row-item"><?php echo intval($user['last_login']) ? date('Y-m-d', strtotime($user['last_login'])) : '-'; ?></td>
                        <td class="user-row-item"><?php echo ($user['ipaddress']) ? $user['ipaddress'] : '-'; ?></td>
                        <td class="user-row-item text-center">
                            <a data-url="<?php echo $this->toasterLink('user', 'load', '', null, true); ?>" data-eid="<?php echo $user['id']; ?>" href="javascript:;" class="_tedit icon-pencil"></a>
                            <a data-url="<?php echo $this->toasterLink('user', 'delete', '', null, true); ?>" data-eid="<?php echo $user['id']; ?>" data-callback="userCallback" class="del-user _tdelete error icon-remove" href="javascript:;"></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php endif; ?>
			</tbody>
		</table>
	</div>
    <div class="footer grid_12 text-right">
        <?php echo $this->pager; ?>
    </div>
</div>
<script type="text/javascript">
	$(function() {
        $(document).on('click', '#add-user-link, ._tedit',function(){
            $('#add-user').show("slide", { direction: "right"});
        });
        $('#export-users').click(function() {
            $('#expusrs').submit();
        });
        $('a[href*="by/<?php echo $this->by ;?>/order/asc"].icon-sort').addClass('icon-sort-down');
        $('a[href*="by/<?php echo $this->by ;?>/order/desc"].icon-sort').addClass('icon-sort-up');
	});
    function userCallback() {
        location.reload();
    }
</script>