<?php if(isset($this->feed) && !empty ($this->feed)): ?>

<ul class="listxrss">
	<?php foreach ($this->feed as $entry): ?>
		<li>
			<a href="<?php echo $entry['link']; ?>" target="_blank" title="<?php echo $entry['title']; ?>" class="page-title"><?php echo $entry['title']; ?></a>
            <span><?php echo date("d M Y", $entry['pubDate']->getTimestamp()); ?></span>
			<?php if($this->useImage && $entry['image']): ?>
				<a title="<?php echo $entry['title']; ?>" href="<?php echo $entry['link']; ?>" target="_blank" title="<?php echo $entry['title']; ?>"><?php echo $entry['image']; ?></a>
			<?php endif; ?>
			<p><?php echo $entry['description']; ?></p>
		</li>
	<?php endforeach; ?>
</ul>

<?php endif; ?>
