<?php if(isset($this->feed) && !empty ($this->feed)): ?>

<ul class="listxrss">
	<?php foreach ($this->feed as $entry): ?>
		<a href="<?php echo $entry['link']; ?>" title="<?php echo $entry['title']; ?>"><?php echo $entry['title']; ?></a>
		<a href="<?php echo $entry['link']; ?>" title="<?php echo $entry['title']; ?>"><?php echo $entry['image']; ?></a>
		<span><?php echo date("d M Y", strtotime($entry['pubDate'])); ?></span>
		<p><?php echo $entry['description']; ?></p>
	<?php endforeach; ?>
</ul>

<?php endif; ?>
