<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/uithemes/seotoasterui/seotoasterui.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/grid.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css'); ?>
<?php echo $this->headLink(); ?>

<div style="font-family: Arial; padding: 5px; font-size: 0.8em;">
	<a style="color: #c6c6c6;" href="<?php echo $this->websiteUrl; ?>" title="<?php echo $this->translate('Are you lost?'); ?>">&larr; <?php echo $this->translate('back to'); ?>&nbsp;<?php echo $_SERVER['SERVER_NAME']; ?></a>
</div>

<?php if (count($this->messages)) : ?>
	<ul id="messages" class="ui-state-error w350" style="margin: 0px auto; list-style-type: none; padding: 15px 0px; text-align: center;">
		<?php foreach ($this->messages as $message) : ?>
			<li><?php echo $this->escape($message); ?></li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>

<div class="seotoaster container_12 w400 h300 rounded8px" style="box-shadow: 0px 0px 30px #c8c8c8; margin: 10% auto 0px auto; padding-bottom: 5px;">
	<div class="header" style="border-radius: 5px; -moz-border-radius: 5px; -webkit-border-radius: 5px;">
		<h1><?php echo $this->translate('Login'); ?></h1>
	</div>

	<div class="textcentered mb10px">
		<?php if(isset($this->flagsFiles) && is_array($this->flagsFiles) && !empty($this->flagsFiles)): ?>
			<?php foreach($this->flagsFiles as $flagFileName => $flagFilePath): ?>
				<a title="<?php echo ($this->translate('Select ') . $flagFileName . $this->translate(' language'));?> " href="javascript:;"><img alt="<?php echo $flagFileName; ?>" class="lang-select" id="<?php echo $flagFileName; ?>" src="<?php echo $this->websiteUrl . 'system/images/flags/' . $flagFilePath; ?>" border="0" /></a>&nbsp;
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
    <div class="clear"></div>
	<div class="grid_12">
		<form action="<?php echo $this->url(); ?>" method="post" >
			<fieldset>
				<legend><?php echo $this->translate('Welcome Back'); ?></legend>
					<dl class="Zend_Form">
						<?php
							echo $this->loginForm->email;
							echo $this->loginForm->password;
						?>
					</dl>
			</fieldset>
			<?php echo $this->loginForm->submit; ?>
		</form>
	</div>
	<div class="clear"></div>
</div>

<script type="text/javascript" charset="utf-8">
<?php $this->jQuery()->onLoadCaptureStart(); ?>
	$('.lang-select').live('click', function() {
		var language = $(this).attr('id');
		$.post( $('#website_url').val() + 'language', {lng: language}, function() {
			window.location.reload();
		})
	})
<?php $this->jQuery()->onLoadCaptureEnd(); ?>
</script>
