<?php
    $this->headMeta()->setCharset('UTF-8');
    $this->headLink()
        ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster.css')
        ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster-ui.css')
        ->prependStylesheet($this->websiteUrl . 'system/css/reset.css');
?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>

<div>
	<a href="<?php echo $this->websiteUrl; ?>" title="<?php echo $this->translate('Are you lost?'); ?>">&larr; <?php echo $this->translate('back to'); ?>&nbsp;<?php echo $_SERVER['SERVER_NAME']; ?></a>
</div>

<div class="seotoaster container go-form">
	<div class="header">
        <img alt="<?php echo $this->currentLanguage; ?>" class="lang-select" data-lng="" src="<?php echo $this->websiteUrl . "system/images/flags/" . $this->currentLanguage . ".png" ; ?>" border="0" />
        <?php echo $this->translate('Welcome Back'); ?>
        <div class="fl-right">
            <select class="lang-select">
                <option class="flag-button"  value="English"><?php echo $this->translate('Select your language'); ?>
                <?php if(isset($this->languages) && is_array($this->languages) && !empty($this->languages)): ?>
                    <?php foreach($this->languages as $lang): ?>
                        <option data-lng="<?php echo $lang['name'];?>" value="<?php echo $lang['name'];?>">
                            <?php echo $lang['language'];?>
                        </option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
        </div>
	</div>

	<form class="grid_12 mt15px pl2 pr2" action="<?php echo $this->url(); ?>" method="post" >
		<p><?php
                echo $this->loginForm->getElement('email')->renderLabel();
			    echo $this->loginForm->getElement('email')->renderViewHelper();
            ?>
        </p>
        <p><?php
                echo $this->loginForm->getElement('password')->renderLabel();
                echo $this->loginForm->getElement('password')->renderViewHelper();
		    ?>
        </p>
        <div class="footer">
            <?php echo $this->loginForm->getElement('submit')->renderViewHelper();?>
            <a id="forgot-password" href="<?php echo $this->websiteUrl; ?>login/retrieve/"><?php echo $this->translate('Forgot password?'); ?></a>
        </div>
        <input type="hidden" name="secureToken" value="<?php echo $this->secureToken;?>"/>
	</form>
</div>

<script type="text/javascript" charset="utf-8">
<?php $this->jQuery()->onLoadCaptureStart(); ?>
	$('.lang-select').on('change', function(e) {
        e.preventDefault();
        console.log($(this).find(':selected').data('lng'));
		$.post( $('#website_url').val() + 'language/', {lng: $(this).find(':selected').data('lng')}, function() {
			window.location.reload();
		})
	});
    showTooltip('.notvalid', 'error', 'right');
    $('.notvalid').on('keyup', function(){
        $(this).tooltip('destroy').removeClass('notvalid').removeAttr('title');
        $(this).unbind();
    })
<?php $this->jQuery()->onLoadCaptureEnd(); ?>
</script>
