<?php
    $this->headMeta()->setCharset('UTF-8');
    $this->headMeta()->setName('viewport', 'width=device-width, initial-scale=1, user-scalable=no');
    $this->headLink()
        ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster.css')
        ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster-ui.css')
        ->prependStylesheet($this->websiteUrl . 'system/css/reset.css')
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400,600,700');

?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<div class="wrap-seotoaster-form-login">

    <form class="card-ui seotoaster-form-login" action="<?php echo $this->url(); ?>" method="post">
        <div class="card-title">
            <span><?php echo $this->translate('Sign In'); ?></span>
            <div class="box-language">
                <img alt="<?php echo $this->currentLanguage; ?>" data-lng="" src="<?php echo $this->websiteUrl . "system/images/flags/" . $this->currentLanguage . ".png" ; ?>" border="0" width="32" height="24" />
                <select class="lang-select">
                    <option class="flag-button"  value="English"><?php echo $this->translate('Select your language'); ?>
                    <?php if(isset($this->languages) && is_array($this->languages) && !empty($this->languages)): ?>
                        <?php foreach($this->languages as $lang): ?>
                            <option data-lng="<?php echo $lang['name'];?>" value="<?php echo $lang['name'];?>">
                                <?php echo $lang['language'];?>
                            </option>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </select>
            </div>
        </div>

        <?php if (!empty(($this->messages)) && is_array($this->messages)) : ?>
            <div class="card-messages error">
                <ul id="messages" class="list-unstyled">
                    <?php $this->messages = array_pop($this->messages);?>
                    <?php foreach ($this->messages as $message) : ?>
                        <li><?php echo $this->escape($message); ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
        <?php endif; ?>

        <div class="card-content">
            <div class="field-line"><?php
                echo $this->loginForm->getElement('email')->renderLabel();
                echo $this->loginForm->getElement('email')->renderViewHelper();
                ?>
            </div>
            <div class="field-line"><?php
                echo $this->loginForm->getElement('password')->renderLabel();
                echo $this->loginForm->getElement('password')->renderViewHelper();
                ?>
            </div>
        </div>

        <div class="btn-area">
            <a id="forgot-password" href="<?php echo $this->websiteUrl; ?>login/retrieve/"><?php echo $this->translate('Forgot password?'); ?></a>
            <?php echo $this->loginForm->getElement('submit')->renderViewHelper();?>
        </div>
        <input type="hidden" name="secureToken" value="<?php echo $this->secureToken;?>"/>
    </form>

</div>

<script type="text/javascript" charset="utf-8">
<?php $this->jQuery()->onLoadCaptureStart(); ?>
	$('.lang-select').on('change', function(e) {
        e.preventDefault();
        console.log($(this).find(':selected').data('lng'));
		$.post( $('#website_url').val() + 'language/', {lng: $(this).find(':selected').data('lng')}, function() {
			window.location.reload();
		})
	});
    showTooltip('.notvalid', 'error', 'right');
    $('.notvalid').on('keyup', function(){
        $(this).tooltip('destroy').removeClass('notvalid').removeAttr('title');
        $(this).unbind();
    })
<?php $this->jQuery()->onLoadCaptureEnd(); ?>
</script>
