<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/uithemes/seotoasterui/seotoasterui.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/grid.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css'); ?>
<?php echo $this->headLink(); ?>

<div>
	<a href="<?php echo $this->websiteUrl; ?>" title="<?php echo $this->translate('Are you lost?'); ?>">&larr; <?php echo $this->translate('back to'); ?>&nbsp;<?php echo $_SERVER['SERVER_NAME']; ?></a>
</div>

<?php if (count($this->messages)) : ?>
	<ul id="messages" class="container alert alert-error text-center w350px">
		<?php foreach ($this->messages as $message) : ?>
			<li>
				<span class="icon-exclamation-sign icon16" style="margin-top: -3px;"></span>
				<?php echo $this->escape($message); ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>

<div class="seotoaster container go-form">
	<div class="header bold">
		<?php echo $this->translate('Retrieve password'); ?>
	</div>
	<div class="grid_12">
		<?php
			$this->form->setAction($this->escape($this->url()));
			echo $this->form;
		?>
		<a id="back-to-login" href="<?php echo $this->websiteUrl; ?>go"><?php echo $this->translate('I remembered my password'); ?></a>
	</div>
</div>