<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/uithemes/seotoasterui/seotoasterui.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/grid.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css'); ?>
<?php echo $this->headLink(); ?>

<div style="font-family: Arial; padding: 5px; font-size: 0.8em;">
	<a style="color: #c6c6c6;" href="<?php echo $this->websiteUrl; ?>" title="<?php echo $this->translate('Are you lost?'); ?>">&larr; <?php echo $this->translate('back to'); ?>&nbsp;<?php echo $_SERVER['SERVER_NAME']; ?></a>
</div>

<?php if (count($this->messages)) : ?>
	<ul id="messages" class="ui-state-error w350" style="margin: 0px auto; list-style-type: none; padding: 15px 0px; text-align: center;">
		<?php foreach ($this->messages as $message) : ?>
			<li><?php echo $this->escape($message); ?></li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>

<div class="seotoaster container_12 w400 h230 rounded3px" style="box-shadow: 0px 0px 20px #bbb; margin: 10% auto 2% auto;">
	<div class="header">
		<?php echo $this->translate('Reset password'); ?>
	</div>
	<div class="clear"></div>
	<div class="grid_12">
		<?php
			$this->form->setAction($this->escape($this->url()));
			echo $this->form;
		?>
	</div>
</div>
