<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/seotoaster-ui.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css'); ?>
<?php echo $this->headLink(); ?>

<div>
	<a href="<?php echo $this->websiteUrl; ?>" title="<?php echo $this->translate('Are you lost?'); ?>">&larr; <?php echo $this->translate('back to'); ?>&nbsp;<?php echo $_SERVER['SERVER_NAME']; ?></a>
</div>

<?php if (count($this->messages)) : ?>
	<ul id="messages" class="ui-state-error w350">
		<?php foreach ($this->messages as $message) : ?>
			<li><?php echo $this->escape($message); ?></li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
<div class="seotoaster container go-form">
	<div class="header">
		<?php if ($this->newUser) : ?>
			<?php echo $this->translate('Create your password'); ?>
		<?php else: ?>
			<?php echo $this->translate('Reset password'); ?>
		<?php endif ?>
	</div>
	<div class="clear"></div>
	<div class="grid_12">
		<?php
		$this->form->setAction($this->escape($this->url()));
		echo $this->form;
		?>
	</div>
</div>
