<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/reset.css'); ?>
<?php $this->headLink()->appendStylesheet($this->websiteUrl . 'system/css/seotoaster.css'); ?>
<?php echo $this->headLink(); ?>

<div>
	<a href="<?php echo $this->websiteUrl; ?>" title="<?php echo $this->translate('Are you lost?'); ?>">&larr; <?php echo $this->translate('back to'); ?>&nbsp;<?php echo $_SERVER['SERVER_NAME']; ?></a>
</div>



<div class="seotoaster container go-form">
	<div class="header text-bold">
		<?php echo $this->translate('Retrieve password'); ?>
	</div>
	<div class="grid_12">
		<?php
			$this->form->setAction($this->escape($this->url()));
			echo $this->form;
		?>
		<a id="back-to-login" href="<?php echo $this->websiteUrl; ?>go"><?php echo $this->translate('I remembered my password'); ?></a>
	</div>
</div>
<script type="text/javascript" charset="utf-8">
    <?php $this->jQuery()->onLoadCaptureStart(); ?>
        showTooltip('.notvalid', 'error', 'right');
        $('.notvalid').on('keyup', function(){
            $(this).tooltip('destroy').removeClass('notvalid').removeAttr('title');
            $(this).unbind();
        })
        <?php if(isset($this->retrieveSuccessMessage)):?>
            showMessage('<?php echo $this->retrieveSuccessMessage;?>', false, 5000);
        <?php endif;?>
    <?php $this->jQuery()->onLoadCaptureEnd(); ?>
</script>
