<?php
$this->headMeta()->setCharset('UTF-8');
$this->headLink()
    ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster.css')
    ->prependStylesheet($this->websiteUrl . 'system/css/seotoaster-ui.css')
    ->prependStylesheet($this->websiteUrl . 'system/css/reset.css')
    ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400,600,700');

?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>




<div class="wrap-seotoaster-form-pass-reset">
    <div class="card-ui seotoaster-form-pass-reset">
        <div class="card-title">
            <?php if ($this->newUser) : ?>
                <span><?php echo $this->translate('Create your password'); ?></span>
            <?php else: ?>
                <span><?php echo $this->translate('Reset password'); ?></span>
            <?php endif ?>
        </div>

        <?php if (count($this->messages)) : ?>
        <div class="card-messages error">
                <ul id="messages" class="list-unstyled">
                    <?php foreach ($this->messages as $message) : ?>
                        <li><?php echo $this->escape($message); ?></li>
                    <?php endforeach; ?>
                </ul>
        </div>
        <?php endif; ?>
        <div class="card-content">
            <?php $this->form->setAction($this->escape($this->url()));?>
            <div class="field-line">
                <?php
                echo $this->form->getElement('password')->renderLabel();
                echo $this->form->getElement('password')->renderViewHelper();
                ?>
            </div>
            <div class="field-line">
                <?php
                echo $this->form->getElement('confirmPassword')->renderLabel();
                echo $this->form->getElement('confirmPassword')->renderViewHelper();
                ?>
            </div>
        </div>
        <div class="btn-area">
            <?php echo $this->form->getElement('reset')->renderViewHelper();?>
        </div>
    </div>
</div>
