<label class="fl-left pointer">
	<input type="checkbox" id="published" <?php echo ($this->published) ? 'checked="checked"' : ''; ?> name="published" value="<?php echo ($this->published) ? '1' : '0'; ?>" />
	<?php echo $this->translate($this->publishedLabel);?>
</label>
<span id="publish-later" class="fl-left hide ml3">&nbsp;&nbsp;<?php echo $this->translate($this->publishAtLabel);?>:&nbsp;&nbsp;
	<?php echo $this->datePicker(
		'datepicker',
		((intval($this->publishAt)) ? date('M j, Y', strtotime($this->publishAt)) : ''),
		array(
			'defaultDate' => '',
			'onSelect'    => (isset($this->onselectCallback)) ? new Zend_Json_Expr($this->onselectCallback) : ''
		),
		array(
			'style' => 'width:100px;',
            'class' => 'small'
		));
	?>
</span>
<script type="text/javascript">
	$(function() {
		pubunpub();
		$(document).on('click', '#published', pubunpub);
	});
	function pubunpub() {
		$('#publish-later').css({display : (($('#published').prop('checked')) ? 'none' : 'block')});
	}
</script>