<div class="header" style="overflow:hidden;">
	<div class="closebutton">
		<span class="help"><?php echo $this->translate('Help'); ?></span>
		<span class="close"><?php echo $this->translate('Close'); ?></span>
	</div>

<!--	<label>-->
		<?php echo (isset($this->headerText) ? $this->translate($this->headerText) : ''); ?>
		<?php if(isset($this->innerHeaderHtml) && $this->innerHeaderHtml): ?>
			<?php echo $this->innerHeaderHtml; ?>
		<?php endif; ?>
<!--	</label>-->
</div>