<?php $this->inlineScript()
           ->appendFile($this->websiteUrl . 'system/js/internal/adminPanelInit.min.js');
?>
<div class="seotoaster-panel aside s">
    <header>
        <span class="ticon-toaster logo-icon"></span>
    </header>
    <ul class="section-list">
        <li class="section">
            <a href="#" class="section-btn ticon-copy2"></a>
            <div class="section-wrap">
                <div class="section-box">
                    <span class="section-title"><?php echo $this->translate('Website editing'); ?></span>
                    <?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PAGES)): ?>
                        <ul class="category-list">
                            <li class="item title"><?php echo $this->translate('PAGES'); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_page', 'page', $this->translate('Edit page properties'), array('id' => $this->pageData['id']), false, array('width' => '960', 'height' => '560')); ?></li>
                            <?php if($this->newsPage !== true): ?>
                                <?php if($this->websiteMainPage != $this->pageData['url']): ?>
                                    <li class="item"><a href="javascript:;" data-cid="<?php echo $this->pageData['parentId']; ?>" id="del-this-page" title="<?php echo $this->translate('Delete this page'); ?>"><?php echo $this->translate('Delete this page'); ?></a></li>
                                    <input type="hidden" id="del-page-id" value="<?php echo $this->pageData['id']; ?>" />
                                <?php endif; ?>
                            <?php endif; ?>
                            <li class="item"><?php echo $this->toasterLink('backend_page', 'page', $this->translate('Create a page'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_page', 'organize', $this->translate('Organize pages'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                            <li class="item"><a href="javascript:;" id="edit404" title="Edit 404 page"><?php echo $this->translate('Edit 404 page'); ?></a></li>
                            <li class="item"><?php echo $this->toasterLink('backend_page', 'draft', $this->translate('Draft') . ' (' .Tools_Page_Tools::getDraftPagesCount() . ')', false, false, array('width' => 480, 'height' => 560)); ?></li>
                        </ul>
                    <?php endif; ?>
                    <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_MEDIA)): ?>
                        <ul class="category-list">
                            <li class="item title"><?php echo $this->translate('MEDIA'); ?></li>
                            <li class="item">
                                <?php echo $this->toasterLink('backend_media', 'uploadthings', $this->translate('Upload things'), false, false, array('width' => '480', 'height' => '560')); ?>
                            </li>
                            <li class="item">
                                <?php echo $this->toasterLink('backend_media', 'removethings', $this->translate('Remove things'), false, false, array('width' => '480', 'height' => '560')); ?>
                            </li>
                        </ul>
                    <?php endif; ?>
                    <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_LAYOUT)):?>
                        <ul class="category-list">
                            <li class="item title"><?php echo $this->translate('LAYOUT'); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_theme', 'template', $this->translate('Add a new template'), array('pid' => $this->pageData['id']), false, array('width' => '960', 'height' => '560')); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_theme', 'template', $this->translate('Edit this template'), array('id'=>$this->pageData['templateId'], 'pid'=>$this->pageData['id']), false, array('width' => '960', 'height' => '560')); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_theme', 'editcss', $this->translate('Edit CSS files'), false, false, array('width' => '480', 'height' => '560')); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_theme', 'editjs', $this->translate('Edit JS files'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_theme', 'themes', $this->translate('Organize themes'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                        </ul>
                    <?php endif; ?>
                </div>
            </div>
        </li>
        <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_SEO)): ?>
            <li class="section">
                <a href="#" class="section-btn ticon-stats-up"></a>
                <div class="section-wrap">
                    <div class="section-box">
                        <span class="section-title"><?php echo $this->translate('Marketing & SEO configs'); ?></span>
                        <ul class="category-list">
                            <li class="item title"><?php echo $this->translate('SEO'); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_seo', 'robots', $this->translate('Edit robots.txt'), false, false, array('width' => '360', 'height' => '350')); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_seo', 'redirects', $this->translate('Add / Edit 301'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_seo', 'deeplinks', $this->translate('Deeplinks'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_seo', 'sculpting', 'Sculpting', false, false, array('width' => '480', 'height' => '560')); ?></li>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endif; ?>
        <?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PLUGINS_MENU)): ?>
            <li class="section">
                <a href="#" class="section-btn ticon-puzzle"></a>
                <div class="section-wrap">
                    <div class="section-box">
                        <span class="section-title"><?php echo $this->translate('Plugins manager'); ?></span>
                        <ul class="category-list">
                            <li class="item"><?php echo $this->toasterLink('backend_plugin', 'plugin', $this->translate('Manage plugins'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                        </ul>

                        <ul class="category-list">
                            <!-- output plugins additional menus -->
                            <?php if(isset($this->additionalMenu) && !empty($this->additionalMenu)): ?>
                            <?php foreach ($this->additionalMenu as $pluginName => $pluginAdditionalMenu): ?>
                                <?php if(!$pluginAdditionalMenu['title'] || !isset($pluginAdditionalMenu['items']) || !sizeof($pluginAdditionalMenu['items'])) {continue;} ?>
                                <li class="item title plugin-cpanel-menu plugin-<?php echo strtolower($pluginAdditionalMenu['title']);?>"><?php echo $this->translate($pluginAdditionalMenu['title']); ?></li>
                                <?php foreach ($pluginAdditionalMenu['items'] as $title => $menuItem): ?>
                                    <?php if(isset($pluginAdditionalMenu['values'][$title])):?>
                                        <?php echo $this->toasterAdminpanelItem(str_replace('{value}', $this->translate($pluginAdditionalMenu['values'][$title]), $menuItem)); ?>
                                    <?php else:?>
                                        <?php echo $this->toasterAdminpanelItem($menuItem); ?>
                                    <?php endif;?>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                    </div>
                </div>
            </li>
        <?php endif; ?>
        <li class="section">
            <a href="#" class="section-btn ticon-basket"></a>
            <div class="section-wrap">
                <div class="section-box">
                    <span class="section-title"><?php echo $this->translate('Store configuration'); ?></span>
                    <ul class="category-list">
                        <li class="item title"><?php echo $this->translate('Store'); ?></li>
                        <li class="item"><a href="#">Add/Edit product</a></li>
                        <li class="item"><a href="#">Manage brand logos</a></li>
                        <li class="item"><a href="#">Manage zones</a></li>
                        <li class="item"><a href="#">Manage locations</a></li>
                        <li class="item"><a href="#">Tax configuration</a></li>
                        <li class="item"><a href="#">Shipping configuration</a></li>
                        <li class="item"><a href="#">Merchandising</a></li>
                        <li class="item"><a href="#">Configuration</a></li>
                        <li class="item"><a href="#">Import orders</a></li>
                        <li class="item"><a href="#">Go to Dashboard</a></li>
                    </ul>
                </div>
            </div>
        </li>
        <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_CONFIG)):?>
            <li class="section">
                <a href="#" class="section-btn ticon-cog2"></a>
                <div class="section-wrap">
                    <div class="section-box">
                        <span class="section-title"><?php echo $this->translate('Website configs'); ?></span>
                        <ul class="category-list">
                            <li class="item title"><?php echo $this->translate('OTHER'); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_config', 'config', $this->translate('Website configs'), false, false, array('width' => '720', 'height' => '360')); ?></li>
                            <li class="item"><?php echo $this->toasterLink('backend_config', 'actionmails', $this->translate('E-mails & SMS actions'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                            <?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_USERS)): ?>
                                <li class="item"><?php echo $this->toasterLink('backend_user', 'manage', $this->translate('Manage users'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </li>
        <?php endif; ?>
        <li class="section under_empty">
            <a href="#" class="section-btn ticon-bell"></a>
            <div class="section-wrap">
                <div class="section-box notifications-box">
                    <span class="section-title"><?php echo $this->translate('Notification'); ?></span>
                    <div class="notif-message info notif-new-version hide">
                        <p><?php echo $this->translate('Good news! Detected a new version. You can upgrade to it'); ?></p>
                        <?php echo $this->toasterLink('backend_update', 'index', $this->translate('Update now'), false, false, array('width' => '480', 'height' => '560')); ?>
                    </div>
                </div>
            </div>
        </li>
        <li class="section">
            <a class="section-btn ticon-loop" href="javascript:;" id="cleancache" title="<?php echo $this->translate('CLEAN CACHE'); ?>"></a>
        </li>
        <li class="section">
            <a href="<?php echo $this->websiteUrl; ?>logout/" class="section-btn ticon-exit" title="<?php echo $this->translate('LOGOUT'); ?>"></a>
        </li>
    </ul>
    <span class="show-hide ticon-arrow-up"></span>
</div>