<?php $this->inlineScript()
           ->appendFile($this->websiteUrl . 'system/js/internal/adminPanelInit.min.js'); ?>
<div id="seotoaster-cpanel" class="seotoaster">
    <?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_CONTENT)): ?>
        <div id="showhide"><a href="javascript:;"><?php echo $this->translate('Collapse menu'); ?></a></div>
        <div id="seotoaster-logowrap">
            <?php $this->placeholder(Tools_System_Tools::PLACEHOLDER_SYSTEM_VERSION)->prepend($this->translate('CMS version ') . Tools_System_Tools::getSystemVersion()); ?>
            <div id="system-version"><?php echo $this->placeholder(Tools_System_Tools::PLACEHOLDER_SYSTEM_VERSION); ?></div>
            <img class="reset-element" width="170" height="180" src="<?php echo $this->placeholder('logoSource'); ?>" />
        </div>
    <?php endif;?>
	<?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PLUGINS)): ?>
	<ul id="cpanelul">
		<?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PAGES)): ?>
		<li>
			<a href="javascript:;"><span><?php echo $this->translate('PAGES'); ?></span></a>
			<ul>
				<li class="cpanelsubtitle"><?php echo $this->translate('This page'); ?></li>
				<li><?php echo $this->toasterLink('backend_page', 'page', $this->translate('Edit page properties'), array('id' => $this->pageData['id']), false, array('width' => '960', 'height' => '560')); ?></li>
                <?php if($this->newsPage !== true): ?>
					<?php if($this->websiteMainPage != $this->pageData['url']): ?>
						<li><a href="javascript:;" data-cid="<?php echo $this->pageData['parentId']; ?>" id="del-this-page" title="<?php echo $this->translate('Delete this page'); ?>"><?php echo $this->translate('Delete this page'); ?></a></li>
						<input type="hidden" id="del-page-id" value="<?php echo $this->pageData['id']; ?>" />
					<?php endif; ?>
				<?php endif; ?>
				<li class="cpanelsubtitle"><?php echo $this->translate('Other pages'); ?></li>
				<li><?php echo $this->toasterLink('backend_page', 'page', $this->translate('Create a page'), false, false, array('width' => '960', 'height' => '560')); ?></li>
				<li><?php echo $this->toasterLink('backend_page', 'organize', $this->translate('Organize pages'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                <li><a href="javascript:;" id="edit404" title="Edit 404 page"><?php echo $this->translate('Edit 404 page'); ?></a></li>
				<li><?php echo $this->toasterLink('backend_page', 'draft', $this->translate('Draft') . ' (' .Tools_Page_Tools::getDraftPagesCount() . ')', false, false, array('width' => 480, 'height' => 560)); ?></li>
			<?php if(isset($this->additionalMenu) && isset($this->additionalMenu['PAGES']) && isset($this->additionalMenu['PAGES']['items'])): ?>
			<?php foreach($this->additionalMenu['PAGES']['items'] as $item):?>
				<?php echo $this->toasterAdminpanelItem($item); ?>
			<?php endforeach;?>
			<?php unset($this->additionalMenu['PAGES']);?>
			<?php endif;?>
			</ul>
		</li>
		<?php endif; ?>
		<?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_MEDIA)): ?>
		<li>
			<a href="javascript:;"><span><?php echo $this->translate('MEDIA'); ?></span></a>
			<ul>
				<li><?php echo $this->toasterLink('backend_media', 'uploadthings', $this->translate('Upload things'), false, false, array('width' => '480', 'height' => '560')); ?></li>
				<li><?php echo $this->toasterLink('backend_media', 'removethings', $this->translate('Remove things'), false, false, array('width' => '480', 'height' => '560')); ?></li>
			<?php if(isset($this->additionalMenu) && isset($this->additionalMenu['MEDIA']) && isset($this->additionalMenu['MEDIA']['items'])): ?>
			<?php foreach($this->additionalMenu['MEDIA']['items'] as $item):?>
				<?php echo $this->toasterAdminpanelItem($item); ?>
			<?php endforeach;?>
			<?php unset($this->additionalMenu['MEDIA']);?>
			<?php endif;?>
			</ul>
		</li>
		<?php endif; ?>
		<?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_SEO)): ?>
		<li>
			<a href="javascript:;"><span><?php echo $this->translate('SEO'); ?></span></a>
			<ul>
				<li><?php echo $this->toasterLink('backend_seo', 'robots', $this->translate('Edit robots.txt'), false, false, array('width' => '360', 'height' => '350')); ?></li>
				<li><?php echo $this->toasterLink('backend_seo', 'redirects', $this->translate('Add / Edit 301'), false, false, array('width' => '960', 'height' => '560')); ?></li>
				<li class="cpanelsubtitle"><?php echo $this->translate('Link strategy'); ?></li>
				<li><?php echo $this->toasterLink('backend_seo', 'deeplinks', $this->translate('Deeplinks'), false, false, array('width' => '960', 'height' => '560')); ?></li>
				<li><?php echo $this->toasterLink('backend_seo', 'sculpting', 'Sculpting', false, false, array('width' => '480', 'height' => '560')); ?></li>
			<?php if(isset($this->additionalMenu) && isset($this->additionalMenu['SEO']) && isset($this->additionalMenu['SEO']['items'])): ?>
			<?php foreach($this->additionalMenu['SEO']['items'] as $item):?>
				<?php echo $this->toasterAdminpanelItem($item); ?>
			<?php endforeach;?>
			<?php unset($this->additionalMenu['SEO']);?>
			<?php endif;?>
			</ul>
		</li>
		<?php endif;?>
		<?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_LAYOUT)):?>
		<li>
			<a href="javascript:;"><span><?php echo $this->translate('LAYOUT'); ?></span></a>
			<ul>
				<li><?php echo $this->toasterLink('backend_theme', 'template', $this->translate('Add template'), array('pid' => $this->pageData['id']), false, array('width' => '960', 'height' => '560')); ?></li>
				<li><?php echo $this->toasterLink('backend_theme', 'template', $this->translate('Edit this template'), array('id'=>$this->pageData['templateId'], 'pid'=>$this->pageData['id']), false, array('width' => '960', 'height' => '560')); ?></li>
				<li><?php echo $this->toasterLink('backend_theme', 'editcss', $this->translate('Edit CSS'), false, false, array('width' => '480', 'height' => '560')); ?></li>
				<li><?php echo $this->toasterLink('backend_theme', 'editjs', $this->translate('Edit JS'), false, false, array('width' => '960', 'height' => '560')); ?></li>
				<li><?php echo $this->toasterLink('backend_theme', 'themes', $this->translate('Themes'), false, false, array('width' => '960', 'height' => '560')); ?></li>
				<li><a href="javascript:;" data-external-url="<?php echo Tools_System_Tools::REMOTE_TOASTER_URL; ?>" id="widgets-shortcodes" title="Widgets & Tokens"><?php echo $this->translate('Widgets & Shortcodes'); ?></a></li>
			<?php if(isset($this->additionalMenu) && isset($this->additionalMenu['LAYOUT']) && isset($this->additionalMenu['LAYOUT']['items'])): ?>
			<?php foreach($this->additionalMenu['LAYOUT']['items'] as $item):?>
				<?php echo $this->toasterAdminpanelItem($item); ?>
			<?php endforeach;?>
			<?php unset($this->additionalMenu['LAYOUT']);?>
			<?php endif;?>
			</ul>
		</li>
		<?php endif;?>
		<?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_CONFIG)):?>
		<li>
			<a href="javascript:;"><span><?php echo $this->translate('OTHER'); ?></span></a>
			<ul>
				<li><?php echo $this->toasterLink('backend_config', 'config', $this->translate('Manage config'), false, false, array('width' => '720', 'height' => '360')); ?></li>
                <li><?php echo $this->toasterLink('backend_config', 'actionmails', $this->translate('Action e-mails & SMS'), false, false, array('width' => '960', 'height' => '560')); ?></li>
				<?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_USERS)): ?>
					<li><?php echo $this->toasterLink('backend_user', 'manage', $this->translate('Manage users'), false, false, array('width' => '960', 'height' => '560')); ?></li>
				<?php endif; ?>
                <li><?php echo $this->toasterLink('backend_plugin', 'plugin', $this->translate('Plugins'), false, false, array('width' => '960', 'height' => '560')); ?></li>
                <li><?php echo $this->toasterLink('backend_update', 'index', $this->translate('Update'), false, false, array('width' => '480', 'height' => '560')); ?></li>
			<?php if(isset($this->additionalMenu) && isset($this->additionalMenu['OTHER']) && isset($this->additionalMenu['OTHER']['items'])): ?>
			<?php foreach($this->additionalMenu['OTHER']['items'] as $item):?>
				<?php echo $this->toasterAdminpanelItem($item); ?>
			<?php endforeach;?>
			<?php unset($this->additionalMenu['OTHER']);?>
			<?php endif;?>
			</ul>
		</li>
		<?php endif;?>
        <?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PLUGINS_MENU)): ?>
            <!-- output plugins additional menus -->
            <?php if(isset($this->additionalMenu) && !empty($this->additionalMenu)): ?>
                <?php foreach ($this->additionalMenu as $pluginName => $pluginAdditionalMenu): ?>
                    <?php if(!$pluginAdditionalMenu['title'] || !isset($pluginAdditionalMenu['items']) || !sizeof($pluginAdditionalMenu['items'])) {continue;} ?>
                    <li class="plugin-cpanel-menu plugin-<?php echo strtolower($pluginAdditionalMenu['title']);?>">
                        <a href="javascript:;"><span><?php echo $this->translate($pluginAdditionalMenu['title']); ?></span></a>
                        <ul>
                            <?php foreach ($pluginAdditionalMenu['items'] as $title => $menuItem): ?>
                                <?php if(isset($pluginAdditionalMenu['values'][$title])):?>
                                    <?php echo $this->toasterAdminpanelItem(str_replace('{value}', $this->translate($pluginAdditionalMenu['values'][$title]), $menuItem)); ?>
                                <?php else:?>
                                    <?php echo $this->toasterAdminpanelItem($menuItem); ?>
                                <?php endif;?>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
            <!-- /output plugins additional menus -->
        <?php endif; ?>
	</ul>
	<?php endif; ?>
    <?php if(Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_CONTENT)): ?>
        <ul class="menu-links">
            <li>
                <a href="javascript:;" id="cleancache"><?php echo $this->translate('CLEAN CACHE'); ?></a>
            </li>
            <li>
                <a class="logout" href="<?php echo $this->websiteUrl; ?>logout/"><?php echo $this->translate('LOGOUT'); ?></a>
             </li>
        </ul>
        <span id="edit404-errorMsg" style="display: none">
        <?php
        echo $this->translate("Sorry, but you don't have a custom - 404 not found - page yet. Click %1\$s to create a 404 page using the appropriate option found under the \"Settings\" section",$this->toasterLink('backend_page', 'page', $this->translate('here'), false, false, array('width' => '960', 'height' => '560')));
        ?>
        </span>
    <?php else:?>
        <a class="logout" href="<?php echo $this->websiteUrl; ?>logout/"><?php echo $this->translate('LOGOUT'); ?></a>
    <?php endif; ?>

</div>
