<?php $this->inlineScript()
    ->appendFile($this->websiteUrl . 'system/js/external/polyfill/polyfill.min.js', null, array('conditional' => 'lte IE 9')) // classList and addEventListener
    ->appendFile($this->websiteUrl . 'system/js/internal/adminPanelInit.min.js', null, array('async' => 'true'));
?>
<div class="seotoaster-panel aside p-show">
    <div class="logo-wrap">
        <span class="_i-logo logo-icon tooltip-admin-panel"
              title="<?php $this->placeholder(Tools_System_Tools::PLACEHOLDER_SYSTEM_VERSION)->prepend($this->translate('CMS version ') . Tools_System_Tools::getSystemVersion()); ?><?php echo $this->placeholder(Tools_System_Tools::PLACEHOLDER_SYSTEM_VERSION); ?>"></span>
    </div>
    <ul class="section-list">
        <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PLUGINS)): ?>
            <li class="section">
                <a href="#" class="section-btn _i-editing"></a>

                <div class="section-wrap">
                    <div class="section-box">
                        <span class="section-title"><?php echo $this->translate('Website editing'); ?></span>
                        <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_PAGES)): ?>
                            <ul class="category-list">
                                <li class="item title"><?php echo $this->translate('PAGES'); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_page', 'page',
                                        $this->translate('Edit page properties'), array('id' => $this->pageData['id']),
                                        false, array('width' => '960', 'height' => '560')); ?></li>
                                <?php if ($this->newsPage !== true): ?>
                                    <?php if ($this->websiteMainPage != $this->pageData['url']): ?>
                                        <li class="item"><a href="javascript:;"
                                                            data-cid="<?php echo $this->pageData['parentId']; ?>"
                                                            id="del-this-page"
                                                            class="error"
                                                            title="<?php echo $this->translate('Delete this page'); ?>"><?php echo $this->translate('Delete this page'); ?></a>
                                        </li>
                                        <input type="hidden" id="del-page-id"
                                               value="<?php echo $this->pageData['id']; ?>"/>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <li class="item"><?php echo $this->toasterLink('backend_page', 'page',
                                        $this->translate('Create a page'), false, false,
                                        array('width' => '960', 'height' => '560')); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_page', 'organize',
                                        $this->translate('Organize pages'), false, false,
                                        array('width' => '960', 'height' => '560')); ?></li>
                                <li class="item"><a href="javascript:;" id="edit404"
                                                    title="Edit 404 page"><?php echo $this->translate('Edit 404 page'); ?></a>
                                </li>
                                <li class="item"><?php echo $this->toasterLink('backend_page', 'draft',
                                        $this->translate('Draft') . ' (' . Tools_Page_Tools::getDraftPagesCount() . ')',
                                        false, false, array('width' => 480, 'height' => 560)); ?></li>
                                <?php if (isset($this->additionalMenu) && isset($this->additionalMenu['PAGES'])): ?>
                                    <?php foreach ($this->additionalMenu['PAGES'] as $categoryName => $category): ?>
                                        <?php if ($categoryName !== 'DEFAULT') : ?>
                                            <li class="item title"><?php echo $categoryName; ?></li>
                                        <?php endif; ?>
                                        <?php foreach ($category as $pluginName => $plugin): ?>
                                            <?php foreach ($plugin['items'] as $index => $item): ?>
                                                <?php if (isset($this->additionalMenu['PAGES'][$categoryName][$pluginName]['values'][$index])): ?>
                                                    <?php echo $this->toasterAdminpanelItem(str_replace('{value}',
                                                        $this->translate($this->additionalMenu['PAGES'][$categoryName][$pluginName]['values'][$index]),
                                                        $item)); ?>
                                                <?php else: ?>
                                                    <?php echo $this->toasterAdminpanelItem($item); ?>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </ul>
                        <?php endif; ?>
                        <?php unset($this->additionalMenu['PAGES']); ?>
                        <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_MEDIA)): ?>
                            <ul class="category-list">
                                <li class="item title"><?php echo $this->translate('MEDIA'); ?></li>
                                <li class="item">
                                    <?php echo $this->toasterLink('backend_media', 'uploadthings',
                                        $this->translate('Upload things'), false, false,
                                        array('width' => '480', 'height' => '560')); ?>
                                </li>
                                <li class="item">
                                    <?php echo $this->toasterLink('backend_media', 'removethings',
                                        $this->translate('Remove things'), false, false,
                                        array('width' => '480', 'height' => '560')); ?>
                                </li>
                                <?php if (isset($this->additionalMenu) && isset($this->additionalMenu['MEDIA'])): ?>
                                    <?php foreach ($this->additionalMenu['MEDIA'] as $categoryName => $category): ?>
                                        <?php if ($categoryName !== 'DEFAULT') : ?>
                                            <li class="item title"><?php echo $categoryName; ?></li>
                                        <?php endif; ?>
                                        <?php foreach ($category as $pluginName => $plugin): ?>
                                            <?php foreach ($plugin['items'] as $index => $item): ?>
                                                <?php if (isset($this->additionalMenu['MEDIA'][$categoryName][$pluginName]['values'][$index])): ?>
                                                    <?php echo $this->toasterAdminpanelItem(str_replace('{value}',
                                                        $this->translate($this->additionalMenu['MEDIA'][$categoryName][$pluginName]['values'][$index]),
                                                        $item)); ?>
                                                <?php else: ?>
                                                    <?php echo $this->toasterAdminpanelItem($item); ?>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </ul>
                        <?php endif; ?>
                        <?php unset($this->additionalMenu['MEDIA']); ?>
                        <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_LAYOUT)): ?>
                            <ul class="category-list">
                                <li class="item title"><?php echo $this->translate('LAYOUT'); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_theme', 'template',
                                        $this->translate('Add a new template'), array('pid' => $this->pageData['id']),
                                        false, array('width' => '960', 'height' => '560')); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_theme', 'template',
                                        $this->translate('Edit this template'),
                                        array('id' => $this->pageData['templateId'], 'pid' => $this->pageData['id']),
                                        false,
                                        array('width' => '960', 'height' => '560')); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_theme', 'editcss',
                                        $this->translate('Edit CSS files'), false, false,
                                        array('width' => '480', 'height' => '560')); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_theme', 'editjs',
                                        $this->translate('Edit JS files'), false, false,
                                        array('width' => '960', 'height' => '560')); ?></li>
                                <?php if (isset($this->additionalMenu) && isset($this->additionalMenu['LAYOUT'])): ?>
                                    <?php foreach ($this->additionalMenu['LAYOUT'] as $categoryName => $category): ?>
                                        <?php if ($categoryName !== 'DEFAULT') : ?>
                                            <li class="item title"><?php echo $categoryName; ?></li>
                                        <?php endif; ?>
                                        <?php foreach ($category as $pluginName => $plugin): ?>
                                            <?php foreach ($plugin['items'] as $index => $item): ?>
                                                <?php if (isset($this->additionalMenu['LAYOUT'][$categoryName][$pluginName]['values'][$index])): ?>
                                                    <?php echo $this->toasterAdminpanelItem(str_replace('{value}',
                                                        $this->translate($this->additionalMenu['LAYOUT'][$categoryName][$pluginName]['values'][$index]),
                                                        $item)); ?>
                                                <?php else: ?>
                                                    <?php echo $this->toasterAdminpanelItem($item); ?>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </ul>
                        <?php endif; ?>
                        <?php unset($this->additionalMenu['LAYOUT']); ?>
                        <!-- start section: EDITING -->
                        <?php if (isset($this->additionalMenu) && isset($this->additionalMenu['EDITING'])): ?>
                            <?php foreach ($this->additionalMenu['EDITING'] as $categoryName => $category): ?>
                                <ul class="category-list">
                                <?php if ($categoryName !== 'DEFAULT') : ?>
                                    <li class="item title"><?php echo $categoryName; ?></li>
                                <?php endif; ?>
                                <?php foreach ($category as $pluginName => $plugin): ?>
                                    <?php foreach ($plugin['items'] as $index => $item): ?>
                                        <?php if (isset($this->additionalMenu['EDITING'][$categoryName][$pluginName]['values'][$index])): ?>
                                            <?php echo $this->toasterAdminpanelItem(str_replace('{value}',
                                                    $this->translate($this->additionalMenu['EDITING'][$categoryName][$pluginName]['values'][$index]),
                                                    $item)); ?>
                                        <?php else: ?>
                                            <?php echo $this->toasterAdminpanelItem($item); ?>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                <?php endforeach; ?>
                                </ul>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <?php unset($this->additionalMenu['EDITING']); ?>
                    </div>
                </div>
            </li>
            <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_SEO)): ?>
                <li class="section">
                    <a href="#" class="section-btn _i-marketing-seo"></a>

                    <div class="section-wrap">
                        <div class="section-box">
                            <span
                                class="section-title"><?php echo $this->translate('Marketing & SEO configs'); ?></span>
                            <ul class="category-list">
                                <li class="item title"><?php echo $this->translate('SEO'); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_seo', 'robots',
                                        $this->translate('Edit robots.txt'), false, false,
                                        array('width' => '360', 'height' => '350')); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_seo', 'redirects',
                                        $this->translate('Add / Edit 301'), false, false,
                                        array('width' => '960', 'height' => '560')); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_seo', 'deeplinks',
                                        $this->translate('Deeplinks'), false, false,
                                        array('width' => '960', 'height' => '560')); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_seo', 'sculpting', 'Sculpting',
                                        false, false, array('width' => '480', 'height' => '560')); ?></li>
                                <?php if (isset($this->additionalMenu) && isset($this->additionalMenu['SEO'])): ?>
                                    <?php foreach ($this->additionalMenu['SEO'] as $categoryName => $category): ?>
                                        <?php if ($categoryName !== 'DEFAULT') : ?>
                                            <li class="item title"><?php echo $categoryName; ?></li>
                                        <?php endif ?>
                                        <?php foreach ($category as $pluginName => $plugin): ?>
                                            <?php foreach ($plugin['items'] as $index => $item): ?>
                                                <?php if (isset($this->additionalMenu['SEO'][$categoryName][$pluginName]['values'][$index])): ?>
                                                    <?php echo $this->toasterAdminpanelItem(str_replace('{value}',
                                                        $this->translate($this->additionalMenu['SEO'][$categoryName][$pluginName]['values'][$index]),
                                                        $item)); ?>
                                                <?php else: ?>
                                                    <?php echo $this->toasterAdminpanelItem($item); ?>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </ul>
                            <!-- start section: MARKETINGSEO -->
                            <?php if (isset($this->additionalMenu) && isset($this->additionalMenu['MARKETINGSEO'])): ?>
                                <?php foreach ($this->additionalMenu['MARKETINGSEO'] as $categoryName => $category): ?>
                                    <ul class="category-list">
                                        <?php if ($categoryName !== 'DEFAULT') : ?>
                                            <li class="item title"><?php echo $categoryName; ?></li>
                                        <?php endif; ?>
                                        <?php foreach ($category as $pluginName => $plugin): ?>
                                            <?php foreach ($plugin['items'] as $index => $item): ?>
                                                <?php if (isset($this->additionalMenu['MARKETINGSEO'][$categoryName][$pluginName]['values'][$index])): ?>
                                                    <?php echo $this->toasterAdminpanelItem(str_replace('{value}',
                                                            $this->translate($this->additionalMenu['MARKETINGSEO'][$categoryName][$pluginName]['values'][$index]),
                                                            $item)); ?>
                                                <?php else: ?>
                                                    <?php echo $this->toasterAdminpanelItem($item); ?>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            <?php unset($this->additionalMenu['MARKETINGSEO']); ?>
                        </div>
                    </div>
                </li>
            <?php endif; ?>
            <?php unset($this->additionalMenu['SEO']); ?>
            <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_CONFIG)): ?>
                <li class="section">
                    <a href="#" class="section-btn _i-plugins"></a>

                    <div class="section-wrap">
                        <div class="section-box">
                            <span class="section-title"><?php echo $this->translate('Plugins manager'); ?></span>
                            <ul class="category-list">
                                <li class="item"><?php echo $this->toasterLink('backend_plugin', 'plugin',
                                        $this->translate('Manage plugins'), false, false,
                                        array('width' => '960', 'height' => '560')); ?></li>
                            </ul>

                                <!-- output plugins additional menus -->
                                <?php if (isset($this->additionalMenu['DEFAULT'])): ?>
                                    <?php foreach ($this->additionalMenu['DEFAULT'] as $categoryName => $category): ?>
                                        <ul class="category-list">
                                        <?php if ($categoryName !== 'DEFAULT') : ?>
                                            <li class="item title"><?php echo $categoryName; ?></li>
                                        <?php endif; ?>
                                        <?php foreach ($category as $pluginName => $plugin): ?>

                                            <?php foreach ($plugin['items'] as $index => $item): ?>
                                                <?php if (isset($this->additionalMenu['DEFAULT'][$categoryName][$pluginName]['values'][$index])): ?>
                                                    <?php echo $this->toasterAdminpanelItem(str_replace('{value}',
                                                        $this->translate($this->additionalMenu['DEFAULT'][$categoryName][$pluginName]['values'][$index]),
                                                        $item)); ?>
                                                <?php else: ?>
                                                    <?php echo $this->toasterAdminpanelItem($item); ?>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                        </ul>
                                    <?php endforeach; ?>
                                    <?php unset($this->additionalMenu['DEFAULT']); ?>
                                <?php endif; ?>
                          
                        </div>
                    </div>
                </li>
            <?php endif; ?>
            <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_CONFIG)): ?>
                <li class="section">
                    <a href="#" class="section-btn _i-setup"></a>

                    <div class="section-wrap">
                        <div class="section-box">
                            <span class="section-title"><?php echo $this->translate('Website configs'); ?></span>
                            <ul class="category-list">
                                <li class="item title"><?php echo $this->translate('OTHER'); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_config', 'config',
                                        $this->translate('Website configs'), false, false,
                                        array('width' => '720', 'height' => '360')); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_config', 'actionmails',
                                        $this->translate('E-mails & SMS actions'), false, false,
                                        array('width' => '960', 'height' => '560')); ?></li>
                                <li class="item"><?php echo $this->toasterLink('backend_theme', 'themes',
                                        $this->translate('Organize themes'), false, false,
                                        array('width' => '960', 'height' => '560')); ?></li>
                                <?php if (Tools_Security_Acl::isAllowed(Tools_Security_Acl::RESOURCE_USERS)): ?>
                                    <li class="item"><?php echo $this->toasterLink('backend_user', 'manage',
                                            $this->translate('Manage users'), false, false,
                                            array('width' => '960', 'height' => '560')); ?></li>
                                <?php endif; ?>
                            </ul>
                            <!-- start section: SETUP -->
                            <?php if (isset($this->additionalMenu) && isset($this->additionalMenu['SETUP'])): ?>
                                <?php foreach ($this->additionalMenu['SETUP'] as $categoryName => $category): ?>
                                    <ul class="category-list">
                                        <?php if ($categoryName !== 'DEFAULT') : ?>
                                            <li class="item title"><?php echo $categoryName; ?></li>
                                        <?php endif; ?>
                                        <?php foreach ($category as $pluginName => $plugin): ?>
                                            <?php foreach ($plugin['items'] as $index => $item): ?>
                                                <?php if (isset($this->additionalMenu['SETUP'][$categoryName][$pluginName]['values'][$index])): ?>
                                                    <?php echo $this->toasterAdminpanelItem(str_replace('{value}',
                                                            $this->translate($this->additionalMenu['SETUP'][$categoryName][$pluginName]['values'][$index]),
                                                            $item)); ?>
                                                <?php else: ?>
                                                    <?php echo $this->toasterAdminpanelItem($item); ?>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        <?php endforeach; ?>
                                    </ul>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            <?php unset($this->additionalMenu['SETUP']); ?>
                        </div>
                    </div>
                </li>
                <?php if (!empty($this->additionalMenu)): ?>
                    <?php foreach ($this->additionalMenu as $addName => $additionalMenuItem): ?>
                        <?php if ($addName === 'DEFAULT') : ?>
                            <?php continue; ?>
                        <?php endif; ?>
                        <li class="section">
                            <a href="#" class="section-btn _i-<?php echo strtolower(str_replace(' ', '-', str_replace('&', 'and', $addName))); ?>"></a>

                            <div class="section-wrap">
                                <div class="section-box">
                                <span
                                    class="section-title"><?php echo $this->translate(ucfirst(strtolower($addName))); ?></span>
                                    <ul class="category-list">
                                        <?php if (isset($this->additionalMenu)): ?>
                                            <?php foreach ($this->additionalMenu[$addName] as $categoryName => $category): ?>
                                                <?php if ($categoryName !== 'DEFAULT') : ?>
                                                    <li class="item title"><?php echo $categoryName; ?></li>
                                                <?php endif; ?>
                                                <?php foreach ($category as $pluginName => $plugin): ?>
                                                    <?php $itemsWithLinks = preg_grep('~open-new-link-admin-panel~', $plugin['items']);?>
                                                    <?php if(!empty($itemsWithLinks)) :?>
                                                        <?php foreach($itemsWithLinks as $itemWithLinkKey => $itemWithLinkValue) :?>
                                                            <?php unset($plugin['items'][$itemWithLinkKey]);?>
                                                            <?php $plugin['items'][] = $itemWithLinkValue;?>
                                                            <?php end($plugin['items']);?>
                                                            <?php $this->additionalMenu[$addName][$categoryName][$pluginName]['values'][key($plugin['items'])] = $this->additionalMenu[$addName][$categoryName][$pluginName]['values'][$itemWithLinkKey];?>
                                                            <?php unset($this->additionalMenu[$addName][$categoryName][$pluginName]['values'][$itemWithLinkKey]);?>
                                                        <?php endforeach;?>
                                                     <?php endif;?>
                                                    <?php foreach ($plugin['items'] as $index => $item): ?>
                                                        <?php if (isset($this->additionalMenu[$addName][$categoryName][$pluginName]['values'][$index])): ?>
                                                            <?php echo $this->toasterAdminpanelItem(str_replace('{value}',
                                                                    $this->translate($this->additionalMenu[$addName][$categoryName][$pluginName]['values'][$index]),
                                                                    $item)); ?>
                                                        <?php else: ?>
                                                            <?php echo $this->toasterAdminpanelItem($item); ?>
                                                        <?php endif; ?>
                                                    <?php endforeach; ?>
                                                <?php endforeach; ?>
                                            <?php endforeach; ?>
                                            <?php unset($this->additionalMenu[$addName]); ?>
                                            </ul>
                                        <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
            </ul><ul class="section-list">
            <?php endif; ?>
            <li class="section">
                <a class="section-btn _i-refresh no-open-section" href="javascript:;" id="cleancache"
                   title="<?php echo $this->translate('CLEAN CACHE'); ?>"></a>
            </li>
        <?php endif; ?>
        <li class="section">
            <a href="<?php echo $this->websiteUrl; ?>logout/" class="section-btn _i-exit no-open-section"
               title="<?php echo $this->translate('LOGOUT'); ?>"></a>
        </li>
    </ul>
    <span class="show-hide _i-panel-hide"></span>
    <span class="edit404-msg hide">
        <?php echo $this->translate("Sorry, but you don't have a custom - 404 not found - page yet. Click %1\$s to create a 404 page using the appropriate option found under the \"Settings\" section",
            $this->toasterLink('backend_page', 'page', $this->translate('here'), false, false,
                array('width' => '960', 'height' => '560'))); ?>
    </span>
</div>
