<form id="<?php echo $this->formId; ?>" method="<?php echo Zend_Form::METHOD_POST; ?>" action="<?php echo $this->actionUrl;?>">
	<div>
		<button id="<?php echo $this->formId; ?>-pickfiles"><?php echo $this->translate($this->buttonCaption); ?></button>
	</div>
</form>
<?php $jsValName = 'js'.str_replace(' ','',ucwords(str_replace('-', ' ', $this->formId))); ?>
<?php $this->jQuery()->onLoadCaptureStart();?>
	var <?php echo $jsValName; ?> = new plupload.Uploader({
		runtimes : 'html5,flash,html4',
		browse_button : '<?php echo $this->formId; ?>-pickfiles',
		max_file_size : '10mb',
		url : $('#<?php echo $this->formId; ?>').attr('action'),
		<?php if ($this->caller == 'images'): ?>
		resize : {width : <?php echo $this->config['img_max_width']; ?>, height : <?php echo $this->config['img_max_width']; ?>, quality : <?php echo $this->config['img_quality']; ?>},
		<?php endif; ?>
		flash_swf_url : '<?php echo $this->websiteUrl;?>system/js/external/plupload/plupload.flash.swf',
		<?php if ($this->filters): ?>
		filters : [<?php foreach ($this->filters as $title){ echo $this->fileTypes[$title] ? json_encode($this->fileTypes[$title]).PHP_EOL : ''; } ?>]
		<?php endif;?>
	});

	<?php echo $jsValName; ?>.bind('Init', function(up, params) {
		if ($('#<?php echo $this->formId;?>-filelist').size() == 0) {
			$('#<?php echo $this->formId;?>').before('<div id="<?php echo $this->formId;?>-filelist"></div>');
		}
		$('#<?php echo $this->formId; ?>-filelist').html("<div>Current runtime: " + params.runtime + "</div>");
	});
	
	<?php echo $jsValName; ?>.init();
	
	<?php echo $jsValName; ?>.bind('FilesAdded', function(up, files) {
		$.each(files, function(i, file) {
			$('#<?php echo $this->formId; ?>-filelist').append(
                '<div id="' + file.id + '">' +
                file.name + ' (' + plupload.formatSize(file.size) + ') <div class="pbar"></div>' +
            '</div>');
			$('#' + file.id + " .pbar").progressbar({value: 0})
		});
		up.refresh(); // Reposition Flash/Silverlight
		
		<?php echo $jsValName; ?>.start();
	});
	
	<?php echo $jsValName; ?>.bind('FilesRemoved', function(up, files) {
		$.each(files, function(i, file) {
			$('#' + file.id).remove();
		});
		up.refresh(); // Reposition Flash/Silverlight
	});

	<?php echo $jsValName; ?>.bind('UploadProgress', function(up, file) {
		$('#' + file.id + " pbar").progressbar({value: file.percent});
	});

    <?php echo $jsValName; ?>.bind('Error', function(up, err) {
        $('#<?php echo $this->formId; ?>-filelist').append('<span class="ui-icon ui-icon-alert"></span>'+
                     (err.file ? err.file.name : "") + ": " + err.message
					 );
        up.refresh(); // Reposition Flash/Silverlight
    });
    
    <?php echo $jsValName; ?>.bind('FileUploaded', function(up, file, info) {
		response = jQuery.parseJSON(info.response);
		if (response.error == true){
			$('#' + file.id).html('<span class="ui-icon ui-icon-alert"></span> ' + file.name 
			+ ( typeof(response.result) == 'object' ? response.result.join('<br/>') : response.result )
			);
		} else {
			$('#' + file.id).find('.pbar').remove().end().append('<span class="ui-icon ui-icon-check ui-corner-all"></span>');
		}	
		<?php if ($this->caller == 'themes') : ?>
		$('#themes-list').trigger('updateContent');
		<?php endif; ?>
    });
	
	<?php if ($this->caller == 'images'): ?>
	<?php echo $jsValName; ?>.bind('BeforeUpload', function (up, file) {
		$('#images-select-folder').attr('disabled', true);
		$('#images-new-folder').attr('disabled', true);
		var newfolder = $('#images-new-folder').val();
		if ( newfolder !== $('#images-new-folder').attr('data-defaultlabel') && newfolder != '' ) {
			<?php echo $jsValName; ?>.settings.multipart_params = {'folder': newfolder};
		} else {
			var folder = $('#images-select-folder').val();
			if (folder != '0' && folder != '') {
			<?php echo $jsValName; ?>.settings.multipart_params = {'folder': folder};
			} else {
			console.log('No folder specified');
			<?php echo $jsValName; ?>.removeFile(file);
			<?php echo $jsValName; ?>.stop();
			
			<?php echo $jsValName; ?>.refresh();
			}
		}
   		$('#images-select-folder').removeAttr('disabled');  
		$('#images-new-folder').removeAttr('disabled');
		});
	<?php endif; ?>

<?php $this->jQuery()->onLoadCaptureEnd(); ?>