<form id="<?php echo $this->formId; ?>" method="<?php echo Zend_Form::METHOD_POST; ?>" action="<?php echo $this->actionUrl;?>">
	<div>
		<button id="<?php echo $this->formId; ?>-pickfiles"><?php echo $this->translate($this->buttonCaption); ?></button>
	</div>
</form>
<?php $jsValName = 'js'.str_replace(' ','',ucwords(str_replace('-', ' ', $this->formId))); ?>
<?php $this->jQuery()->onLoadCaptureStart();?>
	var <?php echo $jsValName; ?> = new plupload.Uploader({
		runtimes : 'html5,flash,html4',
		browse_button : '<?php echo $this->formId; ?>-pickfiles',
		max_file_size : '10mb',
		max_file_count: 10,
		url : $('#<?php echo $this->formId; ?>').attr('action'),
		<?php if (!$this->disableResize): ?>
		<?php switch ($this->caller){
			case 'templatePreview':
				$maxWidth  = $this->config['template_preview_w'];
				$maxHeight = $this->config['template_preview_h'];
				break;
			default:
				$maxWidth = $this->config['img_max_width'];
				$maxHeight = $maxWidth;
				break;
		}
		?>
		resize : {width : <?php echo $maxWidth; ?>, height : <?php echo $maxHeight; ?>, quality : <?php echo $this->config['img_quality']; ?>},
		<?php endif; ?>
		flash_swf_url : '<?php echo $this->websiteUrl;?>system/js/external/plupload/plupload.flash.swf',
		<?php if ($this->filters): ?>
		filters : [<?php foreach ($this->filters as $title){ echo $this->fileTypes[$title] ? json_encode($this->fileTypes[$title]).PHP_EOL : ''; } ?>]
		<?php endif;?>
	});

	<?php echo $jsValName; ?>.bind('Init', function(up, params) {
		<?php if ($this->caller == 'templatePreview') : //positioning for template screen ?>
		var pos = $('#template_preview').position();
		var width = $('#template_preview').width();
		var height = $('#template_preview').height();
		$('#<?php echo $this->formId; ?>').css({
			'position': 'absolute',
			'left':	pos.left,
			'top':	pos.top+height
		});
		<?php endif; ?>
		if ($('#<?php echo $this->formId;?>-filelist').size() == 0) {
			$('#<?php echo $this->formId;?>').before('<div id="<?php echo $this->formId;?>-filelist"></div>');
		}
		$('#<?php echo $this->formId; ?>-filelist').html('');
		if (window.console){
			console.log('Current runtime: ' + params.runtime);
		}
	});
	
	<?php echo $jsValName; ?>.init();
	
	<?php echo $jsValName; ?>.bind('FilesAdded', function(up, files) {
		$.each(files, function(i, file) {
			$('#<?php echo $this->formId; ?>-filelist').prepend(
                '<div class="ui-widget"><div class="ui-state-highlight ui-corner-all" id="' + file.id + '"><p>' +
                file.name + ' (' + plupload.formatSize(file.size) + ')</p><div class="pbar"></div>' +
            '</div></div>');
			$('#' + file.id + " .pbar").progressbar({value: 0})
		});
		up.refresh(); // Reposition Flash/Silverlight
		
		<?php echo $jsValName; ?>.start();
	});
	
	<?php echo $jsValName; ?>.bind('FilesRemoved', function(up, files) {
		$.each(files, function(i, file) {
			$('#' + file.id).closest('div.ui-widget').remove().end().remove();
		});
		up.refresh(); // Reposition Flash/Silverlight
	});

	<?php echo $jsValName; ?>.bind('UploadProgress', function(up, file) {
		$('#' + file.id + " .pbar").progressbar({value: file.percent});
		window.console && console.log(file.name+': '+file.percent+'%');
	});

    <?php echo $jsValName; ?>.bind('Error', function(up, err) {
		$('#<?php echo $this->formId; ?>-filelist').prepend('<div class="ui-widget"><div class="ui-state-error ui-corner-all">'+
                     (err.file ? err.file.name : "") + ": " + err.message + 
					 '<span class="ui-icon ui-icon-alert"></span></div></div>'
					 );
        up.refresh(); // Reposition Flash/Silverlight
    });
    
    <?php echo $jsValName; ?>.bind('FileUploaded', function(up, file, info) {
		response = jQuery.parseJSON(info.response);
		if (response.error == true){
			var errorMessage = '<ul>';
			if  (typeof(response.result) == 'object') {
				for (var i in response.result) {
					errorMessage += '<li>'+response.result[i]+'</li>';
				}
			} else {
				errorMessage += response.result;
			}
			errorMessage += '</ul>';
			$('#' + file.id).html('<p><strong>' +file.name+'</strong>'
			+ errorMessage.replace("'file'", file.name) + '<span class="ui-icon ui-icon-alert"></span></p>' );
		} else {
			$('#' + file.id).find('.pbar').remove().end().append('<span class="ui-icon ui-icon-check ui-corner-all"></span>');
		}	
		<?php if ($this->caller == 'themes') : ?>
		$('#themes-list').trigger('updateContent');
		<?php elseif ($this->caller == 'templatePreview'): ?>
		window.console && console.log(response);
		if (response.error == false && response.hasOwnProperty('thumb')){
			$('#template_preview').attr('src', response.thumb);
		}
		<?php endif; ?>
    });
	
	<?php if ($this->caller == 'media'): ?>
	<?php echo $jsValName; ?>.bind('BeforeUpload', function (up, file) {
		$('#things-select-folder').attr('disabled', true);
		$('#things-new-folder').attr('disabled', true);
		var newfolder = $('#things-new-folder').val();
		if ( newfolder !== $('#things-new-folder').attr('data-defaultlabel') && newfolder != '' ) {
			<?php echo $jsValName; ?>.settings.multipart_params = {'folder': newfolder};
		} else {
			var folder = $('#things-select-folder').val();
			if (folder != '0' && folder != '') {
			<?php echo $jsValName; ?>.settings.multipart_params = {'folder': folder};
			} else {
			$('#ajax_msg').html('<?php echo $this->translate('No folder specified'); ?>')
				.show()
				.one('click', function(){$(this).hide()});
			
			<?php echo $jsValName; ?>.removeFile(file);
			<?php echo $jsValName; ?>.stop();
			<?php echo $jsValName; ?>.refresh();
			}
		}
   		$('#things-select-folder').removeAttr('disabled');  
		$('#things-new-folder').removeAttr('disabled');
		});
	<?php elseif ($this->caller == 'templatePreview'): ?>
	<?php echo $jsValName; ?>.bind('BeforeUpload', function (up, file) {	
			<?php echo $jsValName; ?>.settings.multipart_params = {'templateName': $('#title').val()};
		});
	<?php endif; ?>

<?php $this->jQuery()->onLoadCaptureEnd(); ?>