<?php
    if(isset($this->defaultText)){
        echo $this->defaultText;
    }

    $staticOption = (!empty($this->staticOption)) ? $this->staticOption : '';

    switch($this->elementType) {
        case Widgets_Prepop_Prepop::TYPE_TEXT:
            echo $this->formText($this->prepopName, html_entity_decode($this->prepopContent), array(
                    'class' => $this->prepopName . $staticOption . ' prepop-' . $this->elementType,
                    'maxlength' => ($this->limit) ? $this->limit : '',
                    'data-prepop-container-id' => $this->prepopConainerId
            ));
        break;
        case Widgets_Prepop_Prepop::TYPE_SELECT:
            if(!empty($this->defaultOptionSelection)) {
                $defaultOptionSelection[0] = $this->defaultOptionSelection;
                $this->options = $defaultOptionSelection + $this->options;
            }
            echo $this->formSelect($this->prepopName, $this->prepopContent, array(
                    'class' => $this->prepopName . $staticOption . ' prepop-' . $this->elementType,
                    'data-prepop-container-id' => $this->prepopConainerId
            ), $this->options);
        break;
        case Widgets_Prepop_Prepop::TYPE_RADIO:
            echo $this->formRadio($this->prepopName, $this->prepopContent, array(
                    'class'      => $this->prepopName . ' prepop-' . $this->elementType,
                    'data-prepop-container-id' => $this->prepopConainerId
                ),
            $this->options);
        break;
        case Widgets_Prepop_Prepop::TYPE_TEXTAREA:
            echo $this->formTextarea($this->prepopName, html_entity_decode($this->prepopContent), array(
                    'class' => $this->prepopName . ' prepop-' . $this->elementType,
                    'maxlength' => ($this->limit) ? $this->limit : '',
                    'data-prepop-container-id' => $this->prepopConainerId
                )
            );
        break;
        case Widgets_Prepop_Prepop::TYPE_CHECKBOX:
            echo $this->formMultiCheckbox($this->prepopName, ($this->prepopContent) ? explode('~', $this->prepopContent) : null, array(
                'class'      => $this->prepopName . ' prepop-' . $this->elementType,
                'data-prepop-container-id' => $this->prepopConainerId
            ),
            $this->options);
        break;
    }
?>

<?php if(isset($this->customScriptInclude)):?>
    <script type="application/javascript">
        $(document).ready(function(){
<?php else:?>
    <?php $this->jQuery()->onLoadCaptureStart(); ?>
<?php endif;?>

    var prepop = {
        webisteUrl: '<?php echo $this->websiteUrl; ?>',
        name: null,
        type: null,
        content: null,
        container: {
            name: null,
            type: null,
            id:   null,
            published: true
        },
        options: {},
        url: function() {
            var self = this;
            if(!isNaN(parseInt(self.container.id))) {
                return self.webisteUrl + 'backend/backend_content/edit/id/' + self.container.id + '/containerType/' + self.container.type;
            }
            return self.webisteUrl + 'backend/backend_content/add/containerType/' + self.container.type + '/containerName/' + self.container.name + '/pageId/' + self.pageId;
        },
        exec: function() {
            var self    = this;
            var isValid = self._validate();
            if(isValid !== true) {
                showMessage(isValid.error, true);
                return false;
            }

            $.post(self.url(), {
                containerType : self.container.type,
                containerId   : self.container.id,
                content       : self.content,
                pageId        : self.pageId,
                containerName : self.container.name,
                published     : self.container.published,
                secureToken   : self.secureToken
            }, null, 'json')
                .done(function(response) {
                    if (parseInt(response.error) === 0 && !self.container.id) {
                        $(self.elSelector).data('prepop-container-id', response.responseText);
                    } else if(parseInt(response.error) === 1) {
                        showMessage(response.responseText, true);
                    }
                })
                .fail(function(xhr, status, error) {
                    console.error('Error:', status, error);
                });

        },
        _validate: function() {
            var self     = this;
            self.content = self.content.replace(/<script>/g, '&lt;script&gt;').replace(/<\/script>/, '&lt;/script&gt;');
            if(self.options.hasOwnProperty('limit') && (self.content.length > self.options.limit)) {
                return {'error': 'Hey, not so fast! It is to mcuch text here. Please remove some to fit ' + self.options.limit + ' characters limit'};
            }
            return true;
        }
    };
<?php if(!isset($this->customScriptInclude)):?>
    <?php $this->jQuery()->onLoadCaptureEnd(); ?>
    <?php $this->jQuery()->onLoadCaptureStart(); ?>
<?php endif;?>

    $(document).on('<?php echo $this->onJsElementAction; ?>', '<?php echo (($this->prepopName) ? ('.' . $this->prepopName . $staticOption) : ''); ?>.prepop-<?php echo $this->elementType; ?>', function (e) {
        //init prepop specific fields
        prepop.pageId = '<?php echo $this->commonOptions['pageId']; ?>';
        prepop.container.type = '<?php echo $this->commonOptions['containerType']; ?>';
        prepop.container.name = '<?php echo $this->commonOptions['containerName']; ?>';
        prepop.type = '<?php echo $this->elementType; ?>';

        var elSelector = '#'+prepop.container.name;

        if (prepop.type === 'radio') {
            elSelector = '.'+prepop.container.name+'.prepop-radio';
        }

        if (prepop.type === 'checkbox') {
            elSelector = '.'+prepop.container.name+'.prepop-checkbox';
        }

        prepop.elSelector = elSelector;

        if (!$(prepop.elSelector).data('prepop-container-id')) {
            prepop.container.id = '<?php echo $this->prepopConainerId; ?>';
        } else {
            prepop.container.id = $(prepop.elSelector).data('prepop-container-id');
        }

        prepop.name = '<?php echo $this->prepopName; ?>';
        prepop.secureToken = '<?php echo $this->secureToken; ?>';
        //setting the content
        prepop.content = $(e.currentTarget).val();
        if (prepop.type == '<?php echo Widgets_Prepop_Prepop::TYPE_CHECKBOX; ?>') {
            prepop.content = '';
            $('input[type=checkbox].' + prepop.name + ':checked').each(function () {
                prepop.content += '~' + $(this).val();
            });
        }
        //setting up an additional options
        <?php if(isset($this->limit) && $this->limit): ?>
        prepop.options.limit = '<?php echo $this->limit; ?>';
        <?php endif; ?>
        //executing the prepop
        prepop.exec();
    });
<?php if(isset($this->customScriptInclude)):?>
        });
        </script>
<?php else:?>
        <?php $this->jQuery()->onLoadCaptureEnd(); ?>
<?php endif;?>

