
<a class="prepop-content" href="javascript:;" title="<?php echo $this->prepopContent;?>" id="prepop-<?php echo $this->prepopName;?>"><?php echo $this->prepopContent;?></a>

<?php $this->jQuery()->onLoadCaptureStart() ?>
    $(function() {
        $(document).on('click', 'a.prepop-content', function(e) {
            e.preventDefault();
            var urlAction = "<?php echo $this->websiteUrl;?>backend/search/complexsearch/";
            var searchValues = [];
            var containerNames = [];
            var prepopName = $(this).attr('id');
            var prepopValue = $(this).attr('title');
            containerNames.push(prepopName.replace('prepop-', ''));
            searchValues.push(prepopValue);
            $.ajax({
                type: "POST",
                url: urlAction,
                dataType: "json",
                data: {
                    searchValues: searchValues,
                    containerNames:containerNames
                },
            success: function(responce){
                  var url = responce.redirect;
                  window.location = url;
            }
          
         });
            return false;
            
        });
    });
<?php $this->jQuery()->onLoadCaptureEnd() ?>
