<?php if(isset($this->images) && is_array($this->images) && !empty($this->images)): ?>
	<ul class="img_gallery">
		<?php foreach ($this->images as $image): ?>
			<?php $size = getimagesize($this->galFolder . $image); ?>
			<li class="gallery_image">
				<a class="gall" href="<?php echo $this->original . $image; ?>" rel="<?php echo $this->folder; ?>" title="<?php echo Tools_System_Tools::cutExtension($image); ?>">
					<img src="<?php echo $this->galFolder . $image; ?>" alt="<?php echo Tools_System_Tools::cutExtension($image); ?>" width="<?php echo $size[0]; ?>" height="<?php echo $size[1]; ?>" />
				</a>
				<?php if($this->useCaption): ?>
					<p class="image_caption"><?php echo $image; ?></p>
				<?php endif; ?>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
<p style="clear:both;"></p>
<script type="text/javascript">
	$("a[rel=<?php echo $this->folder; ?>]").fancybox({
				'transitionIn'		: 'none',
				'transitionOut'		: 'none',
				'titlePosition' 	: 'over'
	});
</script>
