<div class="widget-control-img" id="gal-img"></div>
<form class="wmc-block" id="gal-widget-form" action="javascript:;" style="display: none;" method="post">

	<label class="nopad grid_6" for="gal-folders"><?php echo $this->translate('Select a folder'); ?></label>
	<select class="nopad grid_6" id="gal-folders"></select>

	<label class="nopad grid_6" for="gal-thumb-size"><?php echo $this->translate('Thumb. size'); ?></label>
	<input type="text" class="nopad grid_6" id="gal-thumb-size" value="<?php echo Widgets_Gal_Gal::DEFAULT_THUMB_SIZE; ?>"/>

	<label class="nopad grid_6" for="gal-crop"><?php echo $this->translate('Crop image'); ?></label>
	<div class="nopad grid_6"><input type="checkbox" id="gal-crop" /></div>

	<label class="nopad grid_6" for="gal-caption"><?php echo $this->translate('Caption'); ?></label>
	<div class="nopad grid_6"><input type="checkbox" id="gal-caption" /></div>

	<div class="grid_12"><input class="formsubmit" type="submit" id="gal-done" name="done" value="Done" /></div>
</form>
<script type="text/javascript">
	$(function() {
		loadFolders();
		$('.widget-control-img#gal-img').click(function() {
			$('#widgets-header').text('<?php echo $this->translate('Image gallery'); ?>').fadeIn();
			$('#widget-controls').html($('#gal-widget-form').html());
			//$('#gal-widget-form').slideDown();
		});

		$('#gal-done').live('click', function() {
			var widget = '{$gal:' + $('#gal-folders').val() + ':' + $('#gal-thumb-size').val() + ':' + ($('#gal-crop').attr('checked') ? 1 : 0) + ':' + ($('#gal-caption').attr('checked') ? 1 : 0) + '}';
			$('textarea.tinymce').tinymce().execCommand('mceInsertContent', false, widget);
		})
	})

	function loadFolders() {
		$.getJSON($('#website_url').val() + 'backend/backend_media/loadfolders/', function(response) {
			$.each(response.responseText, function(val) {
				$('#gal-folders')
					.append($('<option></option>').attr({
						value: val
					})
					.text(val));
			})
		});
	}
</script>
